/**
 * Drizzle ORM schema for the apps/site Neon Postgres database.
 *
 * This file is the **privacy contract** for marketplace install telemetry. The
 * `marketplaceInstallEvents` table stores aggregate, non-PII events recorded
 * by `dorkos install` when telemetry is opt-in. Adding a column here is the
 * single chokepoint for what we are allowed to collect — the ESLint and test
 * suite enforce that no field which could identify a user (IP address, user
 * agent, hostname, username, working directory, etc.) ever lands here.
 *
 * Tasks #6 (read helpers) and #15 (write endpoint) consume this schema.
 *
 * The Better Auth **DorkOS account** tables (`user`, `session`, `account`,
 * `verification`), the plugin tables (`apikey`, `deviceCode`), the device-link
 * `instance` registry, and the `audit_log` are defined in `./auth-schema.ts` /
 * `./instance-schema.ts` / `./audit-schema.ts` and re-exported below so
 * drizzle-kit and the db client see one schema. They are hard-isolated from
 * `marketplaceInstallEvents` — no foreign keys, join columns, or shared
 * identifiers cross the account ↔ telemetry boundary (see `auth-schema.ts`).
 *
 * @module db/schema
 */
import {
  bigserial,
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

export { account, apikey, deviceCode, session, user, verification } from './auth-schema';
export { instance, type Instance, type NewInstance } from './instance-schema';
export { auditLog, type AuditLogEntry, type NewAuditLogEntry } from './audit-schema';
export {
  newsletterSubscriber,
  type NewsletterSubscriber,
  type NewNewsletterSubscriber,
  type NewsletterStatus,
  type NewsletterSource,
} from './newsletter-schema';

/**
 * `marketplace_install_events` — append-only event log for opt-in install
 * telemetry from `dorkos install`.
 *
 * The columns below are the **complete allowed set**. The schema test in
 * `__tests__/schema.test.ts` enforces negative assertions on PII columns
 * (ipAddress, userAgent, hostname, username, cwd) — those must never be
 * added here.
 */
export const marketplaceInstallEvents = pgTable(
  'marketplace_install_events',
  {
    /** Surrogate primary key. Bigserial so we can grow past 2B rows. */
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    /** Package name from marketplace.json (e.g. `code-reviewer`). 1..64 chars. */
    packageName: text('package_name').notNull(),
    /** Marketplace identifier (e.g. `dorkos-community`). 1..64 chars. */
    marketplace: text('marketplace').notNull(),
    /** Package type — agent | plugin | skill-pack | adapter. */
    type: text('type').notNull(),
    /** Install outcome — success | failure | cancelled. */
    outcome: text('outcome').notNull(),
    /** Wall-clock duration of the install attempt in milliseconds. */
    durationMs: integer('duration_ms').notNull(),
    /** Optional error code (≤64 chars) when outcome is failure. */
    errorCode: text('error_code'),
    /**
     * Random per-install UUID. Generated by the CLI for each install attempt.
     * Not tied to a user — re-installing the same package emits a fresh UUID.
     */
    installId: uuid('install_id').notNull(),
    /** DorkOS version that emitted the event (e.g. `0.4.2`). ≤32 chars. */
    dorkosVersion: text('dorkos_version').notNull(),
    /**
     * Marketplace source type the plugin was installed from. One of
     * `relative-path`, `github`, `url`, `git-subdir`, `npm`. Added in
     * marketplace-05 so we can track adoption of each source form over
     * time. Not PII — purely an install-pipeline metadata field.
     */
    sourceType: text('source_type').notNull(),
    /** Server-side receive timestamp. Trust this, never the client clock. */
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_install_events_package_received').on(t.packageName, t.receivedAt.desc()),
    index('idx_install_events_marketplace_received').on(t.marketplace, t.receivedAt.desc()),
  ]
);

/** A row read from `marketplace_install_events`. */
export type MarketplaceInstallEvent = typeof marketplaceInstallEvents.$inferSelect;

/** A row insertable into `marketplace_install_events`. */
export type NewMarketplaceInstallEvent = typeof marketplaceInstallEvents.$inferInsert;

/**
 * `instance_heartbeats` — append-only log for the opt-in weekly heartbeat
 * (DOR-293). One row per ping lets us count "known weekly-active instances".
 *
 * The columns below are the **complete allowed set**. Like
 * `marketplace_install_events`, this table is the privacy contract: the schema
 * test in `__tests__/schema.test.ts` forbids any PII column (ipAddress,
 * userAgent, hostname, username, cwd). Every field here is anonymous and
 * aggregate-safe by construction. Public contract: https://dorkos.ai/telemetry.
 */
export const instanceHeartbeats = pgTable(
  'instance_heartbeats',
  {
    /** Surrogate primary key. */
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    /**
     * Random per-install UUID (shared with install telemetry). Identifies one
     * DorkOS installation so we can de-duplicate to weekly-active counts — NOT
     * a user, and never joined to any account table.
     */
    instanceId: uuid('instance_id').notNull(),
    /** DorkOS version that produced the heartbeat (e.g. `0.46.0`). */
    dorkosVersion: text('dorkos_version').notNull(),
    /** Platform and CPU architecture, e.g. `darwin-arm64`. */
    os: text('os').notNull(),
    /** Runtime ids the user has enabled, e.g. `{claude-code,codex}`. */
    runtimesConfigured: text('runtimes_configured').array().notNull(),
    /** Whether the public tunnel is enabled (mobile-access signal). */
    tunnelEnabled: boolean('tunnel_enabled').notNull(),
    /** Whether this instance is device-linked to a DorkOS account (fleet signal). */
    cloudLinked: boolean('cloud_linked').notNull(),
    /** Rough count of registered agents. */
    countAgents: integer('count_agents').notNull(),
    /** Rough count of scheduled tasks. */
    countTasks: integer('count_tasks').notNull(),
    /** Rough count of configured relay adapters. */
    countRelayAdapters: integer('count_relay_adapters').notNull(),
    /** Server-side receive timestamp. Trust this, never the client clock. */
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_heartbeats_instance_received').on(t.instanceId, t.receivedAt.desc()),
    index('idx_heartbeats_received').on(t.receivedAt.desc()),
  ]
);

/** A row read from `instance_heartbeats`. */
export type InstanceHeartbeat = typeof instanceHeartbeats.$inferSelect;

/** A row insertable into `instance_heartbeats`. */
export type NewInstanceHeartbeat = typeof instanceHeartbeats.$inferInsert;
