/**
 * Drizzle ORM schema for the apps/site Neon Postgres database.
 *
 * This file is the **privacy contract** for marketplace install telemetry. The
 * `marketplaceInstallEvents` table stores aggregate, non-PII events recorded
 * by `dorkos install` when telemetry is opt-in. Adding a column here is the
 * single chokepoint for what we are allowed to collect — the ESLint and test
 * suite enforce that no field which could identify a user (IP address, user
 * agent, hostname, username, working directory, etc.) ever lands here.
 *
 * Tasks #6 (read helpers) and #15 (write endpoint) consume this schema.
 *
 * @module db/schema
 */
import { bigserial, index, integer, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * `marketplace_install_events` — append-only event log for opt-in install
 * telemetry from `dorkos install`.
 *
 * The columns below are the **complete allowed set**. The schema test in
 * `__tests__/schema.test.ts` enforces negative assertions on PII columns
 * (ipAddress, userAgent, hostname, username, cwd) — those must never be
 * added here.
 */
export const marketplaceInstallEvents = pgTable(
  'marketplace_install_events',
  {
    /** Surrogate primary key. Bigserial so we can grow past 2B rows. */
    id: bigserial('id', { mode: 'bigint' }).primaryKey(),
    /** Package name from marketplace.json (e.g. `code-reviewer`). 1..64 chars. */
    packageName: text('package_name').notNull(),
    /** Marketplace identifier (e.g. `dorkos-community`). 1..64 chars. */
    marketplace: text('marketplace').notNull(),
    /** Package type — agent | plugin | skill-pack | adapter. */
    type: text('type').notNull(),
    /** Install outcome — success | failure | cancelled. */
    outcome: text('outcome').notNull(),
    /** Wall-clock duration of the install attempt in milliseconds. */
    durationMs: integer('duration_ms').notNull(),
    /** Optional error code (≤64 chars) when outcome is failure. */
    errorCode: text('error_code'),
    /**
     * Random per-install UUID. Generated by the CLI for each install attempt.
     * Not tied to a user — re-installing the same package emits a fresh UUID.
     */
    installId: uuid('install_id').notNull(),
    /** DorkOS version that emitted the event (e.g. `0.4.2`). ≤32 chars. */
    dorkosVersion: text('dorkos_version').notNull(),
    /**
     * Marketplace source type the plugin was installed from. One of
     * `relative-path`, `github`, `url`, `git-subdir`, `npm`. Added in
     * marketplace-05 so we can track adoption of each source form over
     * time. Not PII — purely an install-pipeline metadata field.
     */
    sourceType: text('source_type').notNull(),
    /** Server-side receive timestamp. Trust this, never the client clock. */
    receivedAt: timestamp('received_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('idx_install_events_package_received').on(t.packageName, t.receivedAt.desc()),
    index('idx_install_events_marketplace_received').on(t.marketplace, t.receivedAt.desc()),
  ]
);

/** A row read from `marketplace_install_events`. */
export type MarketplaceInstallEvent = typeof marketplaceInstallEvents.$inferSelect;

/** A row insertable into `marketplace_install_events`. */
export type NewMarketplaceInstallEvent = typeof marketplaceInstallEvents.$inferInsert;
