/**
 * Source-root declaration + ephemeral (gitignore) routing.
 *
 * The authored skill source root (`.agents/skills`) is committed. Installed
 * (marketplace) and adopted sources are EPHEMERAL — their on-disk projections are
 * gitignored, never committed — and carry richer per-plugin data than a flat skills
 * directory, so they are discovered by `scanInstalledPlugins` (`sources/installed.ts`)
 * rather than enumerated as a flat {@link SourceRoot} here.
 *
 * @module sources/resolve-roots
 */
import type { Provenance } from '../plan/types.js';
import { AGENTS_SKILLS_DIR } from '../scan/scanner.js';
import {
  CODEX_HOOKS_TARGET,
  CURSOR_HOOKS_TARGET,
  COPILOT_HOOKS_TARGET,
} from '../generate/hooks.js';

/** A skill source root and the provenance of everything found beneath it. */
export interface SourceRoot {
  /** Where skills under this root came from. */
  class: Provenance;
  /** Repo-relative skills directory for this root. */
  skillsDir: string;
}

/**
 * Resolve the authored skill source root for a repository.
 *
 * Installed/adopted sources are not flat roots (they carry per-plugin assets) and
 * are discovered by `scanInstalledPlugins`; this returns only the committed
 * authored root.
 *
 * @param _repoRoot - absolute repository root (reserved for future per-repo roots).
 * @returns the authored source root.
 */
export function resolveSourceRoots(_repoRoot: string): SourceRoot[] {
  return [{ class: 'authored', skillsDir: AGENTS_SKILLS_DIR }];
}

/**
 * Whether a projection's provenance is ephemeral — its on-disk output is
 * gitignored and regenerated by sync, never committed. Authored sources are
 * committed; installed and adopted sources are ephemeral.
 *
 * @param provenance - the projection's provenance.
 * @returns `true` when the projection should live in a gitignored location.
 */
export function isEphemeralProvenance(provenance: Provenance): boolean {
  return provenance !== 'authored';
}

/**
 * The `.gitignore` patterns the engine's ephemeral (installed/adopted) projections
 * require — the single source of truth for what `dorkos harness sync` expects to
 * be ignored so installed projections are never accidentally committed.
 *
 * Generated command wrappers (`.claude/commands/<pkg>/`) are deliberately NOT
 * listed here: a static per-subdirectory wildcard under `.claude/commands` would
 * also swallow authored namespaced commands (`.claude/commands/<ns>/`), so each
 * wrapper directory is kept out of git by a self-ignoring `.gitignore` the engine
 * writes inside it.
 */
export const EPHEMERAL_GITIGNORE_PATTERNS = [
  '.dork/plugins/', // marketplace-installed plugins (project scope)
  `${AGENTS_SKILLS_DIR}/*__*`, // Codex installed-plugin skill symlinks (<pkg>__<skill>)
  '.claude/skills/*__*', // Claude Code installed-plugin skill symlinks (<pkg>__<skill>)
  '.claude/settings.local.json', // user-owned local settings; the engine merges plugin hooks in
  CODEX_HOOKS_TARGET, // generated Codex hooks (folds in installed-plugin hooks)
  CURSOR_HOOKS_TARGET, // generated Cursor hooks (wholly engine-owned, regenerated each sync)
  COPILOT_HOOKS_TARGET, // generated Copilot hooks (wholly engine-owned, regenerated each sync)
] as const;
