// UI components
export { Hero } from './ui/Hero'
export { CredibilityBar } from './ui/CredibilityBar'
export { ProblemSection } from './ui/ProblemSection'
export { HowItWorksSection } from './ui/HowItWorksSection'
export { ProjectCard } from './ui/ProjectCard'
export { ProjectsGrid } from './ui/ProjectsGrid'
export { NotSection } from './ui/NotSection'
export { PhilosophyCard } from './ui/PhilosophyCard'
export { PhilosophyGrid } from './ui/PhilosophyGrid'
export { AboutSection } from './ui/AboutSection'
export { ContactSection } from './ui/ContactSection'
export { MarketingNav } from './ui/MarketingNav'
export { MarketingHeader } from './ui/MarketingHeader'
export { MarketingFooter } from './ui/MarketingFooter'
export { SystemArchitecture } from './ui/SystemArchitecture'
export { UseCasesGrid } from './ui/UseCasesGrid'
export { HonestySection } from './ui/HonestySection'
export { PulseAnimation } from './ui/PulseAnimation'

// Data
export { projects } from './lib/projects'
export { philosophyItems } from './lib/philosophy'
export { systemModules } from './lib/modules'
export { useCases } from './lib/use-cases'

// Types
export type { Project, PhilosophyItem, NavLink } from './lib/types'
export type { SystemModule } from './lib/modules'
export type { UseCase } from './lib/use-cases'
