import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { EventEmitter } from 'node:events';
import { PassThrough } from 'node:stream';
import type { ChildProcess } from 'node:child_process';
import {
  ChromeNotFoundError,
  chromeCandidates,
  findChrome,
  type ChromeLocatorEnv,
} from '../chrome-locator.js';
import { ChromeExitedError, launchChromeWithPipe } from '../cdp-pipe.js';
import {
  AGENT_BROWSER_PROFILE_NAME,
  AGENT_BROWSER_THEME_COLOR,
  THEME_MARKER_FILE,
  ensureAgentProfile,
  profileLock,
} from '../profile.js';
import {
  UnreadableStorageStateError,
  collectStorageState,
  readStorageState,
  toStorageStateCookie,
  writeStorageState,
} from '../storage-state.js';
import { forgetInProfile } from '../profile-cleanup.js';
import { createFakeCdp } from './fake-cdp.js';

let root: string;
beforeEach(() => {
  root = fs.mkdtempSync(path.join(tmpdir(), 'dorkos-agent-browser-lib-'));
});
afterEach(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

function locatorEnv(
  overrides: Partial<ChromeLocatorEnv>,
  present: string[] = []
): ChromeLocatorEnv {
  return {
    platform: 'darwin',
    homeDir: '/Users/me',
    exists: (file) => present.includes(file),
    ...overrides,
  };
}

describe('findChrome', () => {
  const MAC_CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

  it('prefers Google Chrome in /Applications on macOS', () => {
    expect(findChrome(locatorEnv({}, [MAC_CHROME]))).toBe(MAC_CHROME);
    expect(chromeCandidates(locatorEnv({}))[1]).toBe(
      '/Users/me/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    );
  });

  it('searches PATH on Linux, Chrome before Chromium', () => {
    const env = locatorEnv({ platform: 'linux', pathVar: '/usr/local/bin:/usr/bin' }, [
      '/usr/bin/chromium',
      '/usr/bin/google-chrome',
    ]);
    expect(findChrome(env)).toBe('/usr/bin/google-chrome');
  });

  it('looks in the per-user and machine-wide install folders on Windows', () => {
    const exe = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
    const env = locatorEnv(
      {
        platform: 'win32',
        localAppData: 'C:\\Users\\me\\AppData\\Local',
        programFiles: 'C:\\Program Files',
      },
      [exe]
    );
    expect(chromeCandidates(env)[0]).toBe(
      'C:\\Users\\me\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe'
    );
    expect(findChrome(env)).toBe(exe);
  });

  it('uses --chrome when it exists, and says so plainly when it does not', () => {
    expect(findChrome(locatorEnv({}, ['/opt/c']), '/opt/c')).toBe('/opt/c');
    expect(() => findChrome(locatorEnv({}), '/opt/missing')).toThrow(ChromeNotFoundError);
  });

  it('explains a missing Chrome: what it is for, how to get it, and where it looked', () => {
    let error: unknown;
    try {
      findChrome(locatorEnv({}));
    } catch (err) {
      error = err;
    }
    expect(error).toBeInstanceOf(ChromeNotFoundError);
    const message = (error as Error).message;
    expect(message).toContain('Could not find Google Chrome');
    expect(message).toContain('https://www.google.com/chrome/');
    expect(message).toContain('--chrome <path>');
    expect(message).toContain(MAC_CHROME);
  });
});

describe('ensureAgentProfile', () => {
  const readJson = (file: string) => JSON.parse(fs.readFileSync(file, 'utf8'));

  it('creates the profile with the theme and name before Chrome ever starts', () => {
    const profileDir = path.join(root, 'browser', 'profile');
    expect(ensureAgentProfile(profileDir)).toEqual({ created: true, themed: true });

    const prefs = readJson(path.join(profileDir, 'Default', 'Preferences'));
    expect(prefs.browser.theme).toMatchObject({
      user_color: AGENT_BROWSER_THEME_COLOR,
      user_color2: AGENT_BROWSER_THEME_COLOR,
      color_variant2: 3,
      color_scheme2: 1,
    });
    expect(AGENT_BROWSER_THEME_COLOR).toBe(-38144);
    expect(prefs.autogenerated.theme.color).toBe(AGENT_BROWSER_THEME_COLOR);
    expect(prefs.profile.name).toBe(AGENT_BROWSER_PROFILE_NAME);

    const localState = readJson(path.join(profileDir, 'Local State'));
    expect(localState.profile.info_cache.Default).toMatchObject({
      name: AGENT_BROWSER_PROFILE_NAME,
      is_using_default_name: false,
    });
    expect(fs.existsSync(path.join(profileDir, THEME_MARKER_FILE))).toBe(true);
    expect(fs.statSync(path.join(root, 'browser')).mode & 0o777).toBe(0o700);
    expect(fs.statSync(profileDir).mode & 0o777).toBe(0o700);
  });

  it('applies the theme once, so a colour picked later in Chrome is kept', () => {
    const profileDir = path.join(root, 'profile');
    ensureAgentProfile(profileDir);
    const prefsFile = path.join(profileDir, 'Default', 'Preferences');
    fs.writeFileSync(prefsFile, JSON.stringify({ browser: { theme: { user_color2: 42 } } }));
    expect(ensureAgentProfile(profileDir)).toEqual({ created: false, themed: false });
    expect(readJson(prefsFile).browser.theme.user_color2).toBe(42);
  });

  it('themes a profile made before DorkOS styled it, keeping its other settings', () => {
    const profileDir = path.join(root, 'profile');
    fs.mkdirSync(path.join(profileDir, 'Default'), { recursive: true });
    const prefsFile = path.join(profileDir, 'Default', 'Preferences');
    fs.writeFileSync(prefsFile, JSON.stringify({ extensions: { settings: { onepw: {} } } }));
    expect(ensureAgentProfile(profileDir)).toEqual({ created: false, themed: true });
    const prefs = readJson(prefsFile);
    expect(prefs.extensions.settings).toEqual({ onepw: {} });
    expect(prefs.browser.theme.user_color).toBe(AGENT_BROWSER_THEME_COLOR);
  });

  it('leaves a profile that already has its own colour alone', () => {
    const profileDir = path.join(root, 'profile');
    fs.mkdirSync(path.join(profileDir, 'Default'), { recursive: true });
    const prefsFile = path.join(profileDir, 'Default', 'Preferences');
    fs.writeFileSync(prefsFile, JSON.stringify({ browser: { theme: { user_color: 7 } } }));
    expect(ensureAgentProfile(profileDir).themed).toBe(false);
    expect(readJson(prefsFile).browser.theme).toEqual({ user_color: 7 });
  });
});

describe('profileLock', () => {
  it('reads the pid Chrome names in SingletonLock', () => {
    const live = path.join(root, 'live');
    fs.mkdirSync(live);
    fs.symlinkSync(`my-mac.local-${process.pid}`, path.join(live, 'SingletonLock'));
    expect(profileLock(live, 'darwin')).toEqual({ inUse: true, pid: process.pid });
  });

  it('treats a leftover lock from a crashed Chrome, or none, as free', () => {
    const stale = path.join(root, 'stale');
    fs.mkdirSync(stale);
    fs.symlinkSync('my-mac.local-2147483646', path.join(stale, 'SingletonLock'));
    expect(profileLock(stale, 'darwin')).toEqual({ inUse: false });
    expect(profileLock(root, 'linux')).toEqual({ inUse: false });
  });
});

describe('storage state file', () => {
  it('converts Chrome cookies exactly as Playwright does', () => {
    expect(
      toStorageStateCookie({
        name: 'sid',
        value: 'v',
        domain: '.a.test',
        path: '/',
        expires: 1_900_000_000,
        httpOnly: true,
        secure: true,
      })
    ).toEqual({
      name: 'sid',
      value: 'v',
      domain: '.a.test',
      path: '/',
      expires: 1_900_000_000,
      httpOnly: true,
      secure: true,
      sameSite: 'Lax',
    });
    expect(
      toStorageStateCookie({
        name: 's',
        value: 'v',
        domain: 'a.test',
        path: '/',
        expires: -1,
        httpOnly: false,
        secure: true,
        session: true,
        sameSite: 'None',
        partitionKey: { topLevelSite: 'https://top.test', hasCrossSiteAncestor: false },
      })
    ).toMatchObject({ expires: -1, sameSite: 'None', partitionKey: 'https://top.test' });
  });

  it('is written readable only by you, even over a looser file', async () => {
    const file = path.join(root, 'browser', 'storage-state.json');
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, '{}', { mode: 0o644 });
    await writeStorageState(file, { cookies: [], origins: [] });
    expect(fs.statSync(file).mode & 0o777).toBe(0o600);
    expect(readStorageState(file)).toEqual({ cookies: [], origins: [] });
  });

  it('reads a missing file as no session, and a garbled one as an error that says what to do', () => {
    expect(readStorageState(path.join(root, 'nope.json'))).toBeNull();
    const bad = path.join(root, 'bad.json');
    fs.writeFileSync(bad, '{"cookies": "no"}');
    expect(() => readStorageState(bad)).toThrow(UnreadableStorageStateError);
    expect(() => readStorageState(bad)).toThrow(/dorkos browser login/);
  });

  it('collects every cookie and the page storage of open web tabs', async () => {
    const cdp = createFakeCdp({
      'Storage.getCookies': () => ({
        cookies: [
          {
            name: 'sid',
            value: 'v',
            domain: 'a.test',
            path: '/',
            expires: -1,
            httpOnly: true,
            secure: true,
            session: true,
          },
        ],
      }),
      'Target.getTargets': () => ({
        targetInfos: [
          { targetId: 't1', type: 'page', url: 'https://a.test/home' },
          { targetId: 't2', type: 'page', url: 'chrome://newtab/' },
          { targetId: 't3', type: 'service_worker', url: 'https://a.test/sw.js' },
        ],
      }),
      'Target.attachToTarget': (params) => ({ sessionId: `s-${String(params.targetId)}` }),
      'DOMStorage.getDOMStorageItems': (params) => {
        const storageId = params.storageId as { securityOrigin: string };
        return storageId.securityOrigin === 'https://a.test' ? { entries: [['token', 'x']] } : {};
      },
    });
    const state = await collectStorageState(cdp);
    expect(state.cookies).toHaveLength(1);
    expect(state.origins).toEqual([
      { origin: 'https://a.test', localStorage: [{ name: 'token', value: 'x' }] },
    ]);
    // Only the web tab was opened up, and it was let go afterwards.
    expect(cdp.calls.filter((c) => c.method === 'Target.attachToTarget')).toHaveLength(1);
    expect(cdp.calls.some((c) => c.method === 'Target.detachFromTarget')).toBe(true);
  });
});

describe('collectStorageState against a hostile page', () => {
  /** A tab whose page script would answer anything it liked, if it were asked. */
  function hostileTab(entries: unknown) {
    return createFakeCdp({
      'Storage.getCookies': () => ({ cookies: [] }),
      'Target.getTargets': () => ({
        targetInfos: [{ targetId: 't1', type: 'page', url: 'https://evil.test/page?x=1' }],
      }),
      'Target.attachToTarget': () => ({ sessionId: 's1' }),
      // What a page overriding JSON.stringify would hand back to a script read:
      // storage planted for somebody else's origin.
      'Runtime.evaluate': () => ({
        result: {
          value: JSON.stringify({
            origin: 'https://bank.test',
            localStorage: [{ name: 'session', value: 'planted' }],
          }),
        },
      }),
      'DOMStorage.getDOMStorageItems': () => ({ entries }),
    });
  }

  it('never asks the page: the origin is the tab URL and the items are Chrome’s', async () => {
    const cdp = hostileTab([['theme', 'dark']]);
    const state = await collectStorageState(cdp);
    expect(state.origins).toEqual([
      { origin: 'https://evil.test', localStorage: [{ name: 'theme', value: 'dark' }] },
    ]);
    expect(cdp.calls.some((c) => c.method === 'Runtime.evaluate')).toBe(false);
    const read = cdp.calls.find((c) => c.method === 'DOMStorage.getDOMStorageItems')!;
    expect(read.params).toEqual({
      storageId: { securityOrigin: 'https://evil.test', isLocalStorage: true },
    });
  });

  it('drops an answer that is not the shape of page storage, instead of saving it', async () => {
    const state = await collectStorageState(
      hostileTab([
        ['ok', 'fine'],
        ['bad', { not: 'text' }],
      ])
    );
    expect(state.origins).toEqual([]);
  });
});

describe('forgetInProfile', () => {
  it('deletes only the site’s cookies, and clears its page data', async () => {
    const cdp = createFakeCdp({
      'Storage.getCookies': () => ({
        cookies: [
          {
            name: 'a',
            value: 'v',
            domain: '.github.com',
            path: '/',
            expires: -1,
            httpOnly: true,
            secure: true,
          },
          {
            name: 'b',
            value: 'v',
            domain: 'gitlab.com',
            path: '/',
            expires: -1,
            httpOnly: true,
            secure: true,
          },
        ],
      }),
      'Target.createTarget': () => ({ targetId: 'blank' }),
      'Target.attachToTarget': () => ({ sessionId: 'page' }),
    });
    const result = await forgetInProfile(cdp, { site: 'github.com' }, [
      'https://gist.github.com',
      'https://gitlab.com',
    ]);
    const deleted = cdp.calls.filter((c) => c.method === 'Network.deleteCookies');
    expect(deleted.map((c) => c.params.domain)).toEqual(['.github.com']);
    expect(deleted[0]!.sessionId).toBe('page');
    const cleared = cdp.calls
      .filter((c) => c.method === 'Storage.clearDataForOrigin')
      .map((c) => c.params.origin);
    expect(cleared.sort()).toEqual([
      'http://github.com',
      'https://gist.github.com',
      'https://github.com',
    ]);
    expect(result.cookies).toBe(1);
  });

  it('clears every cookie for --all', async () => {
    const cdp = createFakeCdp({ 'Storage.getCookies': () => ({ cookies: [] }) });
    await forgetInProfile(cdp, 'all', ['https://a.test']);
    expect(cdp.calls.map((c) => c.method)).toContain('Storage.clearCookies');
  });
});

describe('launchChromeWithPipe', () => {
  /** A child process whose fds 3/4 are in-memory streams. */
  function fakeChild() {
    const toChrome = new PassThrough();
    const fromChrome = new PassThrough();
    const child = Object.assign(new EventEmitter(), {
      pid: 99,
      stdio: [null, null, null, toChrome, fromChrome],
      kill: () => true,
    }) as unknown as ChildProcess;
    return { child, toChrome, fromChrome };
  }

  it('adds the pipe flag and frames messages with NUL, across chunk boundaries', async () => {
    const { child, toChrome, fromChrome } = fakeChild();
    let launchedWith: string[] = [];
    const cdp = launchChromeWithPipe('/chrome', ['--headless'], (_exe, args) => {
      launchedWith = args;
      return child;
    });
    expect(launchedWith).toEqual(['--remote-debugging-pipe', '--headless']);

    const sent: string[] = [];
    toChrome.on('data', (chunk: Buffer) => sent.push(chunk.toString()));
    const events: string[] = [];
    cdp.onEvent((event) => events.push(event.method));

    const reply = cdp.send<{ product: string }>('Browser.getVersion');
    await new Promise((resolve) => setImmediate(resolve));
    expect(sent.join('')).toBe(
      `${JSON.stringify({ id: 1, method: 'Browser.getVersion', params: {} })}\0`
    );

    const answer = `${JSON.stringify({ method: 'Target.targetCreated', params: {} })}\0${JSON.stringify({ id: 1, result: { product: 'Chrome/153' } })}\0`;
    fromChrome.write(answer.slice(0, 20));
    fromChrome.write(answer.slice(20));
    await expect(reply).resolves.toEqual({ product: 'Chrome/153' });
    expect(events).toEqual(['Target.targetCreated']);
  });

  it('turns a refusal into an error, and fails every waiting call when Chrome quits', async () => {
    const { child, fromChrome } = fakeChild();
    const cdp = launchChromeWithPipe('/chrome', [], () => child);
    const refused = cdp.send('Nope.method');
    fromChrome.write(`${JSON.stringify({ id: 1, error: { message: 'no such method' } })}\0`);
    await expect(refused).rejects.toThrow('no such method');

    const waiting = cdp.send('Storage.getCookies');
    child.emit('exit', 0, null);
    await expect(waiting).rejects.toBeInstanceOf(ChromeExitedError);
    await expect(cdp.exited).resolves.toEqual({ code: 0, signal: null });
    expect(cdp.hasExited()).toBe(true);
    await expect(cdp.send('Browser.getVersion')).rejects.toBeInstanceOf(ChromeExitedError);
  });

  it('forces a silent Chrome within one grace period, not two', async () => {
    const { child } = fakeChild();
    const signals: string[] = [];
    (child as unknown as { kill: (signal: string) => boolean }).kill = (signal: string) => {
      signals.push(signal);
      child.emit('exit', null, signal);
      return true;
    };
    vi.useFakeTimers();
    try {
      const cdp = launchChromeWithPipe('/chrome', [], () => child);
      const closed = cdp.close(100);
      await vi.advanceTimersByTimeAsync(100);
      expect(signals).toEqual(['SIGKILL']);
      await expect(closed).resolves.toEqual({ code: null, signal: 'SIGKILL' });
    } finally {
      vi.useRealTimers();
    }
  });
});
