/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellHomeRouteImport } from './routes/_shell._home'
import { Route as ShellAgentsRouteImport } from './routes/_shell.agents'
import { Route as ShellBrowserRouteImport } from './routes/_shell.browser'
import { Route as ShellChannelsRouteImport } from './routes/_shell.channels'
import { Route as ShellConnectionsRouteImport } from './routes/_shell.connections'
import { Route as ShellFeedbackRequestsRouteImport } from './routes/_shell.feedback-requests'
import { Route as ShellMarketplaceRouteImport } from './routes/_shell.marketplace'
import { Route as ShellSessionRouteImport } from './routes/_shell.session'
import { Route as ShellTeamRouteImport } from './routes/_shell.team'
import { Route as ShellHomeIndexRouteImport } from './routes/_shell._home.index'
import { Route as ShellHomeActivityRouteImport } from './routes/_shell._home.activity'
import { Route as ShellHomeTasksRouteImport } from './routes/_shell._home.tasks'
import { Route as ShellHomeWorkspacesRouteImport } from './routes/_shell._home.workspaces'
import { Route as ShellMarketplaceSourcesRouteImport } from './routes/_shell.marketplace_.sources'
import { Route as ShellXExtensionIdRouteImport } from './routes/_shell.x.$extensionId'
import { Route as ShellXExtensionIdSplatRouteImport } from './routes/_shell.x.$extensionId_.$'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/_home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBrowserRoute = ShellBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChannelsRoute = ShellChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConnectionsRoute = ShellConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFeedbackRequestsRoute = ShellFeedbackRequestsRouteImport.update({
  id: '/feedback-requests',
  path: '/feedback-requests',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMarketplaceRoute = ShellMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionRoute = ShellSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeamRoute = ShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeIndexRoute = ShellHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellHomeRoute,
} as any)
const ShellHomeActivityRoute = ShellHomeActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ShellHomeRoute,
} as any)
const ShellHomeTasksRoute = ShellHomeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellHomeRoute,
} as any)
const ShellHomeWorkspacesRoute = ShellHomeWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => ShellHomeRoute,
} as any)
const ShellMarketplaceSourcesRoute = ShellMarketplaceSourcesRouteImport.update({
  id: '/marketplace_/sources',
  path: '/marketplace/sources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellXExtensionIdRoute = ShellXExtensionIdRouteImport.update({
  id: '/x/$extensionId',
  path: '/x/$extensionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellXExtensionIdSplatRoute = ShellXExtensionIdSplatRouteImport.update({
  id: '/x/$extensionId_/$',
  path: '/x/$extensionId/$',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellHomeIndexRoute
  '/agents': typeof ShellAgentsRoute
  '/browser': typeof ShellBrowserRoute
  '/channels': typeof ShellChannelsRoute
  '/connections': typeof ShellConnectionsRoute
  '/feedback-requests': typeof ShellFeedbackRequestsRoute
  '/marketplace': typeof ShellMarketplaceRoute
  '/session': typeof ShellSessionRoute
  '/team': typeof ShellTeamRoute
  '/activity': typeof ShellHomeActivityRoute
  '/tasks': typeof ShellHomeTasksRoute
  '/workspaces': typeof ShellHomeWorkspacesRoute
  '/marketplace/sources': typeof ShellMarketplaceSourcesRoute
  '/x/$extensionId': typeof ShellXExtensionIdRoute
  '/x/$extensionId/$': typeof ShellXExtensionIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellHomeIndexRoute
  '/agents': typeof ShellAgentsRoute
  '/browser': typeof ShellBrowserRoute
  '/channels': typeof ShellChannelsRoute
  '/connections': typeof ShellConnectionsRoute
  '/feedback-requests': typeof ShellFeedbackRequestsRoute
  '/marketplace': typeof ShellMarketplaceRoute
  '/session': typeof ShellSessionRoute
  '/team': typeof ShellTeamRoute
  '/activity': typeof ShellHomeActivityRoute
  '/tasks': typeof ShellHomeTasksRoute
  '/workspaces': typeof ShellHomeWorkspacesRoute
  '/marketplace/sources': typeof ShellMarketplaceSourcesRoute
  '/x/$extensionId': typeof ShellXExtensionIdRoute
  '/x/$extensionId/$': typeof ShellXExtensionIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/_home': typeof ShellHomeRouteWithChildren
  '/_shell/agents': typeof ShellAgentsRoute
  '/_shell/browser': typeof ShellBrowserRoute
  '/_shell/channels': typeof ShellChannelsRoute
  '/_shell/connections': typeof ShellConnectionsRoute
  '/_shell/feedback-requests': typeof ShellFeedbackRequestsRoute
  '/_shell/marketplace': typeof ShellMarketplaceRoute
  '/_shell/session': typeof ShellSessionRoute
  '/_shell/team': typeof ShellTeamRoute
  '/_shell/_home/activity': typeof ShellHomeActivityRoute
  '/_shell/_home/tasks': typeof ShellHomeTasksRoute
  '/_shell/_home/workspaces': typeof ShellHomeWorkspacesRoute
  '/_shell/marketplace_/sources': typeof ShellMarketplaceSourcesRoute
  '/_shell/x/$extensionId': typeof ShellXExtensionIdRoute
  '/_shell/_home/': typeof ShellHomeIndexRoute
  '/_shell/x/$extensionId_/$': typeof ShellXExtensionIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/browser'
    | '/channels'
    | '/connections'
    | '/feedback-requests'
    | '/marketplace'
    | '/session'
    | '/team'
    | '/activity'
    | '/tasks'
    | '/workspaces'
    | '/marketplace/sources'
    | '/x/$extensionId'
    | '/x/$extensionId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/browser'
    | '/channels'
    | '/connections'
    | '/feedback-requests'
    | '/marketplace'
    | '/session'
    | '/team'
    | '/activity'
    | '/tasks'
    | '/workspaces'
    | '/marketplace/sources'
    | '/x/$extensionId'
    | '/x/$extensionId/$'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/_home'
    | '/_shell/agents'
    | '/_shell/browser'
    | '/_shell/channels'
    | '/_shell/connections'
    | '/_shell/feedback-requests'
    | '/_shell/marketplace'
    | '/_shell/session'
    | '/_shell/team'
    | '/_shell/_home/activity'
    | '/_shell/_home/tasks'
    | '/_shell/_home/workspaces'
    | '/_shell/marketplace_/sources'
    | '/_shell/x/$extensionId'
    | '/_shell/_home/'
    | '/_shell/x/$extensionId_/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_home': {
      id: '/_shell/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/browser': {
      id: '/_shell/browser'
      path: '/browser'
      fullPath: '/browser'
      preLoaderRoute: typeof ShellBrowserRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/channels': {
      id: '/_shell/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ShellChannelsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/connections': {
      id: '/_shell/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ShellConnectionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/feedback-requests': {
      id: '/_shell/feedback-requests'
      path: '/feedback-requests'
      fullPath: '/feedback-requests'
      preLoaderRoute: typeof ShellFeedbackRequestsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/marketplace': {
      id: '/_shell/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof ShellMarketplaceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/session': {
      id: '/_shell/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof ShellSessionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/team': {
      id: '/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ShellTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_home/': {
      id: '/_shell/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellHomeIndexRouteImport
      parentRoute: typeof ShellHomeRoute
    }
    '/_shell/_home/activity': {
      id: '/_shell/_home/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ShellHomeActivityRouteImport
      parentRoute: typeof ShellHomeRoute
    }
    '/_shell/_home/tasks': {
      id: '/_shell/_home/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellHomeTasksRouteImport
      parentRoute: typeof ShellHomeRoute
    }
    '/_shell/_home/workspaces': {
      id: '/_shell/_home/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof ShellHomeWorkspacesRouteImport
      parentRoute: typeof ShellHomeRoute
    }
    '/_shell/marketplace_/sources': {
      id: '/_shell/marketplace_/sources'
      path: '/marketplace/sources'
      fullPath: '/marketplace/sources'
      preLoaderRoute: typeof ShellMarketplaceSourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/x/$extensionId': {
      id: '/_shell/x/$extensionId'
      path: '/x/$extensionId'
      fullPath: '/x/$extensionId'
      preLoaderRoute: typeof ShellXExtensionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/x/$extensionId_/$': {
      id: '/_shell/x/$extensionId_/$'
      path: '/x/$extensionId/$'
      fullPath: '/x/$extensionId/$'
      preLoaderRoute: typeof ShellXExtensionIdSplatRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellHomeRouteChildren {
  ShellHomeActivityRoute: typeof ShellHomeActivityRoute
  ShellHomeTasksRoute: typeof ShellHomeTasksRoute
  ShellHomeWorkspacesRoute: typeof ShellHomeWorkspacesRoute
  ShellHomeIndexRoute: typeof ShellHomeIndexRoute
}

const ShellHomeRouteChildren: ShellHomeRouteChildren = {
  ShellHomeActivityRoute: ShellHomeActivityRoute,
  ShellHomeTasksRoute: ShellHomeTasksRoute,
  ShellHomeWorkspacesRoute: ShellHomeWorkspacesRoute,
  ShellHomeIndexRoute: ShellHomeIndexRoute,
}

const ShellHomeRouteWithChildren = ShellHomeRoute._addFileChildren(
  ShellHomeRouteChildren,
)

interface ShellRouteChildren {
  ShellHomeRoute: typeof ShellHomeRouteWithChildren
  ShellAgentsRoute: typeof ShellAgentsRoute
  ShellBrowserRoute: typeof ShellBrowserRoute
  ShellChannelsRoute: typeof ShellChannelsRoute
  ShellConnectionsRoute: typeof ShellConnectionsRoute
  ShellFeedbackRequestsRoute: typeof ShellFeedbackRequestsRoute
  ShellMarketplaceRoute: typeof ShellMarketplaceRoute
  ShellSessionRoute: typeof ShellSessionRoute
  ShellTeamRoute: typeof ShellTeamRoute
  ShellMarketplaceSourcesRoute: typeof ShellMarketplaceSourcesRoute
  ShellXExtensionIdRoute: typeof ShellXExtensionIdRoute
  ShellXExtensionIdSplatRoute: typeof ShellXExtensionIdSplatRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellHomeRoute: ShellHomeRouteWithChildren,
  ShellAgentsRoute: ShellAgentsRoute,
  ShellBrowserRoute: ShellBrowserRoute,
  ShellChannelsRoute: ShellChannelsRoute,
  ShellConnectionsRoute: ShellConnectionsRoute,
  ShellFeedbackRequestsRoute: ShellFeedbackRequestsRoute,
  ShellMarketplaceRoute: ShellMarketplaceRoute,
  ShellSessionRoute: ShellSessionRoute,
  ShellTeamRoute: ShellTeamRoute,
  ShellMarketplaceSourcesRoute: ShellMarketplaceSourcesRoute,
  ShellXExtensionIdRoute: ShellXExtensionIdRoute,
  ShellXExtensionIdSplatRoute: ShellXExtensionIdSplatRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
