/**
 * The cockpit's three notification cues, and the one function that plays them.
 *
 * Deliberately dumb: it plays the asset it is asked for and nothing else. Whether
 * a cue is WANTED is a preference question, and it is answered one layer up by
 * `features/notifications`'s `useNotificationCues`, which reads the person's
 * config. Putting the config read in here would make a `shared/lib` utility
 * depend on server state and make every caller mock a query to test a sound.
 *
 * The assets are generated by `apps/client/scripts/generate-notification-sound.ts`
 * — see that file for what each one is and why it sounds the way it does.
 *
 * @module shared/lib/notification-sound
 */

/** The three cues, and the file each one plays. */
const CUE_SOURCES = {
  /** An agent stopped and needs you. */
  knock: '/knock.wav',
  /** The last thing waiting on you has been answered. */
  settle: '/settle.wav',
  /** A turn finished. Off by default — see `notifications.sounds.turnEnd`. */
  'turn-end': '/notification.wav',
} as const;

/** Which cue to play. */
export type NotificationCue = keyof typeof CUE_SOURCES;

/**
 * One `Audio` element per cue, made on first use and kept.
 *
 * Kept because a fresh element per play re-fetches the asset and leaks a decoder
 * per call; per CUE rather than one shared element because two cues can land in
 * the same second (answering the last ask settles the queue) and resetting one
 * element's `currentTime` would cut the other off mid-sound.
 */
const players = new Map<NotificationCue, HTMLAudioElement>();

/**
 * Play one cue, if the browser will let us.
 *
 * Never throws and never reports. Autoplay policy rejects `play()` until the
 * person has interacted with the page, and a cue is a flourish about something
 * they can already see — a toast saying "your notification sound did not play"
 * would be worse than the silence.
 *
 * @param cue - Which of the three to play.
 */
export function playNotificationCue(cue: NotificationCue): void {
  try {
    let audio = players.get(cue);
    if (!audio) {
      audio = new Audio(CUE_SOURCES[cue]);
      players.set(cue, audio);
    }
    audio.currentTime = 0;
    audio.play().catch(() => {
      // Silently ignore autoplay rejection
    });
  } catch {
    // Silently ignore any errors
  }
}
