/** Private literal authoritySchema metadata; no authority operations. */
import type { RoomDocExpectedTable } from './room-doc-schema.js';
export const authoritySchema: Readonly<Record<string, RoomDocExpectedTable>> = {
  approvals: {
    columns: [
      ['id', 'TEXT', 1, 1, null],
      ['token_hash', 'TEXT', 1, 0, null],
      ['capability_id', 'TEXT', 1, 0, null],
      ['capability_title', 'TEXT', 1, 0, null],
      ['tier', 'TEXT', 1, 0, "'destructive'"],
      ['input_hash', 'TEXT', 1, 0, null],
      ['authority_binding_digest', 'TEXT', 0, 0, null],
      ['connector_owner_kind', 'TEXT', 0, 0, null],
      ['connector_owner_id', 'TEXT', 0, 0, null],
      ['connector_agent_id', 'TEXT', 0, 0, null],
      ['connector_session_id', 'TEXT', 0, 0, null],
      ['connector_connection_id', 'TEXT', 0, 0, null],
      ['connector_operation_revision_id', 'TEXT', 0, 0, null],
      ['summary', 'TEXT', 1, 0, null],
      ['detail', 'TEXT', 0, 0, null],
      ['subject_kind', 'TEXT', 0, 0, null],
      ['subject_id', 'TEXT', 0, 0, null],
      ['subject_label', 'TEXT', 0, 0, null],
      ['origin', 'TEXT', 0, 0, null],
      ['other_arguments', 'TEXT', 0, 0, null],
      ['service_action', 'TEXT', 0, 0, null],
      ['requested_by', 'TEXT', 0, 0, null],
      ['requested_by_path', 'TEXT', 0, 0, null],
      ['area', 'TEXT', 0, 0, null],
      ['blocked_request', 'INTEGER', 1, 0, 'False'],
      ['request_reason', 'TEXT', 0, 0, null],
      ['state', 'TEXT', 1, 0, "'pending'"],
      ['deny_reason', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['expires_at', 'TEXT', 1, 0, null],
      ['decided_at', 'TEXT', 0, 0, null],
      ['decided_by_user_id', 'TEXT', 0, 0, null],
      ['consumed_at', 'TEXT', 0, 0, null],
      ['requesting_session_id', 'TEXT', 0, 0, null],
      ['requesting_cwd', 'TEXT', 0, 0, null],
      ['notified_at', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [],
    checks: [],
    indices: [
      [
        'approvals_token_hash_unique',
        'CREATE UNIQUE INDEX approvals_token_hash_unique ON approvals (token_hash)',
      ],
      ['idx_approvals_state', 'CREATE INDEX idx_approvals_state ON approvals (state)'],
      [
        'idx_approvals_expires_at',
        'CREATE INDEX idx_approvals_expires_at ON approvals (expires_at)',
      ],
      [
        'idx_approvals_blocked_requester',
        'CREATE INDEX idx_approvals_blocked_requester ON approvals (requested_by_path,blocked_request,created_at)',
      ],
      [
        'approvals_connector_agent_connection_idx',
        'CREATE INDEX approvals_connector_agent_connection_idx ON approvals (connector_agent_id,connector_connection_id,consumed_at)',
      ],
    ],
  },
  connector_runtime_bindings: {
    columns: [
      ['id', 'TEXT', 1, 1, null],
      ['token_hash', 'TEXT', 1, 0, null],
      ['boot_epoch', 'TEXT', 1, 0, null],
      ['owner_kind', 'TEXT', 1, 0, null],
      ['owner_id', 'TEXT', 1, 0, null],
      ['runtime', 'TEXT', 1, 0, null],
      ['canonical_session_id', 'TEXT', 1, 0, null],
      ['agent_id', 'TEXT', 1, 0, null],
      ['agent_path', 'TEXT', 1, 0, null],
      ['canonical_cwd', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['expires_at', 'TEXT', 1, 0, null],
      ['revoked_at', 'TEXT', 0, 0, null],
      ['revoke_reason', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [],
    checks: [],
    indices: [
      [
        'connector_runtime_bindings_token_hash_unique',
        'CREATE UNIQUE INDEX connector_runtime_bindings_token_hash_unique ON connector_runtime_bindings (token_hash)',
      ],
      [
        'connector_runtime_bindings_agent_idx',
        'CREATE INDEX connector_runtime_bindings_agent_idx ON connector_runtime_bindings (agent_id,revoked_at)',
      ],
      [
        'connector_runtime_bindings_session_idx',
        'CREATE INDEX connector_runtime_bindings_session_idx ON connector_runtime_bindings (canonical_session_id,revoked_at)',
      ],
      [
        'connector_runtime_bindings_expiry_idx',
        'CREATE INDEX connector_runtime_bindings_expiry_idx ON connector_runtime_bindings (boot_epoch,revoked_at,expires_at)',
      ],
    ],
  },
};
