/** Private literal admissionSchema metadata; no authority operations. */
import type { RoomDocExpectedTable } from './room-doc-schema.js';
export const admissionSchema: Readonly<Record<string, RoomDocExpectedTable>> = {
  room_doc_admissions: {
    columns: [
      ['admission_id', 'TEXT', 1, 1, null],
      ['document_id', 'TEXT', 1, 0, null],
      ['batch_id', 'TEXT', 1, 0, null],
      ['generation', 'TEXT', 1, 0, null],
      ['source_attempt', 'INTEGER', 1, 0, null],
      ['room_id', 'TEXT', 1, 0, null],
      ['entry_id', 'TEXT', 1, 0, null],
      ['entry_seq', 'INTEGER', 1, 0, null],
      ['grant_id', 'TEXT', 1, 0, null],
      ['grant_revision', 'INTEGER', 1, 0, null],
      ['route_id', 'TEXT', 1, 0, null],
      ['route_hash', 'TEXT', 1, 0, null],
      ['declaration_hash', 'TEXT', 1, 0, null],
      ['manifest_hash', 'TEXT', 0, 0, null],
      ['input_fingerprint', 'TEXT', 1, 0, null],
      ['authority_digest', 'TEXT', 1, 0, null],
      ['effective_payload_digest', 'TEXT', 1, 0, null],
      ['source_hash', 'TEXT', 1, 0, null],
      ['producer_evidence_json', 'TEXT', 1, 0, null],
      ['target_agent_id', 'TEXT', 1, 0, null],
      ['target_author_id', 'TEXT', 1, 0, null],
      ['target_session_id', 'TEXT', 1, 0, null],
      ['target_runtime', 'TEXT', 1, 0, null],
      ['target_agent_path', 'TEXT', 1, 0, null],
      ['cascade_root', 'TEXT', 1, 0, null],
      ['root_room_id', 'TEXT', 1, 0, null],
      ['root_entry_id', 'TEXT', 1, 0, null],
      ['frozen_ceiling', 'INTEGER', 1, 0, null],
      ['dispatch_attempt', 'INTEGER', 1, 0, null],
      ['boot_epoch', 'TEXT', 1, 0, null],
      ['dispatch_id', 'TEXT', 1, 0, null],
      ['claimed_at_ms', 'INTEGER', 1, 0, null],
      ['claimed_at', 'TEXT', 1, 0, null],
      ['spend_row_id', 'INTEGER', 0, 0, null],
      ['status', 'TEXT', 1, 0, null],
      ['turn_id', 'TEXT', 0, 0, null],
      ['outcome', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['updated_at', 'TEXT', 1, 0, null],
      ['row_json', 'TEXT', 1, 0, null],
    ],
    foreignKeys: [
      [
        ['document_id', 'batch_id'],
        'canvas_doc_batches',
        ['document_id', 'batch_id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [
        ['document_id', 'grant_id'],
        'canvas_doc_grants',
        ['document_id', 'grant_id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [['room_id', 'entry_id'], 'room_entries', ['room_id', 'id'], 'NO ACTION', 'NO ACTION'],
      [
        ['root_room_id', 'root_entry_id'],
        'room_entries',
        ['room_id', 'id'],
        'NO ACTION',
        'NO ACTION',
      ],
    ],
    checks: [
      'source_attempt>=0',
      'entry_seq>0',
      'grant_revision>=0',
      'length(route_hash)=64',
      'length(declaration_hash)=64',
      'length(input_fingerprint)=64',
      'length(authority_digest)=64',
      'length(effective_payload_digest)=64',
      'length(source_hash)=64',
      'json_valid(producer_evidence_json)',
      "target_runtime IN ('claude-code','codex','opencode')",
      'frozen_ceiling>0',
      'dispatch_attempt=1',
      'spend_row_id IS NULL OR spend_row_id>0',
      "status IN ('claimed','turn_started','settled','in_doubt')",
      "outcome IS NULL OR outcome IN ('turn_done','failed','cancelled','in_doubt')",
      'json_valid(row_json)',
      'cascade_root=root_entry_id',
      "(status='claimed' AND turn_id IS NULL AND outcome IS NULL)\n  OR (status='turn_started' AND turn_id IS NOT NULL AND outcome IS NULL)\n  OR (status='in_doubt' AND outcome IS 'in_doubt')\n  OR (status='settled' AND outcome IS NOT NULL AND (outcome IN ('failed','cancelled')\n     OR (outcome='turn_done' AND turn_id IS NOT NULL)))",
      "json_extract(row_json,'$.admissionId') IS admission_id\n  AND json_extract(row_json,'$.entryId') IS entry_id\n  AND json_extract(row_json,'$.source.documentId') IS document_id\n  AND json_extract(row_json,'$.source.batchId') IS batch_id\n  AND json_extract(row_json,'$.source.generation') IS generation\n  AND json_extract(row_json,'$.sourceAttempt') IS source_attempt\n  AND json_extract(row_json,'$.sourceHash') IS source_hash\n  AND json_extract(row_json,'$.dispatchAttempt') IS dispatch_attempt\n  AND json_extract(row_json,'$.bootEpoch') IS boot_epoch\n  AND json_extract(row_json,'$.dispatchId') IS dispatch_id\n  AND json_extract(row_json,'$.claimedAtMs') IS claimed_at_ms\n  AND json_extract(row_json,'$.spendRowId') IS spend_row_id\n  AND json_extract(row_json,'$.status') IS status\n  AND json_extract(row_json,'$.turnId') IS turn_id\n  AND json_extract(row_json,'$.outcome') IS outcome\n  AND json_extract(row_json,'$.source.roomId') IS room_id\n  AND json_extract(row_json,'$.source.grantId') IS grant_id\n  AND json_extract(row_json,'$.source.grantRevision') IS grant_revision\n  AND json_extract(row_json,'$.source.routeId') IS route_id\n  AND json_extract(row_json,'$.source.routeHash') IS route_hash\n  AND json_extract(row_json,'$.source.declarationHash') IS declaration_hash\n  AND json_extract(row_json,'$.source.manifestHash') IS manifest_hash\n  AND json_extract(row_json,'$.source.inputFingerprint') IS input_fingerprint\n  AND json_extract(row_json,'$.source.authorityDigest') IS authority_digest\n  AND json_extract(row_json,'$.source.effectivePayloadDigest') IS effective_payload_digest\n  AND json_extract(row_json,'$.source.agentId') IS target_agent_id\n  AND json_extract(row_json,'$.source.authorId') IS target_author_id\n  AND json_extract(row_json,'$.source.sessionId') IS target_session_id\n  AND json_extract(row_json,'$.source.runtime') IS target_runtime\n  AND json_extract(row_json,'$.source.agentPath') IS target_agent_path\n  AND json_extract(row_json,'$.cascadeRoot') IS cascade_root\n  AND json_extract(row_json,'$.rootRoomId') IS root_room_id\n  AND json_extract(row_json,'$.rootEntryId') IS root_entry_id\n  AND json_extract(row_json,'$.ceiling') IS frozen_ceiling\n  AND json(json_extract(row_json,'$.producerEvidence')) IS json(producer_evidence_json)\n  AND json_extract(row_json,'$.createdAt') IS created_at\n  AND json_extract(row_json,'$.claimedAt') IS claimed_at\n  AND json_extract(row_json,'$.updatedAt') IS updated_at",
    ],
    indices: [
      [
        'room_doc_admissions_source_unique',
        'CREATE UNIQUE INDEX room_doc_admissions_source_unique ON room_doc_admissions (document_id,batch_id,generation)',
      ],
      [
        'room_doc_admissions_document_id_unique',
        'CREATE UNIQUE INDEX room_doc_admissions_document_id_unique ON room_doc_admissions (document_id,admission_id)',
      ],
      [
        'room_doc_admissions_entry_unique',
        'CREATE UNIQUE INDEX room_doc_admissions_entry_unique ON room_doc_admissions (room_id,entry_id)',
      ],
      [
        'room_doc_admissions_dispatch_unique',
        'CREATE UNIQUE INDEX room_doc_admissions_dispatch_unique ON room_doc_admissions (dispatch_id)',
      ],
      [
        'room_doc_admissions_document_window',
        'CREATE INDEX room_doc_admissions_document_window ON room_doc_admissions (document_id,claimed_at_ms)',
      ],
      [
        'room_doc_admissions_recovery',
        'CREATE INDEX room_doc_admissions_recovery ON room_doc_admissions (status,boot_epoch,updated_at,admission_id)',
      ],
      [
        'room_doc_admissions_root',
        'CREATE INDEX room_doc_admissions_root ON room_doc_admissions (cascade_root,status)',
      ],
    ],
  },
  room_doc_admission_inputs: {
    columns: [
      ['admission_id', 'TEXT', 1, 1, null],
      ['document_id', 'TEXT', 1, 0, null],
      ['event_id', 'TEXT', 1, 0, null],
      ['route_id', 'TEXT', 1, 0, null],
      ['input_ordinal', 'INTEGER', 1, 2, null],
      ['doc_seq', 'INTEGER', 1, 0, null],
      ['envelope_hash', 'TEXT', 1, 0, null],
      ['source_delivery_status', 'TEXT', 1, 0, null],
      ['source_delivery_reason', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [
      [
        ['document_id', 'admission_id'],
        'room_doc_admissions',
        ['document_id', 'admission_id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [
        ['document_id', 'event_id'],
        'canvas_doc_events',
        ['document_id', 'event_id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [
        ['document_id', 'event_id', 'route_id'],
        'canvas_doc_deliveries',
        ['document_id', 'event_id', 'route_id'],
        'NO ACTION',
        'NO ACTION',
      ],
    ],
    checks: ['input_ordinal>=0 AND input_ordinal<100', 'doc_seq>0', 'length(envelope_hash)=64'],
    indices: [
      [
        'room_doc_admission_inputs_event_unique',
        'CREATE UNIQUE INDEX room_doc_admission_inputs_event_unique ON room_doc_admission_inputs (admission_id,event_id)',
      ],
      [
        'room_doc_admission_inputs_route_unique',
        'CREATE UNIQUE INDEX room_doc_admission_inputs_route_unique ON room_doc_admission_inputs (document_id,event_id,route_id)',
      ],
    ],
  },
  room_doc_exhausted_lineages: {
    columns: [
      ['cascade_root', 'TEXT', 1, 1, null],
      ['root_room_id', 'TEXT', 1, 0, null],
      ['root_entry_id', 'TEXT', 1, 0, null],
      ['original_admission_id', 'TEXT', 1, 0, null],
      ['frozen_ceiling', 'INTEGER', 1, 0, null],
      ['exhausted_at', 'TEXT', 1, 0, null],
    ],
    foreignKeys: [
      [
        ['root_room_id', 'root_entry_id'],
        'room_entries',
        ['room_id', 'id'],
        'NO ACTION',
        'NO ACTION',
      ],
    ],
    checks: ['frozen_ceiling>0', 'cascade_root=root_entry_id'],
    indices: [
      [
        'room_doc_exhausted_lineages_anchor',
        'CREATE INDEX room_doc_exhausted_lineages_anchor ON room_doc_exhausted_lineages (root_room_id,root_entry_id)',
      ],
    ],
  },
};
