/** Private literal schema metadata. Captured 3839 plus reviewed native request. */
import type { RoomDocExpectedTable } from './room-doc-schema.js';
export const sourceSchema: Readonly<Record<string, RoomDocExpectedTable>> = {
  canvas_doc_room_pending_sources: {
    columns: [
      ['document_id', 'TEXT', 1, 1, null],
      ['batch_id', 'TEXT', 1, 2, null],
      ['generation', 'TEXT', 1, 3, null],
      ['source_json', 'TEXT', 1, 0, null],
      ['source_hash', 'TEXT', 1, 0, null],
      ['due_at', 'TEXT', 1, 0, null],
      ['updated_at', 'TEXT', 1, 0, null],
    ],
    foreignKeys: [[['batch_id'], 'canvas_doc_batches', ['batch_id'], 'NO ACTION', 'CASCADE']],
    checks: [],
    indices: [],
  },
  canvas_doc_channels: {
    columns: [
      ['document_id', 'TEXT', 1, 1, null],
      ['scope', 'TEXT', 1, 0, null],
      ['next_doc_seq', 'INTEGER', 1, 0, '1'],
      ['state', 'TEXT', 1, 0, "'{}'"],
      ['state_rev', 'INTEGER', 1, 0, '0'],
      ['retention_floor', 'INTEGER', 1, 0, '1'],
      ['receipt_retention_floor', 'INTEGER', 1, 0, '1'],
      ['declaration', 'TEXT', 0, 0, null],
      ['declaration_hash', 'TEXT', 0, 0, null],
      ['opener_agent_id', 'TEXT', 0, 0, null],
      ['manifest_hash', 'TEXT', 0, 0, null],
      ['closed_at', 'TEXT', 0, 0, null],
      ['closure_evidence', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['updated_at', 'TEXT', 1, 0, null],
      ['room_spend_floor_ms', 'INTEGER', 0, 0, null],
    ],
    foreignKeys: [],
    checks: [],
    indices: [
      [
        'canvas_doc_channels_scope_idx',
        'CREATE INDEX canvas_doc_channels_scope_idx ON canvas_doc_channels (scope,closed_at)',
      ],
    ],
  },
  canvas_doc_grants: {
    columns: [
      ['grant_id', 'TEXT', 1, 1, null],
      ['document_id', 'TEXT', 1, 0, null],
      ['route_id', 'TEXT', 1, 0, null],
      ['revision', 'INTEGER', 1, 0, '1'],
      ['opener_agent_id', 'TEXT', 0, 0, null],
      ['target_agent_id', 'TEXT', 0, 0, null],
      ['target_session_id', 'TEXT', 0, 0, null],
      ['target_runtime', 'TEXT', 0, 0, null],
      ['normalized_route', 'TEXT', 1, 0, null],
      ['route_hash', 'TEXT', 1, 0, null],
      ['declaration_hash', 'TEXT', 1, 0, null],
      ['manifest_hash', 'TEXT', 0, 0, null],
      ['approved_by', 'TEXT', 1, 0, null],
      ['approval_id', 'TEXT', 0, 0, null],
      ['approval_evidence', 'TEXT', 1, 0, null],
      ['limits', 'TEXT', 1, 0, null],
      ['allowed_types', 'TEXT', 1, 0, null],
      ['write_operation', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['expires_at', 'TEXT', 0, 0, null],
      ['revoked_at', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [
      [['document_id'], 'canvas_doc_channels', ['document_id'], 'NO ACTION', 'NO ACTION'],
    ],
    checks: [],
    indices: [
      [
        'canvas_doc_grants_document_id_unique',
        'CREATE UNIQUE INDEX canvas_doc_grants_document_id_unique ON canvas_doc_grants (document_id,grant_id)',
      ],
      [
        'canvas_doc_grants_route_idx',
        'CREATE INDEX canvas_doc_grants_route_idx ON canvas_doc_grants (document_id,route_id,revoked_at)',
      ],
    ],
  },
  canvas_doc_batches: {
    columns: [
      ['batch_id', 'TEXT', 1, 1, null],
      ['document_id', 'TEXT', 1, 0, null],
      ['scope', 'TEXT', 1, 0, null],
      ['route_id', 'TEXT', 1, 0, null],
      ['grant_id', 'TEXT', 1, 0, null],
      ['grant_revision', 'INTEGER', 1, 0, null],
      ['generation', 'TEXT', 1, 0, null],
      ['input_event_ids', 'TEXT', 1, 0, null],
      ['effective_payload', 'TEXT', 1, 0, null],
      ['due_at', 'TEXT', 1, 0, null],
      ['status', 'TEXT', 1, 0, null],
      ['attempt', 'INTEGER', 1, 0, '0'],
      ['lease_until', 'TEXT', 0, 0, null],
      ['waiting_warning_at', 'TEXT', 0, 0, 'NULL'],
      ['relay_message_id', 'TEXT', 0, 0, null],
      ['turn_id', 'TEXT', 0, 0, null],
      ['admission_receipt_id', 'TEXT', 0, 0, null],
      ['error_code', 'TEXT', 0, 0, null],
      ['created_at', 'TEXT', 1, 0, null],
      ['updated_at', 'TEXT', 1, 0, null],
      ['delivery_kind', 'TEXT', 0, 0, null],
      ['room_admission_id', 'TEXT', 0, 0, null],
      ['room_source_attempt', 'INTEGER', 0, 0, null],
      ['room_source_json', 'TEXT', 0, 0, null],
      ['room_source_hash', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [
      [['document_id'], 'canvas_doc_channels', ['document_id'], 'NO ACTION', 'NO ACTION'],
      [
        ['admission_receipt_id'],
        'session_message_acceptance_receipts',
        ['id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [
        ['document_id', 'grant_id'],
        'canvas_doc_grants',
        ['document_id', 'grant_id'],
        'NO ACTION',
        'NO ACTION',
      ],
    ],
    checks: [
      "delivery_kind IS NULL OR delivery_kind IN ('private_session','room_app_event')",
      "\n (delivery_kind IS NOT 'room_app_event' AND room_admission_id IS NULL\n  AND room_source_attempt IS NULL AND room_source_json IS NULL AND room_source_hash IS NULL)\n OR\n (delivery_kind IS 'room_app_event' AND admission_receipt_id IS NULL\n  AND room_admission_id IS NOT NULL AND length(room_admission_id)>0\n  AND room_source_attempt IS NOT NULL AND room_source_attempt>=0\n  AND room_source_json IS NOT NULL AND json_valid(room_source_json)\n  AND room_source_hash IS NOT NULL AND length(room_source_hash)=64\n  AND room_source_hash NOT GLOB '*[^0-9a-f]*'\n  AND json_extract(room_source_json,'$.admissionId') IS room_admission_id\n  AND json_extract(room_source_json,'$.documentId') IS document_id\n  AND json_extract(room_source_json,'$.batchId') IS batch_id\n  AND json_extract(room_source_json,'$.generation') IS generation\n  AND json_extract(room_source_json,'$.sourceAttempt') IS room_source_attempt)",
    ],
    indices: [
      [
        'canvas_doc_batches_document_id_unique',
        'CREATE UNIQUE INDEX canvas_doc_batches_document_id_unique ON canvas_doc_batches (document_id,batch_id)',
      ],
      [
        'canvas_doc_batches_pending_unique',
        "CREATE UNIQUE INDEX canvas_doc_batches_pending_unique ON canvas_doc_batches (document_id,route_id) WHERE \"status\" in ('pending', 'waiting')",
      ],
      [
        'canvas_doc_batches_active_unique',
        "CREATE UNIQUE INDEX canvas_doc_batches_active_unique ON canvas_doc_batches (document_id,route_id) WHERE \"status\" in ('accepted', 'dispatching', 'turn_started', 'in_doubt') AND (delivery_kind IS NOT 'room_app_event' OR status IS NOT 'accepted')",
      ],
      [
        'canvas_doc_batches_due_idx',
        'CREATE INDEX canvas_doc_batches_due_idx ON canvas_doc_batches (status,due_at)',
      ],
      [
        'canvas_doc_batches_lease_idx',
        'CREATE INDEX canvas_doc_batches_lease_idx ON canvas_doc_batches (status,lease_until)',
      ],
      [
        'canvas_doc_batches_receipt_idx',
        'CREATE INDEX canvas_doc_batches_receipt_idx ON canvas_doc_batches (admission_receipt_id)',
      ],
      [
        'canvas_doc_batches_room_admission_unique',
        'CREATE UNIQUE INDEX canvas_doc_batches_room_admission_unique ON canvas_doc_batches (room_admission_id) WHERE room_admission_id IS NOT NULL',
      ],
      [
        'canvas_doc_batches_room_resume',
        'CREATE INDEX canvas_doc_batches_room_resume ON canvas_doc_batches (delivery_kind,status,updated_at,batch_id)',
      ],
    ],
  },
  canvas_doc_events: {
    columns: [
      ['document_id', 'TEXT', 1, 1, null],
      ['event_id', 'TEXT', 1, 2, null],
      ['doc_seq', 'INTEGER', 1, 0, null],
      ['direction', 'TEXT', 1, 0, null],
      ['type', 'TEXT', 1, 0, null],
      ['payload', 'TEXT', 1, 0, null],
      ['envelope_hash', 'TEXT', 1, 0, null],
      ['envelope_bytes', 'INTEGER', 1, 0, '0'],
      ['payload_pruned_at', 'TEXT', 0, 0, null],
      ['coalesce_key', 'TEXT', 0, 0, null],
      ['client_ts', 'TEXT', 0, 0, null],
      ['received_at', 'TEXT', 1, 0, null],
      ['provenance', 'TEXT', 1, 0, null],
    ],
    foreignKeys: [
      [['document_id'], 'canvas_doc_channels', ['document_id'], 'NO ACTION', 'NO ACTION'],
    ],
    checks: [],
    indices: [
      [
        'canvas_doc_events_sequence_unique',
        'CREATE UNIQUE INDEX canvas_doc_events_sequence_unique ON canvas_doc_events (document_id,doc_seq)',
      ],
      [
        'canvas_doc_events_received_idx',
        'CREATE INDEX canvas_doc_events_received_idx ON canvas_doc_events (document_id,received_at)',
      ],
      [
        'canvas_doc_events_retention_idx',
        'CREATE INDEX canvas_doc_events_retention_idx ON canvas_doc_events (received_at,document_id,doc_seq)',
      ],
      [
        'canvas_doc_events_unaccounted_idx',
        'CREATE INDEX canvas_doc_events_unaccounted_idx ON canvas_doc_events (document_id,event_id) WHERE "canvas_doc_events"."envelope_bytes"=0 AND "canvas_doc_events"."payload_pruned_at" IS NULL',
      ],
    ],
  },
  canvas_doc_deliveries: {
    columns: [
      ['document_id', 'TEXT', 1, 1, null],
      ['event_id', 'TEXT', 1, 2, null],
      ['route_id', 'TEXT', 1, 3, null],
      ['batch_id', 'TEXT', 0, 0, null],
      ['status', 'TEXT', 1, 0, null],
      ['turn_id', 'TEXT', 0, 0, null],
      ['reason', 'TEXT', 0, 0, null],
      ['ack_outcome', 'TEXT', 0, 0, null],
      ['acknowledged_at', 'TEXT', 0, 0, null],
      ['acknowledged_by', 'TEXT', 0, 0, null],
      ['ack_evidence', 'TEXT', 0, 0, null],
      ['updated_at', 'TEXT', 1, 0, null],
      ['delivery_kind', 'TEXT', 0, 0, null],
      ['room_admission_id', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [
      [
        ['document_id', 'event_id'],
        'canvas_doc_events',
        ['document_id', 'event_id'],
        'NO ACTION',
        'NO ACTION',
      ],
      [
        ['document_id', 'batch_id'],
        'canvas_doc_batches',
        ['document_id', 'batch_id'],
        'NO ACTION',
        'NO ACTION',
      ],
    ],
    checks: [
      "delivery_kind IS NULL OR delivery_kind IN ('private_session','room_app_event')",
      "\n (delivery_kind IS NOT 'room_app_event' AND room_admission_id IS NULL)\n OR (delivery_kind IS 'room_app_event' AND room_admission_id IS NOT NULL\n     AND length(room_admission_id)>0)",
    ],
    indices: [
      [
        'canvas_doc_deliveries_batch_idx',
        'CREATE INDEX canvas_doc_deliveries_batch_idx ON canvas_doc_deliveries (document_id,batch_id)',
      ],
      [
        'canvas_doc_deliveries_status_idx',
        'CREATE INDEX canvas_doc_deliveries_status_idx ON canvas_doc_deliveries (status,updated_at)',
      ],
      [
        'canvas_doc_deliveries_room_admission',
        'CREATE INDEX canvas_doc_deliveries_room_admission ON canvas_doc_deliveries (room_admission_id,document_id,route_id)',
      ],
    ],
  },
  canvas_documents: {
    columns: [
      ['id', 'TEXT', 1, 1, null],
      ['scope', 'TEXT', 1, 0, null],
      ['room_id', 'TEXT', 0, 0, null],
      ['content', 'TEXT', 1, 0, null],
      ['title', 'TEXT', 1, 0, null],
      ['content_type', 'TEXT', 1, 0, null],
      ['author_id', 'TEXT', 1, 0, null],
      ['source_key', 'TEXT', 0, 0, null],
      ['source_label', 'TEXT', 0, 0, null],
      ['resolved_cwd', 'TEXT', 0, 0, null],
      ['tree_kind', 'TEXT', 0, 0, null],
      ['ahead_of_main', 'INTEGER', 0, 0, null],
      ['pinned', 'INTEGER', 1, 0, 'False'],
      ['rev', 'INTEGER', 1, 0, null],
      ['last_touched_by', 'TEXT', 1, 0, null],
      ['last_touched_at', 'TEXT', 1, 0, null],
      ['editing_by', 'TEXT', 0, 0, null],
      ['editing_heartbeat_at', 'TEXT', 0, 0, null],
      ['opened_at', 'TEXT', 1, 0, null],
      ['last_active_at', 'TEXT', 1, 0, null],
      ['thread_root_entry_id', 'TEXT', 0, 0, null],
    ],
    foreignKeys: [[['room_id'], 'rooms', ['id'], 'NO ACTION', 'CASCADE']],
    checks: [],
    indices: [
      [
        'idx_canvas_documents_scope',
        'CREATE INDEX idx_canvas_documents_scope ON canvas_documents (scope,last_active_at)',
      ],
      [
        'canvas_documents_source_unique',
        'CREATE UNIQUE INDEX canvas_documents_source_unique ON canvas_documents (scope,source_key)',
      ],
      [
        'idx_canvas_documents_scope_type',
        'CREATE INDEX idx_canvas_documents_scope_type ON canvas_documents (scope,content_type)',
      ],
      [
        'idx_canvas_documents_last_touched',
        'CREATE INDEX idx_canvas_documents_last_touched ON canvas_documents (scope,last_touched_by,last_touched_at)',
      ],
    ],
  },
};
