/**
 * The agent browser's Chrome profile: creating it, giving it a look nobody
 * mistakes for their everyday browser, and telling whether it is open.
 *
 * ## The theme, and how it was verified
 *
 * The keys below were found by experiment on Chrome 153.0.8010.52, not
 * guessed: written into a fresh profile's `Default/Preferences` and
 * `Local State` before Chrome first started, read back from
 * `chrome://prefs-internals` while it ran, checked again in the files after it
 * quit, and screenshotted. Chrome 153 migrates `user_color` to `user_color2`
 * (and the same for the variant and greyscale keys) on its own; both are
 * written so an older or newer Chrome finds whichever it reads.
 * `autogenerated.theme.color` is the pre-2023 key, kept for older Chrome.
 *
 * `color_scheme2: 1` forces the light frame. With the system's dark mode the
 * same seed colour renders a dark brown frame that reads as "normal Chrome";
 * light makes it a bright orange one, which is the point.
 *
 * The theme is applied ONCE per profile (a marker file records it), so a
 * colour the person later picks in Chrome is never overwritten, and a profile
 * that already carries a colour of its own is left alone.
 *
 * @module lib/agent-browser/profile
 */
import fs from 'node:fs';
import path from 'node:path';
import { isProcessAlive } from '@dorkos/shared/process-liveness';

/** The name Chrome shows for the agent browser's profile. */
export const AGENT_BROWSER_PROFILE_NAME = 'DorkOS agent browser';

/** The theme seed colour, as the signed 32-bit ARGB integer Chrome stores (opaque #FF6B00). */
export const AGENT_BROWSER_THEME_COLOR = 0xffff6b00 | 0;

/** Chrome's "vibrant" colour variant (`ui::mojom::BrowserColorVariant::kVibrant`). */
const COLOR_VARIANT_VIBRANT = 3;

/** Chrome's forced light colour scheme (`ThemeService::BrowserColorScheme::kLight`). */
const COLOR_SCHEME_LIGHT = 1;

/** The marker file, inside the profile folder, recording that the theme was applied. */
export const THEME_MARKER_FILE = '.dorkos-agent-browser.json';

/** A JSON object read from one of Chrome's preference files. */
type JsonObject = Record<string, unknown>;

/** The `Default/Preferences` keys that give the profile its theme and name. */
function themePreferences(): JsonObject {
  const color = AGENT_BROWSER_THEME_COLOR;
  return {
    browser: {
      theme: {
        user_color: color,
        user_color2: color,
        color_variant: COLOR_VARIANT_VIBRANT,
        color_variant2: COLOR_VARIANT_VIBRANT,
        color_scheme2: COLOR_SCHEME_LIGHT,
        is_grayscale: false,
        is_grayscale2: false,
      },
    },
    autogenerated: { theme: { color } },
    profile: { name: AGENT_BROWSER_PROFILE_NAME },
  };
}

/** The `Local State` keys that name the profile in Chrome's profile menu. */
function localStateProfileInfo(): JsonObject {
  return {
    profile: {
      info_cache: {
        Default: {
          name: AGENT_BROWSER_PROFILE_NAME,
          is_using_default_name: false,
          profile_color_seed: AGENT_BROWSER_THEME_COLOR,
        },
      },
    },
  };
}

function isObject(value: unknown): value is JsonObject {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Merge `patch` into `base`, recursing into objects; `patch` wins on conflicts. */
function deepMerge(base: JsonObject, patch: JsonObject): JsonObject {
  const out: JsonObject = { ...base };
  for (const [key, value] of Object.entries(patch)) {
    out[key] = isObject(value) && isObject(out[key]) ? deepMerge(out[key], value) : value;
  }
  return out;
}

/** Read a JSON object file, or `{}` when it is missing or not an object. */
function readJsonObject(file: string): JsonObject {
  try {
    const parsed: unknown = JSON.parse(fs.readFileSync(file, 'utf8'));
    return isObject(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

/** Whether a `Default/Preferences` object already carries a theme colour of its own. */
function hasOwnThemeColor(prefs: JsonObject): boolean {
  const theme = isObject(prefs.browser) ? prefs.browser.theme : undefined;
  if (isObject(theme) && (theme.user_color !== undefined || theme.user_color2 !== undefined)) {
    return true;
  }
  const extensions = isObject(prefs.extensions) ? prefs.extensions.theme : undefined;
  return isObject(extensions) && typeof extensions.id === 'string' && extensions.id !== '';
}

/** What {@link ensureAgentProfile} did. */
export interface EnsureProfileResult {
  /** The profile folder did not exist and was made now. */
  created: boolean;
  /** The theme was written now (first use, or a profile that never had one). */
  themed: boolean;
}

/**
 * Make sure the agent browser's profile exists, and give it its look the
 * first time. Call it only while the profile is NOT open: Chrome rewrites its
 * preference files as it quits, so an edit made underneath a running Chrome is
 * lost.
 *
 * @param profileDir - The profile folder (`<dorkHome>/browser/profile`).
 * @param now - Clock seam for the marker's timestamp.
 */
export function ensureAgentProfile(
  profileDir: string,
  now: Date = new Date()
): EnsureProfileResult {
  const created = !fs.existsSync(profileDir);
  fs.mkdirSync(path.dirname(profileDir), { recursive: true, mode: 0o700 });
  fs.chmodSync(path.dirname(profileDir), 0o700);
  fs.mkdirSync(profileDir, { recursive: true, mode: 0o700 });

  const marker = path.join(profileDir, THEME_MARKER_FILE);
  if (fs.existsSync(marker)) return { created, themed: false };

  const prefsFile = path.join(profileDir, 'Default', 'Preferences');
  const prefs = readJsonObject(prefsFile);
  const themed = !hasOwnThemeColor(prefs);
  if (themed) {
    fs.mkdirSync(path.dirname(prefsFile), { recursive: true, mode: 0o700 });
    fs.writeFileSync(prefsFile, JSON.stringify(deepMerge(prefs, themePreferences())));
    const localStateFile = path.join(profileDir, 'Local State');
    const localState = readJsonObject(localStateFile);
    fs.writeFileSync(
      localStateFile,
      JSON.stringify(deepMerge(localState, localStateProfileInfo()))
    );
  }
  fs.writeFileSync(
    marker,
    `${JSON.stringify({ themeAppliedAt: now.toISOString(), themed }, null, 2)}\n`
  );
  return { created, themed };
}

/** Whether a Chrome is using the profile right now, and which process holds it. */
export interface ProfileLock {
  inUse: boolean;
  pid?: number;
}

/**
 * Whether a Chrome is running on this profile.
 *
 * Chrome marks a profile it holds with `SingletonLock`, a symlink whose target
 * is `<hostname>-<pid>` on macOS and Linux. A leftover link from a crash names a
 * dead pid, which reads as not in use. Windows uses a `lockfile` that Chrome
 * keeps open, so there the test is whether the file can be removed.
 *
 * @param profileDir - The profile folder.
 * @param platform - Test seam for `process.platform`.
 */
export function profileLock(
  profileDir: string,
  platform: NodeJS.Platform = process.platform
): ProfileLock {
  if (platform === 'win32') {
    const lockfile = path.join(profileDir, 'lockfile');
    if (!fs.existsSync(lockfile)) return { inUse: false };
    try {
      fs.rmSync(lockfile);
      return { inUse: false };
    } catch {
      return { inUse: true };
    }
  }
  let target: string;
  try {
    target = fs.readlinkSync(path.join(profileDir, 'SingletonLock'));
  } catch {
    return { inUse: false };
  }
  const pid = Number(target.slice(target.lastIndexOf('-') + 1));
  if (!Number.isInteger(pid) || pid <= 0) return { inUse: false };
  return isProcessAlive(pid) ? { inUse: true, pid } : { inUse: false };
}
