import { randomUUID } from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { SSEClientTransport } from '@modelcontextprotocol/sdk/client/sse.js';
/** Turn-owned MCP connections. Only the authenticated host route receives bare names. */
import {
  McpConnection,
  boundedMcpFetch,
  mcpAlias,
  type ToolDescriptor,
  type JsonValue,
  type ToolRegistry,
  type McpTransportConfig,
} from '@dorkos/doe';
import type { McpServerEntry } from '@dorkos/shared/transport';
import type { McpAppServerConnection } from '@dorkos/shared/agent-runtime';
import {
  CONNECTOR_RUNTIME_TOOL_TIMEOUT_MS,
  type ConnectorRuntimeMcpInjection,
} from '../connector-tools.js';
import { resolveDorkosMcpInjection } from '../shared/dorkos-mcp-injection.js';
import { alwaysLoadedToolsFor, searchHintFrom } from '../shared/tools/tool-exposure-policy.js';

/** Inputs bound to one authenticated runtime turn; configured servers remain foreign. */
export interface DoeMcpOptions {
  agentPath?: string;
  connectorInjection?: ConnectorRuntimeMcpInjection | null;
  servers?: Record<string, McpAppServerConnection>;
  signal: AbortSignal;
  agentToAgent?: boolean;
}
/** Owned discoveries, exact callable names and explicit connection shutdown. */
export interface DoeMcpAssembly {
  tools: readonly ToolDescriptor[];
  names: ReadonlyMap<string, string>;
  hostConnected: boolean;
  trustedHostToolNames: ReadonlySet<string>;
  statuses: readonly McpServerEntry[];
  serverConfigs: Readonly<Record<string, McpAppServerConnection>>;
  dispose(): Promise<void>;
}
/** Convert explicit managed configuration without importing ambient environment. */
export function doeMcpTransport(server: McpAppServerConnection): McpTransportConfig {
  if (server.transport === 'sse') throw new Error('Legacy SSE MCP transport is unsupported');
  return server.transport === 'stdio'
    ? { kind: 'stdio', command: server.command, args: server.args, environment: { ...server.env } }
    : { kind: 'http', url: server.url, headers: { ...server.headers } };
}
/** Discover fresh caller-filtered registry projections, retaining the MCP execution closures. */
export async function assembleDoeMcp(options: DoeMcpOptions): Promise<DoeMcpAssembly> {
  if (Object.keys(options.servers ?? {}).length > 32)
    throw new Error('Too many managed MCP servers');
  const deadline = AbortSignal.timeout(15000);
  const signal = AbortSignal.any([options.signal, deadline]);
  const connections: Array<{ close(): Promise<void> }> = [];
  const tools: ToolDescriptor[] = [];
  const names = new Map<string, string>();
  const trustedHostToolNames = new Set<string>();
  const statuses: McpServerEntry[] = [];
  let disposal: Promise<void> | undefined;
  const dispose = () =>
    (disposal ??= (async () => {
      statuses.forEach((entry) => {
        entry.status = 'pending';
      });
      await Promise.all(
        connections.map(async (connection) => {
          let timer: ReturnType<typeof setTimeout> | undefined;
          try {
            await Promise.race([
              connection.close(),
              new Promise<never>((_, reject) => {
                timer = setTimeout(() => reject(new Error('MCP shutdown timed out')), 1000);
              }),
            ]);
          } finally {
            clearTimeout(timer);
          }
        })
      );
    })());
  const load = async (
    id: string,
    config: McpTransportConfig | Extract<McpAppServerConnection, { transport: 'sse' }>,
    host = false
  ) => {
    const connection =
      'transport' in config
        ? new DoeSseConnection(id, config)
        : new McpConnection(id, config, {
            connectTimeoutMs: 5000,
            callTimeoutMs:
              host || id === 'dorkos_connections' ? CONNECTOR_RUNTIME_TOOL_TIMEOUT_MS : 10000,
            maxTools: 10000,
            maxMessageBytes: 16777216,
            maxDiscoveryBytes: 33554432,
          });
    connections.push(connection);
    await connection.connect(signal);
    const collector: ToolRegistry = {
      register(tool) {
        // The suffix hash is generated by the engine from the raw protocol name.
        // Recover names from the registry projection's search hint, not by stripping hashes.
        const bare = tool.searchHint?.slice(id.length + 1);
        if (!bare) throw new Error('MCP discovery omitted its registered name');
        const name = host ? bare : tool.name;
        names.set(`${id}:${bare}`, name);
        if (host || id === 'dorkos_connections') trustedHostToolNames.add(name);
        tools.push({
          ...tool,
          name,
          execute: (args, context) =>
            tool.execute(args, {
              ...context,
              signal: AbortSignal.any([options.signal, context.signal]),
              emit: (event) =>
                context.emit(
                  event.type === 'tool-progress' && event.name === tool.name
                    ? { ...event, name }
                    : event
                ),
            }),
          ...(host
            ? {
                initialLoad: alwaysLoadedToolsFor(options.agentToAgent ?? false).has(bare),
                searchHint: searchHintFrom(tool.description),
              }
            : {}),
        });
      },
      selected: () => [],
      search: () => [],
      execute: async () => {
        throw new Error('Discovery cannot execute tools');
      },
    };
    try {
      await connection.registerTools(collector, signal);
    } catch (error) {
      // A configured MCP server can expose only resources/prompts and have no tools/list method.
      if (
        !id.startsWith('managed:') ||
        !error ||
        typeof error !== 'object' ||
        !('code' in error) ||
        error.code !== -32601
      )
        throw error;
    }
  };
  try {
    const injection = await resolveDorkosMcpInjection(
      options.agentPath,
      options.connectorInjection
    );
    if (injection) {
      await load('dorkos', { kind: 'http', ...injection }, true);
      statuses.push({ name: 'dorkos', type: 'http', scope: 'runtime', status: 'connected' });
      if (options.connectorInjection)
        await load('dorkos_connections', {
          kind: 'http',
          url: options.connectorInjection.url,
          headers: options.connectorInjection.headers,
        });
    }
    for (const [name, config] of Object.entries(options.servers ?? {})) {
      // A configured server called dorkos remains foreign and cannot gain host names.
      await load(`managed:${name}`, config.transport === 'sse' ? config : doeMcpTransport(config));
      statuses.push({ name, type: config.transport, scope: 'managed', status: 'connected' });
    }
    options.signal.throwIfAborted();
    return {
      tools,
      names,
      hostConnected: !!injection,
      dispose,
      trustedHostToolNames,
      statuses,
      serverConfigs: { ...options.servers },
    };
  } catch (error) {
    await dispose().catch(() => {});
    throw error;
  }
}
/** Exact alias for one privately routed connection tool. */
export function connectionToolName(bare: string): string {
  return mcpAlias('dorkos_connections', bare);
}

/** Legacy managed-server transport bridge; the engine registry and execution loop stay shared. */
class DoeSseConnection {
  private readonly client = new Client({ name: 'dorkos-doe', version: '1.0.0' });
  private readonly transport: SSEClientTransport;
  private closing?: Promise<void>;
  /** Bind explicit headers to this server origin; refuse redirects and oversized streams. */
  constructor(
    private readonly server: string,
    config: Extract<McpAppServerConnection, { transport: 'sse' }>
  ) {
    const endpoint = new URL(config.url);
    if (!['http:', 'https:'].includes(endpoint.protocol) || endpoint.username || endpoint.password)
      throw new Error('Invalid MCP endpoint');
    this.transport = new SSEClientTransport(endpoint, {
      requestInit: { headers: { ...config.headers } },
      fetch: async (input, init) => {
        const url = new URL(typeof input === 'string' ? input : input.href);
        if (url.origin !== endpoint.origin) throw new Error('MCP endpoint origin changed');
        return boundedMcpFetch(url.href, 16777216)(input, init);
      },
    });
  }
  /** The SDK transport start lacks cancellation, so explicitly race and close its owned stream. */
  async connect(signal: AbortSignal): Promise<void> {
    const bounded = AbortSignal.any([signal, AbortSignal.timeout(5000)]);
    bounded.throwIfAborted();
    let abort: () => void = () => {};
    const connecting = this.client.connect(this.transport, { signal: bounded, timeout: 5000 });
    const cancelled = new Promise<never>((_, reject) => {
      abort = () => {
        void this.close().catch(() => {});
        reject(new Error('MCP connection aborted'));
      };
      bounded.addEventListener('abort', abort, { once: true });
      if (bounded.aborted) abort();
    });
    try {
      await Promise.race([connecting, cancelled]);
    } catch (error) {
      await this.close();
      throw error;
    } finally {
      bounded.removeEventListener('abort', abort);
    }
  }
  /** Bound all discovery pages before registering deferred, distinct source aliases. */
  async registerTools(registry: ToolRegistry, signal: AbortSignal): Promise<readonly string[]> {
    const tools: Awaited<ReturnType<Client['listTools']>>['tools'] = [];
    const cursors = new Set<string>();
    let cursor: string | undefined,
      bytes = 0;
    for (let page = 0; ; page++) {
      if (page >= 100) throw new Error('MCP page limit exceeded');
      const result = await this.client.listTools(cursor ? { cursor } : {}, {
        signal,
        timeout: 10000,
      });
      bytes += Buffer.byteLength(JSON.stringify(result));
      if (bytes > 33554432 || tools.length + result.tools.length > 10000)
        throw new Error('MCP discovery limit exceeded');
      for (const tool of result.tools)
        if (!tool.name || tool.name.length > 1024) throw new Error('Invalid MCP tool');
      tools.push(...result.tools);
      if (!result.nextCursor) break;
      if (result.nextCursor.length > 4096 || cursors.has(result.nextCursor))
        throw new Error('Invalid MCP cursor');
      cursor = result.nextCursor;
      cursors.add(cursor);
    }
    const aliases = tools.map((tool) => mcpAlias(this.server, tool.name));
    if (new Set(aliases).size !== aliases.length) throw new Error('Duplicate MCP tool');
    tools.forEach((tool, index) =>
      registry.register({
        name: aliases[index]!,
        description: (tool.description ?? tool.name).slice(0, 8192),
        searchHint: `${this.server} ${tool.name}`,
        schema: tool.inputSchema as ToolDescriptor['schema'],
        execute: async (args, context) => {
          const signal = AbortSignal.any([context.signal, AbortSignal.timeout(10000)]);
          const stop = () => {
            void this.close().catch(() => {});
          };
          signal.addEventListener('abort', stop, { once: true });
          try {
            signal.throwIfAborted();
            if (!args || typeof args !== 'object' || Array.isArray(args))
              throw new Error('MCP arguments must be an object');
            const callId = context.callId ?? randomUUID();
            const result = await this.client.callTool(
              { name: tool.name, arguments: args },
              undefined,
              {
                signal,
                timeout: 10000,
                onprogress: (progress) =>
                  context.emit({
                    type: 'tool-progress',
                    name: aliases[index]!,
                    callId,
                    scope: context.scope,
                    progress:
                      typeof progress.message === 'string'
                        ? progress.message.slice(0, 1024)
                        : String(progress.progress),
                  }),
              }
            );
            return {
              content: result.content as JsonValue[],
              ...(result.structuredContent === undefined
                ? {}
                : { structuredContent: result.structuredContent as JsonValue }),
              isError: result.isError === true,
            };
          } catch {
            return {
              content: [
                {
                  type: 'text',
                  text: context.signal.aborted ? 'MCP call aborted.' : 'MCP call failed.',
                },
              ],
              isError: true,
            };
          } finally {
            signal.removeEventListener('abort', stop);
          }
        },
      })
    );
    return aliases;
  }
  /** Close this turn's client and SSE stream once; no shared process ownership. */
  close(): Promise<void> {
    return (this.closing ??= this.client.close());
  }
}
