/**
 * Thirty-two agents, sixty rooms, forty sessions and seven things that need
 * you — the fleet the design has to hold its shape under.
 *
 * What this fixture is for: Heads up's cap and its "+ N more" row, Library's rollups
 * on folded sections, groups (manual and smart) as sub-headers, and the build
 * budget — the model has to produce all of this in under 5ms.
 *
 * Generated by loop rather than written out, because thirty-two hand-written
 * agents are thirty-two places for a typo to become a test expectation.
 * Deterministic: every value is a function of its index, and nothing here reads
 * a clock it was not given.
 *
 * **Read it, never edit it** — see `first-run.ts` for why.
 *
 * @module features/dashboard-sidebar/model/fixtures/power
 */
import type { SidebarItemRef } from '@dorkos/shared/config-schema';
import type { RoomSummary, ThreadSummary } from '@dorkos/shared/room-schemas';
import type { Session } from '@dorkos/shared/types';
import type { AgentRosterEntry, SidebarAttentionSignal, SidebarState } from '../sidebar-state';
import { agent, emptyState, hoursAgo, person, prefs, room, session, thread } from './factories';

/** How many agents this operator runs. */
const AGENT_COUNT = 32;

/** How many rooms they are in. */
const ROOM_COUNT = 60;

/** How many sessions the cockpit can see. */
const SESSION_COUNT = 40;

/** How many things need them right now — enough to overflow Heads up's cap of 3. */
const SIGNAL_COUNT = 7;

/** The runtimes the fleet is spread across. */
const RUNTIMES = ['claude-code', 'codex', 'opencode'];

/** The agent's directory for one index. */
const agentPath = (index: number) => `/Users/dev/code/agent-${String(index).padStart(2, '0')}`;

const agents: AgentRosterEntry[] = Array.from({ length: AGENT_COUNT }, (_, index) =>
  agent(agentPath(index), {
    runtime: RUNTIMES[index % RUNTIMES.length] ?? 'claude-code',
    attention: index % 5 === 0 ? 'needs-attention' : index % 7 === 0 ? 'inactive' : 'active',
    lastActivityAt: Date.parse(hoursAgo(index)),
  })
);

const displayNames = Object.fromEntries(
  agents.map((entry, index) => [entry.path, `agent-${String(index).padStart(2, '0')}`])
);

const rooms: RoomSummary[] = Array.from({ length: ROOM_COUNT }, (_, index) =>
  index % 6 === 0
    ? room({
        id: `dm-${index}`,
        kind: 'dm',
        title: `Person ${index}`,
        unreadCount: index % 12 === 0 ? 2 : 0,
        participants: [person(`person-${index}`, `Person ${index}`)],
      })
    : room({
        id: `room-${index}`,
        kind: 'channel',
        title: `channel-${index}`,
        unreadCount: index % 4 === 0 ? index : 0,
        working: index % 9 === 0 ? 1 : 0,
      })
);

const sessions: Session[] = Array.from({ length: SESSION_COUNT }, (_, index) =>
  session({
    id: `ses-${index}`,
    title: `Task ${index}`,
    cwd: agentPath(index % AGENT_COUNT),
    updatedAt: hoursAgo(index / 10),
    ...(index % 8 === 0 ? { origin: 'task' as const } : {}),
  })
);

const threads: ThreadSummary[] = Array.from({ length: 4 }, (_, index) =>
  thread({
    roomId: `room-${index * 5 + 1}`,
    roomTitle: `channel-${index * 5 + 1}`,
    rootEntryId: `entry-${index}`,
    unreadCount: index,
  })
);

const attention: SidebarAttentionSignal[] = Array.from({ length: SIGNAL_COUNT }, (_, index) => ({
  id: `sig-${index}`,
  kind: (['permission-prompt', 'question', 'error', 'schedule-approval'] as const)[index % 4],
  primary: displayNames[agentPath(index)] ?? `agent-${index}`,
  since: hoursAgo(index * 0.1 + 0.1),
  deepLink: `/session?sessionId=ses-${index}`,
  agentPath: agentPath(index),
}));

const workingSessionIds = sessions
  .filter((entry, index) => index % 7 === 1 && entry.origin === undefined)
  .map((entry) => entry.id);

const sessionStatuses: SidebarState['sessionStatuses'] = Object.fromEntries(
  sessions.map((entry) => [entry.id, workingSessionIds.includes(entry.id) ? 'streaming' : 'idle'])
);

const interactions = Object.fromEntries([
  ...sessions.map((entry, index) => [`session:${entry.id}`, hoursAgo(index * 0.1)]),
  ...rooms.map((entry, index) => [`room:${entry.id}`, hoursAgo(index * 0.05)]),
]);

const groupMembers = (from: number, to: number): SidebarItemRef[] =>
  Array.from({ length: to - from }, (_, index) => ({
    kind: 'agent' as const,
    path: agentPath(from + index),
  }));

/** The power-user journey. */
export const powerFixture: SidebarState = emptyState({
  agents,
  displayNames,
  rooms,
  threads,
  sessions,
  workingSessionIds,
  sessionStatuses,
  attention,
  interactions,
  prefs: prefs({
    pinned: [
      { kind: 'agent', path: agentPath(0) },
      { kind: 'room', roomId: 'room-1' },
    ],
    muted: [{ kind: 'room', roomId: 'room-2' }],
    sections: {
      channels: { collapsed: true },
      agents: { collapsed: false, sortMode: 'name' },
    },
    groups: [
      {
        id: 'group-frontend',
        name: 'Frontend',
        kind: 'manual',
        items: groupMembers(0, 4),
        collapsed: true,
        sortMode: 'manual',
        displayFilter: 'all',
        muted: false,
      },
      {
        id: 'group-codex',
        name: 'Codex fleet',
        kind: 'smart',
        items: [],
        collapsed: false,
        sortMode: 'name',
        displayFilter: 'all',
        muted: false,
        rules: { runtimes: ['codex'] },
      },
    ],
  }),
  activeTarget: { kind: 'session', sessionId: 'ses-3', agentPath: agentPath(3), cwd: agentPath(3) },
  journey: {
    discoveredUnregisteredPaths: [],
    nonSystemAgentCount: AGENT_COUNT,
    hasEverStartedSession: true,
    hasPostedInTeam: true,
    hasDorkBotSession: true,
  },
  digest: { finishedWhileAwayCount: 0, idleWhileAwayCount: 0 },
});
