// React is provided by the host — do not import it directly.
// Use React.createElement() and React.useState() etc. from the global.
import type { ExtensionAPI } from '@dorkos/extension-api';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Shape of a single Linear issue from the GraphQL API. */
interface LinearIssue {
  id: string;
  identifier: string;
  title: string;
  priority: number;
  state?: { name: string; type: string; color: string };
  team?: { key: string; name: string };
  project?: { name: string };
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Activate
// ---------------------------------------------------------------------------

/**
 * Linear Issues extension — shows the authenticated user's active Linear
 * issues on the DorkOS dashboard.
 *
 * The settings tab for API key management is auto-generated by the host
 * from the `serverCapabilities.secrets` declaration in extension.json.
 * No settings code needed here.
 *
 * To install:
 * 1. Copy this directory to ~/.dork/extensions/linear-issues/
 * 2. Open DorkOS Settings > Extensions
 * 3. Enable "Linear Issues"
 * 4. Configure your Linear API key in the extension's Settings tab
 */
export function activate(api: ExtensionAPI): () => void {
  // Dashboard section showing compact issue list
  const unregisterSection = api.registerComponent(
    'dashboard.sections',
    'linear-issues-section',
    LinearIssuesSection,
    { priority: 6 },
  );

  return () => {
    unregisterSection();
  };
}

// ---------------------------------------------------------------------------
// Dashboard Section
// ---------------------------------------------------------------------------

function LinearIssuesSection() {
  const [issues, setIssues] = React.useState<LinearIssue[] | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    const fetchIssues = async () => {
      try {
        const res = await fetch('/api/ext/linear-issues/cached');
        const data = await res.json();
        setIssues(data?.data?.data?.viewer?.assignedIssues?.nodes ?? []);
      } catch (err: unknown) {
        setError(String(err));
      } finally {
        setLoading(false);
      }
    };
    fetchIssues();
    const interval = setInterval(fetchIssues, 60_000);
    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return React.createElement('div', { style: styles.card }, 'Loading issues...');
  }
  if (error) {
    return React.createElement('div', { style: styles.card }, `Error: ${error}`);
  }
  if (!issues?.length) {
    return React.createElement('div', { style: styles.card }, 'No active issues');
  }

  return React.createElement(
    'div',
    { style: styles.card },
    React.createElement('h3', { style: styles.heading }, 'Linear Issues'),
    React.createElement(
      'div',
      { style: styles.list },
      issues.map((issue) =>
        React.createElement(IssueRow, { key: issue.id, issue }),
      ),
    ),
  );
}

// ---------------------------------------------------------------------------
// Issue Row
// ---------------------------------------------------------------------------

function IssueRow({ issue }: { issue: LinearIssue }) {
  return React.createElement(
    'div',
    { style: styles.issueRow },
    React.createElement('span', {
      style: { ...styles.statusDot, backgroundColor: issue.state?.color ?? '#888' },
    }),
    React.createElement('span', { style: styles.identifier }, issue.identifier),
    React.createElement('span', { style: styles.title }, issue.title),
    React.createElement('span', { style: styles.team }, issue.team?.key),
  );
}

// ---------------------------------------------------------------------------
// Styles — uses CSS custom properties from the host theme
// ---------------------------------------------------------------------------

const styles: Record<string, React.CSSProperties> = {
  card: {
    padding: '16px',
    borderRadius: '8px',
    border: '1px solid var(--border)',
    marginBottom: '12px',
  },
  heading: { margin: '0 0 12px', fontSize: '14px', fontWeight: 600 },
  list: { display: 'flex', flexDirection: 'column', gap: '6px' },
  issueRow: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px' },
  statusDot: { width: '8px', height: '8px', borderRadius: '50%', flexShrink: 0 },
  identifier: {
    fontFamily: 'var(--font-mono)',
    color: 'var(--muted-foreground)',
    fontSize: '12px',
    flexShrink: 0,
  },
  title: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  team: {
    marginLeft: 'auto',
    fontSize: '11px',
    color: 'var(--muted-foreground)',
    flexShrink: 0,
  },
};
