/**
 * The single composition root for DorkOS's Capability Registry (spec
 * `capability-registry`, task 2.3).
 *
 * {@link composeDorkOsCapabilityRegistry} folds the migrated domains — operator,
 * marketplace, and the self-description domain — into ONE immutable registry.
 * Composing them together (rather than one registry per surface) is what restores
 * cross-domain duplicate detection: a tool name or capability id claimed by two
 * different domains throws at boot. It then back-writes the composed registry onto
 * the shared dependency bag so `capabilities.list` can serialize the registry it
 * belongs to (the late-binding self-reference; see `capabilities-domain.ts`).
 *
 * A domain is included only when its service handles are present in `deps`:
 * `operatorDeps` gates the operator domain, `marketplaceDeps` the marketplace
 * domain, `roomDeps` the rooms domain, and the self-description domain is always
 * present. Every included
 * domain's `assertDeps` runs inside `composeRegistry`, so a domain admitted
 * without its deps fails fast at boot.
 *
 * @module services/core/self-description/dorkos-registry
 */
import { noopLogger } from '@dorkos/shared/logger';

import {
  composeRegistry,
  type CapabilityDeps,
  type CapabilityDomain,
  type CapabilityInvocationObserver,
  type CapabilityRegistry,
} from '../capabilities/index.js';
import { operatorDomain } from '../operator/operator-capabilities.js';
import { marketplaceDomain } from '../../marketplace-mcp/marketplace-capabilities.js';
import { connectorDomain } from '../../connectors/connector-capabilities.js';
import { mcpDomain } from '../../mesh/mcp-capabilities.js';
import { roomsDomain } from '../../rooms/room-capabilities.js';
import { memoryDomain } from '../../memory/memory-capabilities.js';
import { capabilitiesDomain } from './capabilities-domain.js';

/**
 * Compose the whole DorkOS capability registry from whichever domains `deps`
 * enables, then back-write it onto `deps` for the self-description capability.
 *
 * @param deps - The boot-time dependency bag. `operatorDeps` includes the
 *   operator domain; `marketplaceDeps` the marketplace domain; `connectorDeps`
 *   the connector domain; `mcpDeps` the MCP-server-management domain; `roomDeps`
 *   the rooms domain; the self-description domain is always included. The composed
 *   registry is written back onto `deps.registry`.
 * @param onInvocation - Optional observer called after every invocation. Boot
 *   passes the Activity attribution observer so an identified agent's calls are
 *   recorded in the feed (spec `agent-trust` §3.1); omitted in unit tests.
 * @returns The frozen, ready-to-serve registry.
 */
export function composeDorkOsCapabilityRegistry(
  deps: CapabilityDeps,
  onInvocation?: CapabilityInvocationObserver
): CapabilityRegistry {
  const domains: CapabilityDomain[] = [];
  if (deps.operatorDeps) domains.push(operatorDomain);
  if (deps.marketplaceDeps) domains.push(marketplaceDomain);
  if (deps.connectorDeps) domains.push(connectorDomain);
  if (deps.mcpDeps) domains.push(mcpDomain);
  if (deps.roomDeps) domains.push(roomsDomain);
  // Unconditional, unlike every domain above it: memory has no service handle to
  // switch off. Every install has a filesystem, the builtin provider needs
  // nothing else, and an agent that could not save what it learns is the defect
  // this domain exists to fix — so there is no configuration under which the
  // right answer is to leave the verb out.
  domains.push(memoryDomain);
  domains.push(capabilitiesDomain);

  const registry = composeRegistry(domains, deps, onInvocation);
  // Back-write the composed registry so `capabilities.list` can serialize it.
  // Done immediately after composition, before any request is served — this is
  // the late-binding half of the self-reference.
  deps.registry = registry;
  return registry;
}

/**
 * Compose a projection-only registry of EVERY domain, for static OpenAPI export
 * (spec `capability-registry`, task 2.5).
 *
 * The OpenAPI document is generated by `scripts/export-openapi.ts` without
 * booting the server, so no live service handles exist. This composer includes
 * all domains unconditionally (unlike {@link composeDorkOsCapabilityRegistry},
 * which gates each domain on its deps) so every capability's `http` surface
 * projects into the document. The placeholder deps satisfy each domain's
 * `assertDeps` presence check and are never invoked: OpenAPI projection reads
 * only static capability metadata (`id`, `surfaces`, `input`/`output` schemas),
 * never `invoke`.
 *
 * @returns The frozen registry over all domains, for documentation projection only.
 */
export function composeCapabilityRegistryForDocs(): CapabilityRegistry {
  const domains: CapabilityDomain[] = [
    operatorDomain,
    marketplaceDomain,
    connectorDomain,
    mcpDomain,
    roomsDomain,
    memoryDomain,
    capabilitiesDomain,
  ];
  const deps: CapabilityDeps = {
    logger: noopLogger,
    operatorDeps: {} as CapabilityDeps['operatorDeps'],
    marketplaceDeps: {} as CapabilityDeps['marketplaceDeps'],
    connectorDeps: {} as CapabilityDeps['connectorDeps'],
    mcpDeps: {} as CapabilityDeps['mcpDeps'],
    roomDeps: {} as CapabilityDeps['roomDeps'],
  };
  return composeRegistry(domains, deps);
}
