/**
 * Cross-harness hooks generation: translate a Claude hooks config into each
 * target harness's on-disk hook config.
 *
 * Claude and Codex share the same matcher-group hook shape
 * (`{ matcher?, hooks: [{ type, command }] }`); Cursor and Copilot flatten each
 * command into a standalone entry. All three write a WRAPPED file rather than a
 * bare event map: Codex documents `{ description?, hooks }`, Cursor and Copilot
 * `{ version, hooks }`. Every
 * generator routes each Claude event name through its canonical form and out to
 * the target harness spelling. Any event with no canonical form, or no target
 * equivalent, is reported in `dropped` with a reason, never silently lost. A
 * projected command STILL carrying a Claude-only substitution token (e.g.
 * `${CLAUDE_PLUGIN_ROOT}`) surfaces in `warnings`: the hook still projects, but
 * the operator is told it may not work in the (non-Claude) target.
 *
 * By the time hooks reach these generators, an installed plugin's
 * `${CLAUDE_PLUGIN_ROOT}` has already been rewritten to its absolute install dir
 * by the projector (the install root is known at plan time), so those hooks are
 * portable and warning-free. Only AUTHORED hooks (whose root is unknown) and
 * other unresolved `${CLAUDE_*}` tokens remain here to warn on.
 *
 * @module generate/hooks
 */
import type { HarnessId } from '../manifest/schema.js';
import {
  CLAUDE_TO_CANONICAL_EVENT_NAMES,
  CANONICAL_TO_CODEXCLI_EVENT_NAMES,
  CANONICAL_TO_CURSOR_EVENT_NAMES,
  CANONICAL_TO_COPILOT_EVENT_NAMES,
} from '../vendor/rulesync-maps.js';

/** A single hook command (Claude and Codex both use the `command` type). */
export interface HookCommand {
  /** The hook command kind. */
  type: string;
  /** The shell command to execute. */
  command: string;
}

/** A matcher group: an optional matcher and its ordered hook commands. */
export interface HookMatcherGroup {
  /** Optional tool/event matcher (a glob or regex). */
  matcher?: string;
  /** The ordered hook commands for this matcher group. */
  hooks: HookCommand[];
}

/** The `.hooks` object from `.claude/settings.json`, keyed by Claude event name. */
export type ClaudeHooksConfig = Record<string, HookMatcherGroup[]>;

/**
 * An empty hooks config with NO prototype — the only safe accumulator for a
 * record keyed by event names.
 *
 * Event names come from a third-party package's `hooks.json` (and from a
 * user-owned settings file), so `__proto__` is a key a package can choose.
 * Assigning it on a `{}` literal invokes `Object.prototype`'s inherited setter
 * rather than creating a property: the groups vanish without an error, and the
 * accumulator's own prototype is replaced by whatever was assigned. Every stage
 * that accumulates hooks by event name therefore starts from this — one hop
 * still using a `{}` literal re-opens the hole for the whole chain.
 *
 * @returns a fresh, prototype-less hooks config.
 */
export function emptyHooksConfig(): ClaudeHooksConfig {
  return Object.create(null) as ClaudeHooksConfig;
}

/**
 * A generated matcher-group hooks object (the `hooks` member of Codex's
 * `.codex/hooks.json`), keyed by the target harness's event name. Same shape as
 * {@link ClaudeHooksConfig}.
 */
export type CodexHooksConfig = Record<string, HookMatcherGroup[]>;

/**
 * The `description` the engine writes into every generated hooks file that has a
 * place for one. Codex documents the key as an optional free-text string, so it
 * reads as a comment: the one line that tells a person opening
 * `.codex/hooks.json` that a program wrote it and how to get it back.
 *
 * It is NOT an ownership marker — ownership lives in the `.dorkos-generated`
 * sidecar, because a marker cannot tell a generated file from a generated file
 * somebody has since edited. See `apply/generated-ownership.ts`.
 */
export const GENERATED_HOOKS_DESCRIPTION =
  'Generated by DorkOS Harness Sync — run `dorkos harness sync` to regenerate';

/**
 * The generated Codex hooks file (`.codex/hooks.json`) in the shape Codex
 * documents: the event map nested under a top-level `hooks` key, beside an
 * optional free-text `description`.
 *
 * @see https://learn.chatgpt.com/docs/hooks
 */
export interface CodexHooksFile {
  /** Free-text note that a program wrote this file ({@link GENERATED_HOOKS_DESCRIPTION}). */
  description: string;
  /** Codex-event-keyed matcher groups. */
  hooks: CodexHooksConfig;
}

/**
 * A single flattened hook entry for a harness (Cursor / Copilot) that does not
 * use the nested matcher-group shape. The optional `matcher` rides on the entry
 * itself rather than wrapping a group.
 */
export interface FlatHookEntry {
  /** The hook command kind (`command`). */
  type: string;
  /** The shell command to execute. */
  command: string;
  /** Optional tool/event matcher carried over from the source matcher group. */
  matcher?: string;
}

/**
 * A generated flat hooks file: a `{ version, hooks }` wrapper whose `hooks` maps
 * each target event name to an array of standalone {@link FlatHookEntry} items.
 * This is the shape Cursor (`.cursor/hooks.json`) and Copilot
 * (`.github/hooks/copilot-hooks.json`) both use.
 */
export interface FlatHooksFile {
  /** The config schema version (currently 1 for both Cursor and Copilot). */
  version: 1;
  /** Target-event-keyed arrays of flat hook entries. */
  hooks: Record<string, FlatHookEntry[]>;
}

/**
 * The repo-relative path of the Codex hooks file the engine generates
 * (gitignored, rewritten every sync from the canonical `.claude/settings.json`
 * hooks plus installed-plugin hooks), so the single source of truth for this
 * path is shared by the projector's generate target and the apply stage's
 * generated-orphan prune. When no plugin or authored hook contributes a
 * Codex-mappable event, the projector emits no generate action and the apply
 * stage prunes the file it wrote here — but only the file it wrote: Codex
 * documents this path as one a person may author, so both the rewrite and the
 * prune are gated on the `.dorkos-generated` sidecar
 * (`apply/generated-ownership.ts`).
 */
export const CODEX_HOOKS_TARGET = '.codex/hooks.json';

/**
 * The repo-relative path of the Cursor hooks file the engine generates
 * (gitignored, rewritten every sync), on the same lifecycle — and under the same
 * sidecar ownership rule — as {@link CODEX_HOOKS_TARGET}. Cursor's docs also
 * describe this as a file people write by hand.
 *
 * @see https://cursor.com/docs/agent/hooks
 */
export const CURSOR_HOOKS_TARGET = '.cursor/hooks.json';

/**
 * The repo-relative path of the Copilot hooks file the engine generates
 * (gitignored, rewritten every sync), on the same lifecycle — and under the same
 * sidecar ownership rule — as {@link CODEX_HOOKS_TARGET}.
 *
 * @see https://docs.github.com/en/copilot/concepts/agents/coding-agent/about-hooks
 */
export const COPILOT_HOOKS_TARGET = '.github/hooks/copilot-hooks.json';

/**
 * Every repo-relative hooks file the engine generates, one per harness. The
 * apply stage prunes one of these that the current plan no longer regenerates
 * (the source plugin/hook is gone) — but ONLY when its `.dorkos-generated`
 * sidecar proves the engine wrote exactly the bytes on disk, and only for a
 * harness the manifest enables. Presence on this list is not ownership: all
 * three are paths their vendors document as hand-authorable.
 *
 * Gemini is deliberately absent for a stronger reason: its hooks live inside the
 * SHARED `.gemini/settings.json`, which also holds unrelated user settings, so
 * there is no whole file to generate at all — it is projected as a merge, or
 * honestly dropped, never listed here.
 */
export const GENERATED_HOOK_TARGETS = [
  CODEX_HOOKS_TARGET,
  CURSOR_HOOKS_TARGET,
  COPILOT_HOOKS_TARGET,
] as const;

/**
 * Which harness each generated hook file belongs to. The apply stage's orphan
 * sweep reads this so it only ever prunes a file for a harness the manifest
 * actually enables — a Copilot hooks file is not the engine's business in a repo
 * that never enabled Copilot (AP-07).
 */
export const GENERATED_HOOK_TARGET_HARNESSES: Readonly<
  Record<(typeof GENERATED_HOOK_TARGETS)[number], HarnessId>
> = {
  [CODEX_HOOKS_TARGET]: 'codex',
  [CURSOR_HOOKS_TARGET]: 'cursor',
  [COPILOT_HOOKS_TARGET]: 'copilot',
};

/** A single dropped hook event and the reason it could not be projected. */
export interface DroppedHook {
  /** The Claude event name that was dropped. */
  event: string;
  /** Human-readable reason the event has no home in the target harness. */
  reason: string;
}

/** A projected hook that may not work in the target harness, with the reason. */
export interface HookWarning {
  /** The Claude event name whose command carries the unresolved token. */
  event: string;
  /** Human-readable warning (which token, and that the target harness will not resolve it). */
  reason: string;
}

/**
 * Substitution tokens Claude Code resolves at hook-exec time that no other
 * harness understands. A projected command that still contains one of these
 * (e.g. `${CLAUDE_PLUGIN_ROOT}` in a plugin's Stop hook) is broken in the target
 * harness, so the engine warns rather than projecting it as silently-correct.
 */
const CLAUDE_ONLY_HOOK_TOKENS = ['${CLAUDE_PLUGIN_ROOT}'] as const;

/**
 * Match any `${CLAUDE_*}` / `${CLAUDE_*_ROOT}`-style substitution: a literal
 * `CLAUDE_`-prefixed variable Claude Code expands but other harnesses leave
 * verbatim. This is the general net beyond the named tokens above.
 */
const CLAUDE_VAR_PATTERN = /\$\{CLAUDE_[A-Z0-9_]*\}/;

/**
 * Detect Claude-only substitution tokens in a projected hook command.
 *
 * @param command - the shell command being projected to a non-Claude harness.
 * @returns the distinct Claude-only tokens found (empty when the command is portable).
 */
function findClaudeOnlyTokens(command: string): string[] {
  const found = new Set<string>();
  for (const token of CLAUDE_ONLY_HOOK_TOKENS) {
    if (command.includes(token)) found.add(token);
  }
  for (const match of command.matchAll(new RegExp(CLAUDE_VAR_PATTERN, 'g'))) {
    found.add(match[0]);
  }
  return [...found];
}

/**
 * Collect warnings for any matcher group in `groups` whose command still carries
 * a Claude-only token. The hook is still projected (warn-and-project, not drop):
 * a broken hook that is reported is honest, an absent one is not. The warning
 * names the actual target harness (FND-11) so it is correct for every target,
 * not just Codex.
 *
 * @param harnessLabel - the human-readable target harness name (e.g. `"Cursor"`).
 * @param event - the Claude event name whose command is being checked.
 * @param groups - the matcher groups projected for this event.
 * @returns zero or one warning for the event (empty when the command is portable).
 */
function warnClaudeOnlyTokens(
  harnessLabel: string,
  event: string,
  groups: HookMatcherGroup[]
): HookWarning[] {
  const tokens = new Set<string>();
  for (const group of groups) {
    for (const hook of group.hooks) {
      for (const token of findClaudeOnlyTokens(hook.command)) tokens.add(token);
    }
  }
  if (tokens.size === 0) return [];
  return [
    {
      event,
      reason: `hook command for "${event}" uses Claude-only ${[...tokens]
        .map((t) => `"${t}"`)
        .join(', ')}; ${harnessLabel} will not resolve it, so this hook may not work`,
    },
  ];
}

/** One event that translated to a target harness, with its source matcher groups. */
interface TranslatedEvent {
  /** The target harness's event name (e.g. Codex `Stop`, Cursor `stop`). */
  targetEvent: string;
  /** The source matcher groups to project under `targetEvent`. */
  groups: HookMatcherGroup[];
}

/**
 * Translate a Claude hooks config's event keys into one target harness's event
 * names, collecting drops (no canonical / no target home) and warnings
 * (projected-but-possibly-broken). The caller decides how to serialize the
 * translated events into the target's on-disk shape.
 *
 * @param claudeHooks - the `.hooks` object from `.claude/settings.json`.
 * @param harnessLabel - the human-readable target harness name (for warnings/drops).
 * @param eventMap - the `CANONICAL_TO_<tool>_EVENT_NAMES` map for the target.
 * @returns the translated events plus the drop and warning lists.
 */
function translateHooks(
  claudeHooks: ClaudeHooksConfig,
  harnessLabel: string,
  eventMap: Record<string, string>
): { translated: TranslatedEvent[]; dropped: DroppedHook[]; warnings: HookWarning[] } {
  const translated: TranslatedEvent[] = [];
  const dropped: DroppedHook[] = [];
  const warnings: HookWarning[] = [];

  for (const [event, groups] of Object.entries(claudeHooks)) {
    // `Object.hasOwn`, never a bare lookup: the event name is package-chosen, and
    // `map["constructor"]` on a plain object answers with a FUNCTION off the
    // prototype — a truthy "canonical event" that no target map can resolve, and
    // a drop reason naming a class instead of an event.
    const canonical = Object.hasOwn(CLAUDE_TO_CANONICAL_EVENT_NAMES, event)
      ? CLAUDE_TO_CANONICAL_EVENT_NAMES[event]
      : undefined;
    if (!canonical) {
      dropped.push({ event, reason: `no canonical mapping for Claude event "${event}"` });
      continue;
    }
    const targetEvent = Object.hasOwn(eventMap, canonical) ? eventMap[canonical] : undefined;
    if (!targetEvent) {
      dropped.push({
        event,
        reason: `${harnessLabel} has no equivalent for "${event}" (canonical "${canonical}")`,
      });
      continue;
    }
    warnings.push(...warnClaudeOnlyTokens(harnessLabel, event, groups));
    translated.push({ targetEvent, groups });
  }

  return { translated, dropped, warnings };
}

/** Flatten matcher groups into standalone entries, carrying `matcher` onto each entry. */
function flattenGroups(groups: HookMatcherGroup[]): FlatHookEntry[] {
  const entries: FlatHookEntry[] = [];
  for (const group of groups) {
    for (const hook of group.hooks) {
      const entry: FlatHookEntry = { type: hook.type, command: hook.command };
      if (group.matcher !== undefined) entry.matcher = group.matcher;
      entries.push(entry);
    }
  }
  return entries;
}

/** Assemble translated events into a `{ version, hooks }` flat file, concatenating per event. */
function toFlatFile(translated: TranslatedEvent[]): FlatHooksFile {
  const hooks: Record<string, FlatHookEntry[]> = {};
  for (const { targetEvent, groups } of translated) {
    hooks[targetEvent] = [...(hooks[targetEvent] ?? []), ...flattenGroups(groups)];
  }
  return { version: 1, hooks };
}

/**
 * Translate a Claude hooks config into a Codex hooks config.
 *
 * Events with no Codex home land in `dropped` (never silently lost). Events that
 * DO project but whose command carries a Claude-only substitution token (e.g.
 * `${CLAUDE_PLUGIN_ROOT}`, which Codex leaves verbatim) are still projected but
 * surface in `warnings` so the operator is told the hook may not work.
 *
 * The result is the file Codex documents — the event map under a top-level
 * `hooks` key, beside the generated-file `description` — not a bare event map
 * (HK-01). The bare form was never documented, so hooks written that way most
 * likely never ran.
 *
 * @param claudeHooks - the `.hooks` object from `.claude/settings.json`.
 * @returns the Codex hooks file, the list of dropped events, and the list of
 *   projected-but-possibly-broken hook warnings.
 * @see https://learn.chatgpt.com/docs/hooks
 */
export function generateCodexHooks(claudeHooks: ClaudeHooksConfig): {
  file: CodexHooksFile;
  dropped: DroppedHook[];
  warnings: HookWarning[];
} {
  const { translated, dropped, warnings } = translateHooks(
    claudeHooks,
    'Codex',
    CANONICAL_TO_CODEXCLI_EVENT_NAMES
  );
  const hooks: CodexHooksConfig = {};
  for (const { targetEvent, groups } of translated) hooks[targetEvent] = groups;
  return { file: { description: GENERATED_HOOKS_DESCRIPTION, hooks }, dropped, warnings };
}

/**
 * Translate a Claude hooks config into a Cursor hooks file
 * (`.cursor/hooks.json`).
 *
 * Cursor uses a `{ version, hooks }` wrapper whose `hooks` maps each event to an
 * array of FLAT entries (`{ command, type, matcher? }`), not the nested
 * matcher-group shape, so each source command becomes its own entry. Events
 * with no Cursor home land in `dropped`; a projected command with a Claude-only
 * token surfaces in `warnings` naming Cursor.
 *
 * @param claudeHooks - the `.hooks` object from `.claude/settings.json`.
 * @returns the Cursor hooks file, the dropped events, and the warnings.
 * @see https://cursor.com/docs/agent/hooks
 */
export function generateCursorHooks(claudeHooks: ClaudeHooksConfig): {
  file: FlatHooksFile;
  dropped: DroppedHook[];
  warnings: HookWarning[];
} {
  const { translated, dropped, warnings } = translateHooks(
    claudeHooks,
    'Cursor',
    CANONICAL_TO_CURSOR_EVENT_NAMES
  );
  return { file: toFlatFile(translated), dropped, warnings };
}

/**
 * Translate a Claude hooks config into a Copilot hooks file
 * (`.github/hooks/copilot-hooks.json`).
 *
 * Copilot (the cloud coding agent) uses the same `{ version, hooks }` wrapper +
 * flat-entry shape as Cursor. Its command entries additionally accept
 * platform-specific `bash`/`powershell` keys, but a portable `command` entry is
 * valid, so the engine emits the same `{ command, type, matcher? }` entry it
 * emits for Cursor. Events with no Copilot home land in `dropped`; a projected
 * command with a Claude-only token surfaces in `warnings` naming Copilot.
 *
 * @param claudeHooks - the `.hooks` object from `.claude/settings.json`.
 * @returns the Copilot hooks file, the dropped events, and the warnings.
 * @see https://docs.github.com/en/copilot/concepts/agents/coding-agent/about-hooks
 */
export function generateCopilotHooks(claudeHooks: ClaudeHooksConfig): {
  file: FlatHooksFile;
  dropped: DroppedHook[];
  warnings: HookWarning[];
} {
  const { translated, dropped, warnings } = translateHooks(
    claudeHooks,
    'Copilot',
    CANONICAL_TO_COPILOT_EVENT_NAMES
  );
  return { file: toFlatFile(translated), dropped, warnings };
}
