/**
 * Type re-exports — all types derived from Zod schemas in `schemas.ts`.
 *
 * Import types from this module (`@dorkos/shared/types`) for consuming code.
 * Import schemas from `@dorkos/shared/schemas` when you need runtime validation.
 *
 * @module shared/types
 */
export type {
  PermissionMode,
  Session,
  CreateSessionRequest,
  UpdateSessionRequest,
  SendMessageRequest,
  StreamEventType,
  StreamEvent,
  TextDelta,
  ToolCallEvent,
  ApprovalEvent,
  QuestionOption,
  QuestionItem,
  QuestionPromptEvent,
  ErrorEvent,
  DoneEvent,
  SessionStatusEvent,
  TextPart,
  ToolCallPart,
  MessagePart,
  MessageType,
  HistoryMessage,
  HistoryToolCall,
  TaskStatus,
  TaskItem,
  TaskUpdateEvent,
  BrowseDirectoryResponse,
  DirectoryEntry,
  CommandEntry,
  CommandRegistry,
  FileListQuery,
  FileListResponse,
  HealthResponse,
  TunnelStatus,
  ServerConfig,
  GitStatusResponse,
  GitStatusError,
  SessionLockedError,
  ConfigPatchRequest,
  ConfigPatchResponse,
  PulseScheduleStatus,
  PulseRunStatus,
  PulseRunTrigger,
  PulseSchedule,
  PulseRun,
  CreateScheduleRequest,
  CreateScheduleInput,
  UpdateScheduleRequest,
  ListRunsQuery,
  RelayReceiptEvent,
  MessageDeliveredEvent,
  RelayMessageEvent,
  ModelOption,
} from './schemas.js';

export type {
  Performative,
  SignalType,
  ChannelType,
  RelayBudget,
  RelayEnvelope,
  Attachment,
  ResponseContext,
  StandardPayload,
  Signal,
  RelayAccessRule,
  TraceSpan,
  TraceSpanStatus,
  DeliveryMetrics,
  BudgetRejections,
  EndpointRegistration,
  AdapterType,
  RelayReceipt,
} from './relay-schemas.js';

export type {
  AgentRuntime,
  AgentHealthStatus,
  AgentBehavior,
  AgentBudget,
  AgentManifest,
  AgentHints,
  DiscoveryCandidate,
  DenialRecord,
  TopologyAgent,
  NamespaceInfo,
  CrossNamespaceRule,
  TopologyView,
  AgentHealth,
  MeshStatus,
  MeshInspect,
  MeshLifecycleEvent,
  AgentListQuery,
  RegisterAgentRequest,
  UpdateAgentRequest,
  UpdateAccessRuleRequest,
  ResolveAgentsRequest,
  ResolveAgentsResponse,
  CreateAgentRequest,
  HeartbeatRequest,
} from './mesh-schemas.js';
