import type { PlaygroundSection } from '../playground-registry';

/**
 * Chat component sections from ChatPage.
 *
 * Sources: MessageShowcases, ToolShowcases, InputShowcases,
 * StatusShowcases, MiscShowcases.
 */
export const CHAT_SECTIONS: PlaygroundSection[] = [
  // MessageShowcases
  {
    id: 'message-matrix',
    title: 'Message.* matrix',
    page: 'chat',
    category: 'Messages',
    keywords: [
      'message',
      'row',
      'conversation',
      'capabilities',
      'anchor',
      'rail',
      'corner',
      'density',
      'compact',
      'reactions',
      'run with',
      'shared',
    ],
  },
  {
    id: 'conversation-dividers',
    title: 'Conversation dividers',
    page: 'chat',
    category: 'Messages',
    keywords: ['divider', 'day', 'unread', 'new messages', 'separator', 'rule', 'boundary'],
  },
  {
    id: 'permissiondeniedchip',
    title: 'PermissionDeniedChip',
    page: 'chat',
    category: 'Messages',
    keywords: ['permission', 'denied', 'chip', 'classifier', 'blocked', 'auto', 'safety', 'tool'],
  },
  {
    id: 'usermessagecontent',
    title: 'UserMessageContent',
    page: 'chat',
    category: 'Messages',
    keywords: ['user', 'message', 'content', 'text', 'command', 'compaction'],
  },
  {
    id: 'assistantmessagecontent',
    title: 'AssistantMessageContent',
    page: 'chat',
    category: 'Messages',
    keywords: ['assistant', 'message', 'content', 'markdown', 'code', 'tool', 'approval'],
  },
  {
    id: 'sessionmessage',
    title: 'SessionMessage',
    page: 'chat',
    category: 'Messages',
    keywords: ['message', 'item', 'grouping', 'position', 'bubble'],
  },
  {
    id: 'stagedcontextnote',
    title: 'StagedContextNote',
    page: 'chat',
    category: 'Messages',
    keywords: ['staged', 'context', 'add', 'note', 'fold', 'next', 'reply', 'disposition'],
  },
  {
    id: 'messageauthoravatar',
    title: 'MessageAuthorAvatar',
    page: 'chat',
    category: 'Messages',
    keywords: [
      'author',
      'avatar',
      'identity',
      'agent',
      'human',
      'person',
      'system',
      'external',
      'bridged',
      'shape',
      'badge',
      'square',
      'circle',
    ],
  },
  // ToolShowcases
  {
    id: 'toolcallcard',
    title: 'ToolCallCard',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'call', 'card', 'status', 'running', 'complete', 'error', 'pending'],
  },
  {
    id: 'toolcallcard-extended-labels',
    title: 'ToolCallCard — Extended Labels',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'call', 'label', 'task', 'notebook', 'mcp', 'plan'],
  },
  {
    id: 'toolcallcard-hook-lifecycle',
    title: 'ToolCallCard — Hook Lifecycle',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'hook', 'lifecycle', 'running', 'success', 'error', 'cancelled'],
  },
  {
    id: 'subagentblock',
    title: 'SubagentBlock',
    page: 'chat',
    category: 'Tools',
    keywords: [
      'subagent',
      'agent',
      'block',
      'lifecycle',
      'spawned',
      'background',
      'task',
      'streaming',
      'text',
      'forwarded',
    ],
  },
  {
    id: 'backgroundtaskbar',
    title: 'BackgroundTaskBar',
    page: 'chat',
    category: 'Tools',
    keywords: [
      'background',
      'task',
      'bar',
      'indicator',
      'agent',
      'bash',
      'running',
      'unified',
      'expand',
      'kill',
      'stop',
    ],
  },
  {
    id: 'taskdotsection',
    title: 'TaskDotSection',
    page: 'chat',
    category: 'Tools',
    keywords: ['task', 'dot', 'bash', 'tasks', 'animation', 'background', 'running'],
  },
  {
    id: 'taskdetailpanel',
    title: 'TaskDetailPanel',
    page: 'chat',
    category: 'Tools',
    keywords: ['task', 'detail', 'panel', 'expand', 'row', 'chip', 'kill', 'stop', 'background'],
  },
  {
    id: 'inlinekillbutton',
    title: 'InlineKillButton',
    page: 'chat',
    category: 'Tools',
    keywords: ['kill', 'stop', 'button', 'inline', 'confirm', 'agent', 'bash', 'background'],
  },
  {
    id: 'errormessageblock',
    title: 'ErrorMessageBlock',
    page: 'chat',
    category: 'Tools',
    keywords: ['error', 'message', 'block', 'failure', 'category', 'execution'],
  },
  {
    id: 'thinkingblock',
    title: 'ThinkingBlock',
    page: 'chat',
    category: 'Tools',
    keywords: ['thinking', 'reasoning', 'extended', 'streaming', 'collapsed', 'chain of thought'],
  },
  {
    id: 'collapsiblerun',
    title: 'CollapsibleRun',
    page: 'chat',
    category: 'Tools',
    keywords: ['collapse', 'run', 'n more', 'steps', 'dense', 'tool', 'thinking', 'group'],
  },
  {
    id: 'approvalprompt',
    title: 'ApprovalPrompt',
    page: 'chat',
    category: 'Tools',
    keywords: ['approval', 'tool', 'approve', 'deny', 'pending', 'interactive', 'timeout'],
  },
  {
    id: 'askreceipt',
    title: 'AskReceipt',
    page: 'chat',
    category: 'Tools',
    keywords: ['receipt', 'approval', 'allowed', 'denied', 'expired', 'record', 'transcript'],
  },
  // ChipShowcases
  {
    id: 'touchchip-every-verb-live',
    title: 'TouchChip — every verb, live',
    page: 'chat',
    category: 'Chips',
    keywords: [
      'chip',
      'touch',
      'verb',
      'live',
      'animation',
      'scan',
      'beam',
      'scribble',
      'ping',
      'cursor',
      'motion',
      'reduced motion',
    ],
  },
  {
    id: 'touchchip-every-verb-settled',
    title: 'TouchChip — every verb, settled',
    page: 'chat',
    category: 'Chips',
    keywords: [
      'chip',
      'touch',
      'verb',
      'settled',
      'diffstat',
      'hits',
      'count',
      'upgrade',
      'morph',
      'glob',
      'pattern',
    ],
  },
  {
    id: 'touchchip-failures-and-tombstones',
    title: 'TouchChip — failures and tombstones',
    page: 'chat',
    category: 'Chips',
    keywords: ['chip', 'touch', 'error', 'failed', 'tombstone', 'deleted', 'destructive'],
  },
  {
    id: 'chippile-where-a-chip-goes-when-it-ages-out',
    title: 'ChipPile — where a chip goes when it ages out',
    page: 'chat',
    category: 'Chips',
    keywords: ['chip', 'pile', 'facepile', 'stack', 'absorb', 'wobble', 'count', 'overflow'],
  },
  {
    id: 'chiptray-the-full-roster',
    title: 'ChipTray — the full roster',
    page: 'chat',
    category: 'Chips',
    keywords: ['chip', 'tray', 'roster', 'filter', 'order', 'chronological', 'kind', 'disclosure'],
  },
  {
    id: 'touchchipstrip-a-turn-working-and-finished',
    title: 'TouchChipStrip — a turn, working and finished',
    page: 'chat',
    category: 'Chips',
    keywords: ['chip', 'strip', 'turn', 'summary', 'live row', 'settled', 'show all', 'touched'],
  },
  // InputShowcases
  {
    id: 'composer-root',
    title: 'Composer.Root',
    page: 'chat',
    category: 'Input',
    keywords: ['composer', 'card', 'dropzone', 'chrome', 'attach', 'drag', 'drop'],
  },
  {
    id: 'composer-input',
    title: 'Composer.Input',
    page: 'chat',
    category: 'Input',
    keywords: [
      'input',
      'textarea',
      'chat',
      'composer',
      'send',
      'streaming',
      'stop',
      'queue',
      'rich text',
      'markdown',
      'lexical',
      'formatting',
    ],
  },
  {
    id: 'composer-dispositions',
    title: 'Composer dispositions',
    page: 'chat',
    category: 'Input',
    keywords: [
      'composer',
      'queue',
      'steer',
      'add context',
      'stage',
      'disposition',
      'busy',
      'mid-turn',
      'downgrade',
      'capability',
    ],
  },
  {
    id: 'composer-attachments',
    title: 'Composer.Attachments',
    page: 'chat',
    category: 'Input',
    keywords: ['file', 'attachment', 'chip', 'upload', 'remove', 'composer'],
  },
  {
    id: 'queuepanel',
    title: 'QueuePanel',
    page: 'chat',
    category: 'Input',
    keywords: ['queue', 'message', 'panel', 'pending', 'edit'],
  },
  {
    id: 'commandpalette',
    title: 'CommandPalette',
    page: 'chat',
    category: 'Input',
    keywords: ['command', 'palette', 'slash', 'autocomplete', 'dropdown', 'namespace'],
  },
  {
    id: 'filepalette',
    title: 'FilePalette',
    page: 'chat',
    category: 'Input',
    keywords: ['file', 'palette', 'mention', 'autocomplete', 'dropdown', 'fuzzy', 'at'],
  },
  {
    id: 'questionprompt',
    title: 'QuestionPrompt',
    page: 'chat',
    category: 'Input',
    keywords: [
      'question',
      'prompt',
      'radio',
      'checkbox',
      'multi-select',
      'tabs',
      'form',
      'interactive',
    ],
  },
  // StatusShowcases
  {
    id: 'live-status-dots',
    title: 'Live status dots',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'dot',
      'working',
      'streaming',
      'needs you',
      'error',
      'unseen',
      'pulse',
      'token',
      'signal',
    ],
  },
  {
    id: 'streamingtext',
    title: 'StreamingText',
    page: 'chat',
    category: 'Status',
    keywords: ['streaming', 'text', 'markdown', 'cursor', 'render'],
  },
  {
    id: 'live-lane',
    title: 'Live lane',
    page: 'chat',
    category: 'Status',
    keywords: [
      'lane',
      'live',
      'status',
      'presence',
      'working',
      'stalled',
      'streaming',
      'queued',
      'ask',
      'compaction',
      'permission',
      'elapsed',
      'announcer',
      'reserved',
      'layout shift',
    ],
  },
  {
    id: 'live-peek',
    title: 'Live peek',
    page: 'chat',
    category: 'Status',
    keywords: [
      'peek',
      'popover',
      'sheet',
      'agents',
      'working',
      'elapsed',
      'replying to',
      'open its session',
      'stop',
      'halt',
    ],
  },
  {
    id: 'usagestatusitem',
    title: 'UsageStatusItem',
    page: 'chat',
    category: 'Status',
    keywords: [
      'usage',
      'cost',
      'subscription',
      'utilization',
      'rate limit',
      'window',
      'pay-as-you-go',
    ],
  },
  {
    id: 'transport-error-errormessageblock',
    title: 'Transport error (ErrorMessageBlock)',
    page: 'chat',
    category: 'Status',
    keywords: ['transport', 'error', 'banner', 'connection', 'retry', 'network', 'timeout'],
  },
  {
    id: 'tasklistpanel',
    title: 'TaskListPanel',
    page: 'chat',
    category: 'Status',
    keywords: ['task', 'list', 'panel', 'progress', 'collapse', 'checklist'],
  },
  // TrustDialShowcases
  {
    id: 'trust-dial-one-question-three-stops',
    title: 'Trust Dial — one question, three stops',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'permission',
      'permissions',
      'stop',
      'segmented',
      'ask',
      'act',
      'autonomy',
      'caption',
      'runtime',
      'codex',
      'divergent',
    ],
  },
  {
    id: 'trust-dial-the-awkward-states',
    title: 'Trust Dial — the awkward states',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'stranded',
      'disabled',
      'plan',
      'absent',
      'loading',
      'permission',
      'empty',
    ],
  },
  {
    id: 'trust-dial-the-door-into-a-mode-that-never-asks',
    title: 'Trust Dial — the door into a mode that never asks',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'autonomy',
      'confirm',
      'dialog',
      'consent',
      'bypass',
      'permission',
      'scope',
      'never asks',
    ],
  },
  {
    id: 'trust-dial-the-surfaces-nobody-is-watching',
    title: 'Trust Dial — the surfaces nobody is watching',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'binding',
      'integration',
      'task',
      'schedule',
      'unattended',
      'stranded',
      'keep current',
      'autonomy',
      'approver',
      'permission',
    ],
  },
  {
    id: 'trust-dial-where-new-sessions-start',
    title: 'Trust Dial — where new sessions start',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'default',
      'defaults',
      'settings',
      'new session',
      'make default',
      'stop',
      'autonomy',
      'per runtime',
      'override',
      'permission',
    ],
  },
  {
    id: 'plan-a-way-of-working-beside-the-composer',
    title: 'Plan — a way of working, beside the composer',
    page: 'chat',
    category: 'Status',
    keywords: ['plan', 'planning', 'composer', 'toggle', 'switch', 'working', 'mode'],
  },
  // StatusLineShowcases
  {
    id: 'statusline-density-tiers',
    title: 'StatusLine — density tiers',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'bar',
      'density',
      'tier',
      'budget',
      'width',
      'overflow',
      'truncate',
      'mobile',
      'responsive',
    ],
  },
  {
    id: 'statusline-promoted-set',
    title: 'StatusLine — promoted set',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'promote',
      'promotion',
      'severity',
      'quiet',
      'degraded',
      'healthy',
      'registry',
    ],
  },
  {
    id: 'statusline-what-a-pin-does',
    title: 'StatusLine — what a pin does',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'pin',
      'pins',
      'pinned',
      'quiet',
      'severity',
      'budget',
      'overflow',
      'git',
      'branch',
    ],
  },
  {
    id: 'sessionpopover',
    title: 'SessionPopover',
    page: 'chat',
    category: 'Status',
    keywords: [
      'session',
      'popover',
      'panel',
      'pin',
      'pins',
      'diagnostics',
      'copy',
      'reveal',
      'ellipsis',
      'controls',
    ],
  },
  {
    id: 'sessioninspector',
    title: 'SessionInspector',
    page: 'chat',
    category: 'Status',
    keywords: [
      'session',
      'inspector',
      'readout',
      'diagnostics',
      'right panel',
      'stream',
      'connection',
      'seq',
      'cursor',
      'cache',
      'context',
      'subagents',
    ],
  },
  {
    id: 'agentidentitychip',
    title: 'AgentIdentityChip',
    page: 'chat',
    category: 'Status',
    keywords: [
      'agent',
      'identity',
      'chip',
      'avatar',
      'anchor',
      'context menu',
      'switch agent',
      'profile',
    ],
  },
  // MiscShowcases
  {
    id: 'celebrationoverlay',
    title: 'CelebrationOverlay',
    page: 'chat',
    category: 'Misc',
    keywords: ['celebration', 'confetti', 'overlay', 'task', 'complete', 'fireworks'],
  },
];
