import type { PlaygroundSection } from '../playground-registry';

/**
 * Chat component sections from ChatPage.
 *
 * Sources: MessageShowcases, ToolShowcases, InputShowcases,
 * StatusShowcases, MiscShowcases.
 */
export const CHAT_SECTIONS: PlaygroundSection[] = [
  // MessageShowcases
  {
    id: 'permissiondeniedchip',
    title: 'PermissionDeniedChip',
    page: 'chat',
    category: 'Messages',
    keywords: ['permission', 'denied', 'chip', 'classifier', 'blocked', 'auto', 'safety', 'tool'],
  },
  {
    id: 'usermessagecontent',
    title: 'UserMessageContent',
    page: 'chat',
    category: 'Messages',
    keywords: ['user', 'message', 'content', 'text', 'command', 'compaction'],
  },
  {
    id: 'assistantmessagecontent',
    title: 'AssistantMessageContent',
    page: 'chat',
    category: 'Messages',
    keywords: ['assistant', 'message', 'content', 'markdown', 'code', 'tool', 'approval'],
  },
  {
    id: 'messageitem',
    title: 'MessageItem',
    page: 'chat',
    category: 'Messages',
    keywords: ['message', 'item', 'grouping', 'position', 'bubble'],
  },
  // ToolShowcases
  {
    id: 'toolcallcard',
    title: 'ToolCallCard',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'call', 'card', 'status', 'running', 'complete', 'error', 'pending'],
  },
  {
    id: 'toolcallcard-extended-labels',
    title: 'ToolCallCard — Extended Labels',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'call', 'label', 'task', 'notebook', 'mcp', 'plan'],
  },
  {
    id: 'toolcallcard-hook-lifecycle',
    title: 'ToolCallCard — Hook Lifecycle',
    page: 'chat',
    category: 'Tools',
    keywords: ['tool', 'hook', 'lifecycle', 'running', 'success', 'error', 'cancelled'],
  },
  {
    id: 'subagentblock',
    title: 'SubagentBlock',
    page: 'chat',
    category: 'Tools',
    keywords: [
      'subagent',
      'agent',
      'block',
      'lifecycle',
      'spawned',
      'background',
      'task',
      'streaming',
      'text',
      'forwarded',
    ],
  },
  {
    id: 'backgroundtaskbar',
    title: 'BackgroundTaskBar',
    page: 'chat',
    category: 'Tools',
    keywords: [
      'background',
      'task',
      'bar',
      'indicator',
      'agent',
      'bash',
      'running',
      'unified',
      'expand',
      'kill',
      'stop',
    ],
  },
  {
    id: 'taskdotsection',
    title: 'TaskDotSection',
    page: 'chat',
    category: 'Tools',
    keywords: ['task', 'dot', 'bash', 'tasks', 'animation', 'background', 'running'],
  },
  {
    id: 'taskdetailpanel',
    title: 'TaskDetailPanel',
    page: 'chat',
    category: 'Tools',
    keywords: ['task', 'detail', 'panel', 'expand', 'row', 'chip', 'kill', 'stop', 'background'],
  },
  {
    id: 'inlinekillbutton',
    title: 'InlineKillButton',
    page: 'chat',
    category: 'Tools',
    keywords: ['kill', 'stop', 'button', 'inline', 'confirm', 'agent', 'bash', 'background'],
  },
  {
    id: 'errormessageblock',
    title: 'ErrorMessageBlock',
    page: 'chat',
    category: 'Tools',
    keywords: ['error', 'message', 'block', 'failure', 'category', 'execution'],
  },
  {
    id: 'thinkingblock',
    title: 'ThinkingBlock',
    page: 'chat',
    category: 'Tools',
    keywords: ['thinking', 'reasoning', 'extended', 'streaming', 'collapsed', 'chain of thought'],
  },
  {
    id: 'collapsiblerun',
    title: 'CollapsibleRun',
    page: 'chat',
    category: 'Tools',
    keywords: ['collapse', 'run', 'n more', 'steps', 'dense', 'tool', 'thinking', 'group'],
  },
  {
    id: 'toolapproval',
    title: 'ToolApproval',
    page: 'chat',
    category: 'Tools',
    keywords: ['approval', 'tool', 'approve', 'deny', 'pending', 'interactive', 'timeout'],
  },
  {
    id: 'approvalreceipt',
    title: 'ApprovalReceipt',
    page: 'chat',
    category: 'Tools',
    keywords: ['receipt', 'approval', 'allowed', 'denied', 'expired', 'record', 'transcript'],
  },
  // InputShowcases
  {
    id: 'chatinput',
    title: 'ChatInput',
    page: 'chat',
    category: 'Input',
    keywords: ['input', 'textarea', 'chat', 'send', 'streaming', 'stop', 'queue'],
  },
  {
    id: 'filechipbar',
    title: 'FileChipBar',
    page: 'chat',
    category: 'Input',
    keywords: ['file', 'attachment', 'chip', 'upload', 'remove'],
  },
  {
    id: 'queuepanel',
    title: 'QueuePanel',
    page: 'chat',
    category: 'Input',
    keywords: ['queue', 'message', 'panel', 'pending', 'edit'],
  },
  {
    id: 'commandpalette',
    title: 'CommandPalette',
    page: 'chat',
    category: 'Input',
    keywords: ['command', 'palette', 'slash', 'autocomplete', 'dropdown', 'namespace'],
  },
  {
    id: 'filepalette',
    title: 'FilePalette',
    page: 'chat',
    category: 'Input',
    keywords: ['file', 'palette', 'mention', 'autocomplete', 'dropdown', 'fuzzy', 'at'],
  },
  {
    id: 'promptsuggestionchips',
    title: 'PromptSuggestionChips',
    page: 'chat',
    category: 'Input',
    keywords: ['prompt', 'suggestion', 'chip', 'follow-up', 'sdk', 'autocomplete'],
  },
  {
    id: 'questionprompt',
    title: 'QuestionPrompt',
    page: 'chat',
    category: 'Input',
    keywords: [
      'question',
      'prompt',
      'radio',
      'checkbox',
      'multi-select',
      'tabs',
      'form',
      'interactive',
    ],
  },
  // StatusShowcases
  {
    id: 'streamingtext',
    title: 'StreamingText',
    page: 'chat',
    category: 'Status',
    keywords: ['streaming', 'text', 'markdown', 'cursor', 'render'],
  },
  {
    id: 'chatstatusstrip',
    title: 'ChatStatusStrip',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'strip',
      'streaming',
      'waiting',
      'rate limit',
      'system',
      'inference',
      'indicator',
      'compaction',
      'permission',
      'ephemeral',
      'timer',
      'complete',
    ],
  },
  {
    id: 'usagestatusitem',
    title: 'UsageStatusItem',
    page: 'chat',
    category: 'Status',
    keywords: [
      'usage',
      'cost',
      'subscription',
      'utilization',
      'rate limit',
      'window',
      'pay-as-you-go',
    ],
  },
  {
    id: 'transporterrorbanner',
    title: 'TransportErrorBanner',
    page: 'chat',
    category: 'Status',
    keywords: [
      'transport',
      'error',
      'banner',
      'connection',
      'retry',
      'network',
      'timeout',
      'session lock',
    ],
  },
  {
    id: 'tasklistpanel',
    title: 'TaskListPanel',
    page: 'chat',
    category: 'Status',
    keywords: ['task', 'list', 'panel', 'progress', 'collapse', 'checklist'],
  },
  // TrustDialShowcases
  {
    id: 'trust-dial-one-question-three-stops',
    title: 'Trust Dial — one question, three stops',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'permission',
      'permissions',
      'stop',
      'segmented',
      'ask',
      'act',
      'autonomy',
      'caption',
      'runtime',
      'codex',
      'divergent',
    ],
  },
  {
    id: 'trust-dial-the-awkward-states',
    title: 'Trust Dial — the awkward states',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'stranded',
      'disabled',
      'plan',
      'absent',
      'loading',
      'permission',
      'empty',
    ],
  },
  {
    id: 'trust-dial-the-door-into-full-autonomy',
    title: 'Trust Dial — the door into Full autonomy',
    page: 'chat',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'autonomy',
      'confirm',
      'dialog',
      'consent',
      'bypass',
      'permission',
      'scope',
    ],
  },
  {
    id: 'plan-a-way-of-working-beside-the-composer',
    title: 'Plan — a way of working, beside the composer',
    page: 'chat',
    category: 'Status',
    keywords: ['plan', 'planning', 'composer', 'toggle', 'switch', 'working', 'mode'],
  },
  // StatusLineShowcases
  {
    id: 'statusline-density-tiers',
    title: 'StatusLine — density tiers',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'bar',
      'density',
      'tier',
      'budget',
      'width',
      'overflow',
      'truncate',
      'mobile',
      'responsive',
    ],
  },
  {
    id: 'statusline-promoted-set',
    title: 'StatusLine — promoted set',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'promote',
      'promotion',
      'severity',
      'quiet',
      'degraded',
      'healthy',
      'registry',
    ],
  },
  {
    id: 'statusline-what-a-pin-does',
    title: 'StatusLine — what a pin does',
    page: 'chat',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'pin',
      'pins',
      'pinned',
      'quiet',
      'severity',
      'budget',
      'overflow',
      'git',
      'branch',
    ],
  },
  {
    id: 'sessionpopover',
    title: 'SessionPopover',
    page: 'chat',
    category: 'Status',
    keywords: [
      'session',
      'popover',
      'panel',
      'pin',
      'pins',
      'diagnostics',
      'copy',
      'reveal',
      'ellipsis',
      'controls',
    ],
  },
  {
    id: 'sessioninspector',
    title: 'SessionInspector',
    page: 'chat',
    category: 'Status',
    keywords: [
      'session',
      'inspector',
      'readout',
      'diagnostics',
      'right panel',
      'stream',
      'connection',
      'seq',
      'cursor',
      'cache',
      'context',
      'subagents',
    ],
  },
  {
    id: 'agentidentitychip',
    title: 'AgentIdentityChip',
    page: 'chat',
    category: 'Status',
    keywords: [
      'agent',
      'identity',
      'chip',
      'avatar',
      'anchor',
      'context menu',
      'switch agent',
      'profile',
    ],
  },
  // MiscShowcases
  {
    id: 'celebrationoverlay',
    title: 'CelebrationOverlay',
    page: 'chat',
    category: 'Misc',
    keywords: ['celebration', 'confetti', 'overlay', 'task', 'complete', 'fireworks'],
  },
];
