import type { PlaygroundSection } from '../playground-registry';

/**
 * Component sections from ComponentsPage.
 *
 * Sources: LayoutShowcases, ButtonShowcases, FeedbackShowcases,
 * NavigationShowcases, SidebarShowcases, OverlayShowcases, DataDisplayShowcases.
 */
export const COMPONENTS_SECTIONS: PlaygroundSection[] = [
  // LayoutShowcases
  {
    id: 'pagecontainer',
    title: 'PageContainer',
    page: 'components',
    category: 'Layout',
    keywords: [
      'page',
      'container',
      'width',
      'max-width',
      'wide',
      'reading',
      'full',
      'gutter',
      'scroll',
      'layout',
      'centered',
    ],
  },
  // ButtonShowcases
  {
    id: 'button',
    title: 'Button',
    page: 'components',
    category: 'Buttons',
    keywords: [
      'btn',
      'click',
      'action',
      'variant',
      'destructive',
      'ghost',
      'outline',
      'brand',
      'link',
    ],
  },
  {
    id: 'badge',
    title: 'Badge',
    page: 'components',
    category: 'Buttons',
    keywords: ['label', 'tag', 'chip', 'status', 'pill'],
  },
  {
    id: 'hoverbordergradient',
    title: 'HoverBorderGradient',
    page: 'components',
    category: 'Buttons',
    keywords: ['gradient', 'animated', 'border', 'hover', 'aceternity'],
  },
  {
    id: 'kbd',
    title: 'Kbd',
    page: 'components',
    category: 'Buttons',
    keywords: ['keyboard', 'shortcut', 'key', 'hotkey', 'hint'],
  },
  {
    id: 'inlinecode',
    title: 'InlineCode',
    page: 'components',
    category: 'Buttons',
    keywords: ['code', 'command', 'mono', 'monospace', 'snippet', 'path'],
  },
  // FeedbackShowcases
  {
    id: 'feedback-dialog',
    title: 'Feedback dialog',
    page: 'components',
    category: 'Feedback',
    keywords: ['feedback', 'bug', 'report', 'idea', 'praise', 'diagnostics', 'attachments'],
  },
  {
    id: 'skeleton',
    title: 'Skeleton',
    page: 'components',
    category: 'Feedback',
    keywords: ['loading', 'placeholder', 'tasks', 'shimmer', 'spinner'],
  },
  {
    id: 'separator',
    title: 'Separator',
    page: 'components',
    category: 'Feedback',
    keywords: ['divider', 'line', 'horizontal', 'vertical', 'hr'],
  },
  {
    id: 'tooltip',
    title: 'Tooltip',
    page: 'components',
    category: 'Feedback',
    keywords: ['hover', 'popover', 'hint', 'label', 'info'],
  },
  {
    id: 'hovercard',
    title: 'HoverCard',
    page: 'components',
    category: 'Feedback',
    keywords: ['hover', 'card', 'preview', 'popover', 'trigger'],
  },
  {
    id: 'collapsible',
    title: 'Collapsible',
    page: 'components',
    category: 'Feedback',
    keywords: ['collapse', 'expand', 'toggle', 'accordion', 'disclosure'],
  },
  {
    id: 'toaster',
    title: 'Toaster',
    page: 'components',
    category: 'Feedback',
    keywords: ['toast', 'notification', 'sonner', 'success', 'error', 'info', 'warning'],
  },
  {
    id: 'banner',
    title: 'Banner',
    page: 'components',
    category: 'Feedback',
    keywords: ['banner', 'alert', 'notice', 'critical', 'warning', 'info', 'neutral', 'dismiss'],
  },
  // NavigationShowcases
  {
    id: 'navigationlayout',
    title: 'NavigationLayout',
    page: 'components',
    category: 'Navigation',
    keywords: ['nav', 'sidebar', 'settings', 'panel', 'layout', 'menu', 'item'],
  },
  {
    id: 'apptabstrip',
    title: 'AppTabStrip',
    page: 'components',
    category: 'Navigation',
    keywords: ['tab', 'tabs', 'strip', 'window', 'titlebar', 'close', 'new tab', 'session'],
  },
  // SidebarShowcases
  {
    id: 'sidebarrow',
    title: 'SidebarRow',
    page: 'components',
    category: 'Sidebar',
    keywords: [
      'sidebar',
      'row',
      'gutter',
      'trailing',
      'trailing action',
      'satellite',
      'truncate',
      'ellipsis',
      'chip',
      'kebab',
      'drag',
    ],
  },
  {
    id: 'sessionrow',
    title: 'SessionRow',
    page: 'components',
    category: 'Sidebar',
    keywords: [
      'session',
      'row',
      'active',
      'permission',
      'expand',
      'entrance',
      'compact',
      'dot',
      'variant',
    ],
  },
  {
    id: 'sessionsview',
    title: 'SessionsView',
    page: 'components',
    category: 'Sidebar',
    keywords: ['session', 'list', 'group', 'today', 'yesterday', 'empty', 'scroll'],
  },
  {
    id: 'sidebarfooterstrip',
    title: 'SidebarFooterStrip',
    page: 'components',
    category: 'Sidebar',
    keywords: ['footer', 'strip', 'sidebar', 'ask dorkbot', 'update', 'pill', 'navigation'],
  },
  // VerbLadderShowcases
  {
    id: 'verb-ladder-and-signals',
    title: 'Verb ladder & signals',
    page: 'components',
    category: 'Sidebar',
    keywords: [
      'verb',
      'ladder',
      'activity',
      'working',
      'waiting on you',
      'honesty',
      'status',
      'dot',
      'signal',
      'welcome back',
      'glow',
      'sidebar',
      'row',
      'second line',
    ],
  },
  // OverlayShowcases
  {
    id: 'dialog',
    title: 'Dialog',
    page: 'components',
    category: 'Overlays',
    keywords: ['modal', 'overlay', 'popup', 'confirm', 'alert'],
  },
  {
    id: 'alertdialog',
    title: 'AlertDialog',
    page: 'components',
    category: 'Overlays',
    keywords: ['modal', 'confirm', 'destructive', 'delete', 'danger', 'alert'],
  },
  {
    id: 'popover',
    title: 'Popover',
    page: 'components',
    category: 'Overlays',
    keywords: ['floating', 'overlay', 'panel', 'anchor', 'tooltip'],
  },
  {
    id: 'dropdownmenu',
    title: 'DropdownMenu',
    page: 'components',
    category: 'Overlays',
    keywords: ['menu', 'context', 'dropdown', 'action', 'item'],
  },
  {
    id: 'sheet',
    title: 'Sheet',
    page: 'components',
    category: 'Overlays',
    keywords: ['sheet', 'panel', 'slide', 'side', 'drawer', 'left', 'right'],
  },
  {
    id: 'responsivesheet',
    title: 'ResponsiveSheet',
    page: 'components',
    category: 'Overlays',
    keywords: [
      'responsive',
      'sheet',
      'panel',
      'drawer',
      'mobile',
      'desktop',
      'fullscreen',
      'right',
    ],
  },
  {
    id: 'responsivedialog',
    title: 'ResponsiveDialog',
    page: 'components',
    category: 'Overlays',
    keywords: ['responsive', 'dialog', 'drawer', 'mobile', 'desktop', 'fullscreen'],
  },
  // DrawerShowcases
  {
    id: 'drawer',
    title: 'Drawer',
    page: 'components',
    category: 'Overlays',
    keywords: ['drawer', 'bottom', 'sheet', 'slide', 'panel', 'vaul', 'mobile'],
  },
  // DataDisplayShowcases
  {
    id: 'pathbreadcrumb',
    title: 'PathBreadcrumb',
    page: 'components',
    category: 'Data Display',
    keywords: ['path', 'breadcrumb', 'filesystem', 'directory', 'segment', 'truncate'],
  },
  {
    id: 'scanline',
    title: 'ScanLine',
    page: 'components',
    category: 'Data Display',
    keywords: ['scan', 'line', 'animation', 'streaming', 'beam', 'glow', 'agent'],
  },
  {
    id: 'markdowncontent',
    title: 'MarkdownContent',
    page: 'components',
    category: 'Data Display',
    keywords: ['markdown', 'prose', 'render', 'static', 'streamdown', 'content'],
  },
  {
    id: 'featuredisabledstate',
    title: 'FeatureDisabledState',
    page: 'components',
    category: 'Data Display',
    keywords: ['feature', 'disabled', 'empty', 'state', 'placeholder', 'subsystem'],
  },
  {
    id: 'scrollarea',
    title: 'ScrollArea',
    page: 'components',
    category: 'Data Display',
    keywords: ['scroll', 'area', 'overflow', 'scrollbar', 'custom', 'vertical', 'horizontal'],
  },
  {
    id: 'identityavatar',
    title: 'IdentityAvatar',
    page: 'components',
    category: 'Data Display',
    keywords: [
      'avatar',
      'identity',
      'emoji',
      'initial',
      'color',
      'tint',
      'fill',
      'shape',
      'circle',
      'square',
      'disc',
      'agent',
      'room',
      'photo',
      'image',
      'picture',
    ],
  },
  {
    id: 'mentionpill',
    title: 'MentionPill',
    page: 'components',
    category: 'Data Display',
    keywords: [
      'mention',
      'pill',
      'at',
      '@',
      'agent',
      'human',
      'external',
      'system',
      'unresolved',
      'bot',
      'platform',
      'wrap',
    ],
  },
  {
    id: 'identityhovercard',
    title: 'IdentityHoverCard',
    page: 'components',
    category: 'Data Display',
    keywords: [
      'identity',
      'hover',
      'card',
      'profile',
      'handle',
      'chip',
      'working',
      'runtime',
      'model',
      'origin',
    ],
  },
  {
    id: 'a-mention-in-a-real-message',
    title: 'A mention in a real message',
    page: 'components',
    category: 'Data Display',
    keywords: [
      'mention',
      'identity',
      'hover',
      'card',
      'agent',
      'runtime',
      'model',
      'roster',
      'room',
      'entry',
    ],
  },
  // ChatPrimitivesShowcases
  {
    id: 'collapsiblecard',
    title: 'CollapsibleCard',
    page: 'components',
    category: 'Chat Primitives',
    keywords: ['collapsible', 'card', 'expand', 'collapse', 'thinking', 'chevron'],
  },
  {
    id: 'interactivecard',
    title: 'InteractiveCard',
    page: 'components',
    category: 'Chat Primitives',
    keywords: ['interactive', 'card', 'active', 'resolved', 'focus', 'ring'],
  },
  {
    id: 'optionrow',
    title: 'OptionRow',
    page: 'components',
    category: 'Chat Primitives',
    keywords: ['option', 'row', 'radio', 'selected', 'focused', 'choice'],
  },
  {
    id: 'compactpendingrow',
    title: 'CompactPendingRow',
    page: 'components',
    category: 'Chat Primitives',
    keywords: ['compact', 'pending', 'row', 'approval', 'question', 'waiting'],
  },
  {
    id: 'compactresultrow',
    title: 'CompactResultRow',
    page: 'components',
    category: 'Chat Primitives',
    keywords: ['compact', 'result', 'row', 'approved', 'denied', 'badge', 'icon'],
  },
  // PromptSuggestionChipsShowcases
  {
    id: 'promptsuggestionchips',
    title: 'PromptSuggestionChips',
    page: 'components',
    category: 'Feedback',
    keywords: [
      'prompt',
      'suggestion',
      'chip',
      'follow-up',
      'sdk',
      'starter',
      'openers',
      'day one',
      'compact',
      'comfortable',
    ],
  },
];
