import type { PlaygroundSection } from '../playground-registry';

/**
 * Conversation component sections from ConversationPage.
 *
 * Sources: SurfacesShowcases, MessageShowcases, TimelineShowcases,
 * ToolShowcases, AsksShowcases, ComposerShowcases, StatusShowcases,
 * MiscShowcases.
 */
export const CONVERSATION_SECTIONS: PlaygroundSection[] = [
  // SurfacesShowcases — session, room and DM side by side from one fixture
  // (DOR-1332, P5).
  {
    id: 'surfaces',
    title: 'Surfaces',
    page: 'conversation',
    category: 'Messages',
    keywords: [
      'surfaces',
      'session',
      'room',
      'dm',
      'direct message',
      'side by side',
      'capabilities',
      'unification',
      'fixture',
    ],
  },
  // MessageShowcases
  {
    id: 'message-row',
    title: 'Message row',
    page: 'conversation',
    category: 'Messages',
    keywords: [
      'message',
      'row',
      'conversation',
      'capabilities',
      'anchor',
      'rail',
      'corner',
      'density',
      'compact',
      'reactions',
      'run with',
      'shared',
    ],
  },
  {
    id: 'conversation-dividers',
    title: 'Conversation dividers',
    page: 'conversation',
    category: 'Messages',
    keywords: ['divider', 'day', 'unread', 'new messages', 'separator', 'rule', 'boundary'],
  },
  // TimelineShowcases (DOR-1332, P5)
  {
    id: 'timeline',
    title: 'Timeline',
    page: 'conversation',
    category: 'Messages',
    keywords: [
      'timeline',
      'virtualized',
      'virtualization',
      'scroller',
      'feed',
      'loading',
      'empty',
      'grouping',
      'pending',
      'thread',
      'long run',
    ],
  },
  {
    id: 'permissiondeniedchip',
    title: 'PermissionDeniedChip',
    page: 'conversation',
    category: 'Messages',
    keywords: ['permission', 'denied', 'chip', 'classifier', 'blocked', 'auto', 'safety', 'tool'],
  },
  {
    id: 'usermessagecontent',
    title: 'UserMessageContent',
    page: 'conversation',
    category: 'Messages',
    keywords: ['user', 'message', 'content', 'text', 'command', 'compaction'],
  },
  {
    id: 'assistantmessagecontent',
    title: 'AssistantMessageContent',
    page: 'conversation',
    category: 'Messages',
    keywords: ['assistant', 'message', 'content', 'markdown', 'code', 'tool', 'approval'],
  },
  {
    id: 'sessionmessage',
    title: 'SessionMessage',
    page: 'conversation',
    category: 'Messages',
    keywords: ['message', 'item', 'grouping', 'position', 'bubble'],
  },
  {
    id: 'stagedcontextnote',
    title: 'StagedContextNote',
    page: 'conversation',
    category: 'Messages',
    keywords: ['staged', 'context', 'add', 'note', 'fold', 'next', 'reply', 'disposition'],
  },
  {
    id: 'messageimage',
    title: 'MessageImage',
    page: 'conversation',
    category: 'Messages',
    keywords: ['image', 'picture', 'attachment', 'media', 'generated', 'screenshot', 'png'],
  },
  {
    id: 'messageauthoravatar',
    title: 'MessageAuthorAvatar',
    page: 'conversation',
    category: 'Messages',
    keywords: [
      'author',
      'avatar',
      'identity',
      'agent',
      'human',
      'person',
      'system',
      'external',
      'bridged',
      'shape',
      'badge',
      'square',
      'circle',
    ],
  },
  // ToolShowcases
  {
    id: 'toolcallcard',
    title: 'ToolCallCard',
    page: 'conversation',
    category: 'Tools',
    keywords: ['tool', 'call', 'card', 'status', 'running', 'complete', 'error', 'pending'],
  },
  {
    id: 'toolcallcard-extended-labels',
    title: 'ToolCallCard — Extended Labels',
    page: 'conversation',
    category: 'Tools',
    keywords: ['tool', 'call', 'label', 'task', 'notebook', 'mcp', 'plan'],
  },
  {
    id: 'toolcallcard-hook-lifecycle',
    title: 'ToolCallCard — Hook Lifecycle',
    page: 'conversation',
    category: 'Tools',
    keywords: ['tool', 'hook', 'lifecycle', 'running', 'success', 'error', 'cancelled'],
  },
  {
    id: 'subagentblock',
    title: 'SubagentBlock',
    page: 'conversation',
    category: 'Tools',
    keywords: [
      'subagent',
      'agent',
      'block',
      'lifecycle',
      'spawned',
      'background',
      'task',
      'streaming',
      'text',
      'forwarded',
    ],
  },
  {
    id: 'backgroundtaskbar',
    title: 'BackgroundTaskBar',
    page: 'conversation',
    category: 'Tools',
    keywords: [
      'background',
      'task',
      'bar',
      'indicator',
      'agent',
      'bash',
      'running',
      'unified',
      'expand',
      'kill',
      'stop',
    ],
  },
  {
    id: 'taskdotsection',
    title: 'TaskDotSection',
    page: 'conversation',
    category: 'Tools',
    keywords: ['task', 'dot', 'bash', 'tasks', 'animation', 'background', 'running'],
  },
  {
    id: 'taskdetailpanel',
    title: 'TaskDetailPanel',
    page: 'conversation',
    category: 'Tools',
    keywords: ['task', 'detail', 'panel', 'expand', 'row', 'chip', 'kill', 'stop', 'background'],
  },
  {
    id: 'inlinekillbutton',
    title: 'InlineKillButton',
    page: 'conversation',
    category: 'Tools',
    keywords: ['kill', 'stop', 'button', 'inline', 'confirm', 'agent', 'bash', 'background'],
  },
  {
    id: 'errormessageblock',
    title: 'ErrorMessageBlock',
    page: 'conversation',
    category: 'Tools',
    keywords: ['error', 'message', 'block', 'failure', 'category', 'execution'],
  },
  {
    id: 'thinkingblock',
    title: 'ThinkingBlock',
    page: 'conversation',
    category: 'Tools',
    keywords: ['thinking', 'reasoning', 'extended', 'streaming', 'collapsed', 'chain of thought'],
  },
  {
    id: 'collapsiblerun',
    title: 'CollapsibleRun',
    page: 'conversation',
    category: 'Tools',
    keywords: ['collapse', 'run', 'n more', 'steps', 'dense', 'tool', 'thinking', 'group'],
  },
  // AsksShowcases — the whole card family in one section (DOR-1332, P5):
  // AskCard.* in three kinds, AskStack, AskList, the countdown, five receipt
  // lines, the inline ApprovalPrompt and the transcript AskReceipt. The
  // capability-approval card is cross-listed onto the PAGE (see
  // CONVERSATION_CROSS_LISTED), not folded into this entry.
  {
    id: 'asks',
    title: 'Asks',
    page: 'conversation',
    category: 'Tools',
    keywords: [
      'ask',
      'asks',
      'prompt',
      'approval',
      'question',
      'elicitation',
      'answer',
      'card',
      'countdown',
      'timeout',
      'parked',
      'waiting for you',
      'urgent',
      'warning',
      'burst',
      'stack',
      'allow all',
      'deny all',
      'receipt',
      'answered',
      'expired',
      'cancelled',
      'tray',
      'waiting on you',
      'nothing needs you',
      'header',
      'pill',
      'capability',
    ],
  },
  // ChipShowcases
  {
    id: 'touchchip-every-verb-live',
    title: 'TouchChip — every verb, live',
    page: 'conversation',
    category: 'Chips',
    keywords: [
      'chip',
      'touch',
      'verb',
      'live',
      'animation',
      'scan',
      'beam',
      'scribble',
      'ping',
      'cursor',
      'motion',
      'reduced motion',
    ],
  },
  {
    id: 'touchchip-every-verb-settled',
    title: 'TouchChip — every verb, settled',
    page: 'conversation',
    category: 'Chips',
    keywords: [
      'chip',
      'touch',
      'verb',
      'settled',
      'diffstat',
      'hits',
      'count',
      'upgrade',
      'morph',
      'glob',
      'pattern',
    ],
  },
  {
    id: 'touchchip-failures-and-tombstones',
    title: 'TouchChip — failures and tombstones',
    page: 'conversation',
    category: 'Chips',
    keywords: ['chip', 'touch', 'error', 'failed', 'tombstone', 'deleted', 'destructive'],
  },
  {
    id: 'chippile-where-a-chip-goes-when-it-ages-out',
    title: 'ChipPile — where a chip goes when it ages out',
    page: 'conversation',
    category: 'Chips',
    keywords: ['chip', 'pile', 'facepile', 'stack', 'absorb', 'wobble', 'count', 'overflow'],
  },
  {
    id: 'chiptray-the-full-roster',
    title: 'ChipTray — the full roster',
    page: 'conversation',
    category: 'Chips',
    keywords: ['chip', 'tray', 'roster', 'filter', 'order', 'chronological', 'kind', 'disclosure'],
  },
  {
    id: 'touchchipstrip-a-turn-working-and-finished',
    title: 'TouchChipStrip — a turn, working and finished',
    page: 'conversation',
    category: 'Chips',
    keywords: ['chip', 'strip', 'turn', 'summary', 'live row', 'settled', 'show all', 'touched'],
  },
  // ComposerShowcases (replaces InputShowcases, DOR-1332 P5) — the one host,
  // benched against both ConversationTarget adapters.
  {
    id: 'composer',
    title: 'Composer',
    page: 'conversation',
    category: 'Input',
    keywords: [
      'composer',
      'conversation.composer',
      'card',
      'target',
      'adapter',
      'idle',
      'typing',
      'attachments',
      'attach',
      'drag',
      'drop',
      'mentions',
      'queue',
      'steer',
      'add context',
      'ask',
      'takeover',
      'archived',
      'cansend',
      'canSend',
      'rich text',
      'streaming',
      'stop',
    ],
  },
  {
    id: 'commandpalette',
    title: 'CommandPalette',
    page: 'conversation',
    category: 'Input',
    keywords: ['command', 'palette', 'slash', 'autocomplete', 'dropdown', 'namespace'],
  },
  {
    id: 'questionprompt',
    title: 'QuestionPrompt',
    page: 'conversation',
    category: 'Input',
    keywords: [
      'question',
      'prompt',
      'radio',
      'checkbox',
      'multi-select',
      'tabs',
      'form',
      'interactive',
    ],
  },
  // StatusShowcases
  {
    id: 'live-status-dots',
    title: 'Live status dots',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'status',
      'dot',
      'working',
      'streaming',
      'needs you',
      'error',
      'unseen',
      'pulse',
      'token',
      'signal',
    ],
  },
  {
    id: 'streamingtext',
    title: 'StreamingText',
    page: 'conversation',
    category: 'Status',
    keywords: ['streaming', 'text', 'markdown', 'cursor', 'render'],
  },
  {
    id: 'live-lane',
    title: 'Live lane',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'lane',
      'live',
      'status',
      'presence',
      'working',
      'stalled',
      'streaming',
      'ask',
      'receipt',
      'compaction',
      'permission',
      'elapsed',
      'announcer',
      'reserved',
      'layout shift',
    ],
  },
  {
    id: 'live-peek',
    title: 'Live peek',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'peek',
      'popover',
      'sheet',
      'agents',
      'working',
      'elapsed',
      'replying to',
      'open its session',
      'stop',
      'halt',
    ],
  },
  {
    id: 'usagestatusitem',
    title: 'UsageStatusItem',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'usage',
      'cost',
      'subscription',
      'utilization',
      'rate limit',
      'window',
      'pay-as-you-go',
    ],
  },
  {
    id: 'transport-error-errormessageblock',
    title: 'Transport error (ErrorMessageBlock)',
    page: 'conversation',
    category: 'Status',
    keywords: ['transport', 'error', 'banner', 'connection', 'retry', 'network', 'timeout'],
  },
  {
    id: 'tasklistpanel',
    title: 'TaskListPanel',
    page: 'conversation',
    category: 'Status',
    keywords: ['task', 'list', 'panel', 'progress', 'collapse', 'checklist'],
  },
  // TrustDialShowcases
  {
    id: 'trust-dial-one-question-three-stops',
    title: 'Trust Dial — one question, three stops',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'permission',
      'permissions',
      'stop',
      'segmented',
      'ask',
      'act',
      'autonomy',
      'caption',
      'runtime',
      'codex',
      'divergent',
    ],
  },
  {
    id: 'trust-dial-the-awkward-states',
    title: 'Trust Dial — the awkward states',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'stranded',
      'disabled',
      'plan',
      'absent',
      'loading',
      'permission',
      'empty',
    ],
  },
  {
    id: 'trust-dial-the-door-into-a-mode-that-never-asks',
    title: 'Trust Dial — the door into a mode that never asks',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'autonomy',
      'confirm',
      'dialog',
      'consent',
      'bypass',
      'permission',
      'scope',
      'never asks',
    ],
  },
  {
    id: 'trust-dial-the-surfaces-nobody-is-watching',
    title: 'Trust Dial — the surfaces nobody is watching',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'binding',
      'integration',
      'task',
      'schedule',
      'unattended',
      'stranded',
      'keep current',
      'autonomy',
      'approver',
      'permission',
    ],
  },
  {
    id: 'trust-dial-where-new-sessions-start',
    title: 'Trust Dial — where new sessions start',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'trust',
      'dial',
      'default',
      'defaults',
      'settings',
      'new session',
      'make default',
      'stop',
      'autonomy',
      'per runtime',
      'override',
      'permission',
    ],
  },
  {
    id: 'plan-a-way-of-working-beside-the-composer',
    title: 'Plan — a way of working, beside the composer',
    page: 'conversation',
    category: 'Status',
    keywords: ['plan', 'planning', 'composer', 'toggle', 'switch', 'working', 'mode'],
  },
  // StatusLineShowcases
  {
    id: 'statusline-density-tiers',
    title: 'StatusLine — density tiers',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'bar',
      'density',
      'tier',
      'budget',
      'width',
      'overflow',
      'truncate',
      'mobile',
      'responsive',
    ],
  },
  {
    id: 'statusline-promoted-set',
    title: 'StatusLine — promoted set',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'promote',
      'promotion',
      'severity',
      'quiet',
      'degraded',
      'healthy',
      'registry',
    ],
  },
  {
    id: 'statusline-what-a-pin-does',
    title: 'StatusLine — what a pin does',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'status',
      'line',
      'pin',
      'pins',
      'pinned',
      'quiet',
      'severity',
      'budget',
      'overflow',
      'git',
      'branch',
    ],
  },
  {
    id: 'sessionpopover',
    title: 'SessionPopover',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'session',
      'popover',
      'panel',
      'pin',
      'pins',
      'diagnostics',
      'copy',
      'reveal',
      'ellipsis',
      'controls',
    ],
  },
  {
    id: 'sessioninspector',
    title: 'SessionInspector',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'session',
      'inspector',
      'readout',
      'diagnostics',
      'right panel',
      'stream',
      'connection',
      'seq',
      'cursor',
      'cache',
      'context',
      'subagents',
    ],
  },
  {
    id: 'agentidentitychip',
    title: 'AgentIdentityChip',
    page: 'conversation',
    category: 'Status',
    keywords: [
      'agent',
      'identity',
      'chip',
      'avatar',
      'anchor',
      'context menu',
      'switch agent',
      'profile',
    ],
  },
  // MiscShowcases
  {
    id: 'celebrationoverlay',
    title: 'CelebrationOverlay',
    page: 'conversation',
    category: 'Misc',
    keywords: ['celebration', 'confetti', 'overlay', 'task', 'complete', 'fireworks'],
  },
];
