import type { PlaygroundSection } from '../playground-registry';

/**
 * Feature component sections from FeaturesPage.
 *
 * Identity lives on its own page now (`identity-sections.ts`, spec
 * `identity-consistency` §W4) — the agent avatar, the team roster, the profile
 * surfaces and the account menu all moved there, so what is left here is the
 * subsystems the page is named for.
 *
 * Sources: PersonalityPickerShowcases, AgentSidebarShowcases, AgentFleetShowcases,
 * RelayShowcases, AdapterWizardShowcases, MeshShowcases, TasksShowcases,
 * PipPanelShowcases, ApprovalsShowcases, ConnectionsShowcases, McpServerCardShowcases.
 */
export const FEATURES_SECTIONS: PlaygroundSection[] = [
  // PersonalityPickerShowcases
  {
    id: 'personalitypicker',
    title: 'PersonalityPicker',
    page: 'features',
    category: 'Agent',
    keywords: [
      'personality',
      'picker',
      'radar',
      'preset',
      'traits',
      'nebula',
      'archetype',
      'slider',
    ],
  },
  // AgentFleetShowcases
  {
    id: 'agentfleettable',
    title: 'AgentFleetTable',
    page: 'features',
    category: 'Agent',
    keywords: [
      'agent',
      'fleet',
      'table',
      'attention',
      'needs you',
      'working',
      'quiet',
      'activity',
      'scheduled',
      'group',
    ],
  },
  // RelayShowcases
  {
    id: 'catalogcard',
    title: 'CatalogCard',
    page: 'features',
    category: 'Relay',
    keywords: ['catalog', 'card', 'adapter', 'manifest', 'add', 'relay'],
  },
  {
    id: 'connectionstatusbanner',
    title: 'ConnectionStatusBanner',
    page: 'features',
    category: 'Relay',
    keywords: ['connection', 'status', 'banner', 'disconnected', 'reconnecting', 'relay'],
  },
  {
    id: 'relayemptystate',
    title: 'RelayEmptyState',
    page: 'features',
    category: 'Relay',
    keywords: ['relay', 'empty', 'state', 'adapter', 'onboarding'],
  },
  // AdapterWizardShowcases
  {
    id: 'stepindicator',
    title: 'StepIndicator',
    page: 'features',
    category: 'Relay',
    keywords: ['step', 'indicator', 'wizard', 'progress', 'stepper', 'relay'],
  },
  {
    id: 'configurestep',
    title: 'ConfigureStep',
    page: 'features',
    category: 'Relay',
    keywords: ['configure', 'step', 'wizard', 'form', 'adapter', 'relay'],
  },
  {
    id: 'configfieldinput',
    title: 'ConfigFieldInput',
    page: 'features',
    category: 'Relay',
    keywords: ['config', 'field', 'input', 'form', 'password', 'select', 'boolean', 'relay'],
  },
  {
    id: 'configfieldinput-error-states',
    title: 'ConfigFieldInput — Error States',
    page: 'features',
    category: 'Relay',
    keywords: ['config', 'field', 'input', 'error', 'validation', 'form', 'relay'],
  },
  {
    id: 'teststep',
    title: 'TestStep',
    page: 'features',
    category: 'Relay',
    keywords: ['test', 'step', 'wizard', 'connection', 'pending', 'success', 'error', 'relay'],
  },
  {
    id: 'confirmstep',
    title: 'ConfirmStep',
    page: 'features',
    category: 'Relay',
    keywords: ['confirm', 'step', 'wizard', 'summary', 'review', 'mask', 'relay'],
  },
  {
    id: 'agentstep',
    title: 'AgentStep',
    page: 'features',
    category: 'Relay',
    keywords: ['agent', 'step', 'wizard', 'answer', 'routing', 'session', 'memory', 'relay'],
  },
  {
    id: 'setupguidesheet',
    title: 'SetupGuideSheet',
    page: 'features',
    category: 'Relay',
    keywords: ['setup', 'guide', 'sheet', 'markdown', 'instructions', 'relay'],
  },
  {
    id: 'adapterbindingrow',
    title: 'AdapterBindingRow',
    page: 'features',
    category: 'Relay',
    keywords: ['adapter', 'binding', 'row', 'agent', 'permission', 'strategy', 'relay'],
  },
  // AgentSidebarShowcases
  {
    id: 'jump-back-in-rows',
    title: 'Jump back in rows',
    page: 'features',
    category: 'Agent',
    keywords: [
      'jump back in',
      'recents',
      'sidebar',
      'session',
      'room',
      'channel',
      'direct message',
      'dm',
      'shortcut',
    ],
  },
  {
    id: 'jump-back-in-popover',
    title: 'Jump back in popover',
    page: 'features',
    category: 'Agent',
    keywords: [
      'jump back in',
      'popover',
      'composer',
      'recents',
      'home',
      'listbox',
      'palette',
      'shortcut',
    ],
  },
  {
    id: 'sidebarsectionheader',
    title: 'SidebarSectionHeader',
    page: 'features',
    category: 'Agent',
    keywords: [
      'sidebar',
      'section',
      'header',
      'menu',
      'context menu',
      'right-click',
      'collapse',
      'sort',
      'show',
      'channels',
      'agents',
    ],
  },
  {
    id: 'groupcreateinput',
    title: 'GroupCreateInput',
    page: 'features',
    category: 'Agent',
    keywords: ['group', 'create', 'input', 'inline', 'rename', 'sidebar', 'enter', 'escape'],
  },
  {
    id: 'groupshintcard',
    title: 'GroupsHintCard',
    page: 'features',
    category: 'Agent',
    keywords: ['group', 'hint', 'card', 'nudge', 'discovery', 'dismiss', 'fleet', 'sidebar'],
  },
  {
    id: 'agentactivitybadge',
    title: 'AgentActivityBadge',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'activity', 'badge', 'dot', 'status', 'streaming', 'error', 'sidebar'],
  },
  {
    id: 'sessionrow-compact',
    title: 'SessionRow (compact)',
    page: 'features',
    category: 'Agent',
    keywords: ['session', 'row', 'compact', 'dot', 'sidebar', 'preview', 'variant'],
  },
  {
    id: 'agentlistitem',
    title: 'AgentListItem',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'list', 'item', 'sidebar', 'expandable', 'row', 'pin', 'select'],
  },
  {
    id: 'agentcontextmenu',
    title: 'AgentContextMenu',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'context', 'menu', 'right-click', 'pin', 'profile', 'sidebar'],
  },
  {
    id: 'agentonboardingcard',
    title: 'AgentOnboardingCard',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'onboarding', 'card', 'empty', 'state', 'sidebar', 'add'],
  },
  // MeshShowcases
  {
    id: 'meshemptystate',
    title: 'MeshEmptyState',
    page: 'features',
    category: 'Mesh',
    keywords: ['mesh', 'empty', 'state', 'topology', 'preview', 'agent'],
  },
  // TasksShowcases
  {
    id: 'tasktemplatecard',
    title: 'TaskTemplateCard',
    page: 'features',
    category: 'Tasks',
    keywords: ['preset', 'card', 'schedule', 'toggle', 'selectable', 'cron', 'tasks'],
  },
  // PipPanelShowcases
  {
    id: 'floatingpanel',
    title: 'FloatingPanel',
    page: 'features',
    category: 'PIP Panel',
    keywords: ['pip', 'panel', 'floating', 'drag', 'resize', 'mini-player', 'pop out'],
  },
  // ApprovalsShowcases
  {
    id: 'approvalcard',
    title: 'ApprovalCard',
    page: 'features',
    category: 'Approvals',
    keywords: [
      'approval',
      'approve',
      'allow',
      'deny',
      'destructive',
      'tier',
      'irreversible',
      'consent',
      'waiting on you',
    ],
  },
  {
    id: 'approvallist',
    title: 'ApprovalList',
    page: 'features',
    category: 'Approvals',
    keywords: ['approval', 'queue', 'stack', 'cap', 'pending', 'waiting on you'],
  },
  {
    id: 'standingpermissionlist',
    title: 'StandingPermissionList',
    page: 'features',
    category: 'Approvals',
    keywords: [
      'approval',
      'standing permission',
      'stop asking',
      'trust',
      'revoke',
      'stop trusting',
    ],
  },
  {
    id: 'approvalsunavailable',
    title: 'ApprovalsUnavailable',
    page: 'features',
    category: 'Approvals',
    keywords: ['approval', 'error', 'offline', 'retry', 'unavailable', 'failed read'],
  },
  // ConnectionsShowcases
  {
    id: 'servicetile',
    title: 'ServiceTile',
    page: 'features',
    category: 'Connections',
    keywords: ['connector', 'connections', 'service', 'connect', 'gmail', 'slack', 'tile', 'grid'],
  },
  {
    id: 'accountrow',
    title: 'AccountRow',
    page: 'features',
    category: 'Connections',
    keywords: [
      'connector',
      'connections',
      'account',
      'custody',
      'disclosure',
      'disconnect',
      'expired',
      'multi-account',
    ],
  },
  // McpServerCardShowcases
  {
    id: 'mcp-cards-what-needs-you',
    title: 'MCP cards: what needs you',
    page: 'features',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'needs sign-in',
      'signing in',
      'trust',
      'can’t reach',
      'setup problem',
      'attention',
    ],
  },
  {
    id: 'mcp-cards-working',
    title: 'MCP cards: working',
    page: 'features',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'connected',
      'signed in',
      'uses your key',
      'not checked yet',
      'off',
      'details',
      'tools',
    ],
  },
  {
    id: 'mcp-cards-from-somewhere-else',
    title: 'MCP cards: from somewhere else',
    page: 'features',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'scope',
      'project',
      'plugin',
      'computer',
      'discovered',
      'add to agent',
    ],
  },
  {
    id: 'mcp-cards-the-panel-when-it-opens',
    title: 'MCP cards: the panel when it opens',
    page: 'features',
    category: 'MCP servers',
    keywords: ['mcp', 'server', 'card', 'order', 'sort', 'freeze', 'panel', 'attention first'],
  },
];
