import type { PlaygroundSection } from '../playground-registry';

/**
 * Sections for the Agent & Relay page: an agent and the network it lives in.
 *
 * Sources: PersonalityPickerShowcases, AgentFleetShowcases, RelayShowcases,
 * AgentSidebarShowcases, AdapterWizardShowcases, MeshShowcases,
 * TasksShowcases, PulsePanelShowcases.
 *
 * Formerly the first half of one combined `FEATURES_SECTIONS` array — split
 * into its own page at DOR-1766 (batch 20 audit finding 20.2): the flat
 * registry had already passed the 500-line file cap and been split into two
 * data files along this exact seam, but the page above it stayed one 46-item
 * list with no matching split. `FEATURE_SURFACE_SECTIONS` is the other half,
 * now the Home, Inbox & Approvals page (`features-surface-sections.ts`).
 *
 * @module dev/sections/features-agent-sections
 */
export const FEATURE_AGENT_SECTIONS: PlaygroundSection[] = [
  // PersonalityPickerShowcases
  {
    id: 'personalitypicker',
    title: 'PersonalityPicker',
    page: 'features',
    category: 'Agent',
    keywords: [
      'personality',
      'picker',
      'radar',
      'preset',
      'traits',
      'nebula',
      'archetype',
      'slider',
    ],
  },
  // AgentFleetShowcases
  {
    id: 'agentfleettable',
    title: 'AgentFleetTable',
    page: 'features',
    category: 'Agent',
    keywords: [
      'agent',
      'fleet',
      'table',
      'attention',
      'needs you',
      'working',
      'quiet',
      'activity',
      'scheduled',
      'group',
    ],
  },
  // RelayShowcases
  {
    id: 'catalogcard',
    title: 'CatalogCard',
    page: 'features',
    category: 'Relay',
    keywords: ['catalog', 'card', 'adapter', 'manifest', 'add', 'relay'],
  },
  {
    id: 'connectionstatusbanner',
    title: 'ConnectionStatusBanner',
    page: 'features',
    category: 'Relay',
    keywords: ['connection', 'status', 'banner', 'disconnected', 'reconnecting', 'relay'],
  },
  {
    id: 'messagingconnections',
    title: 'MessagingConnections',
    page: 'features',
    category: 'Relay',
    keywords: [
      'messaging',
      'connections',
      'panel',
      'composed',
      'adapter',
      'card',
      'live now',
      'catalog',
    ],
  },
  // AdapterWizardShowcases
  {
    id: 'stepindicator',
    title: 'StepIndicator',
    page: 'features',
    category: 'Relay',
    keywords: ['step', 'indicator', 'wizard', 'progress', 'stepper', 'relay'],
  },
  {
    id: 'configurestep',
    title: 'ConfigureStep',
    page: 'features',
    category: 'Relay',
    keywords: ['configure', 'step', 'wizard', 'form', 'adapter', 'relay'],
  },
  {
    id: 'configfieldinput',
    title: 'ConfigFieldInput',
    page: 'features',
    category: 'Relay',
    keywords: ['config', 'field', 'input', 'form', 'password', 'select', 'boolean', 'relay'],
  },
  {
    id: 'configfieldinput-error-states',
    title: 'ConfigFieldInput — Error States',
    page: 'features',
    category: 'Relay',
    keywords: ['config', 'field', 'input', 'error', 'validation', 'form', 'relay'],
  },
  {
    id: 'teststep',
    title: 'TestStep',
    page: 'features',
    category: 'Relay',
    keywords: ['test', 'step', 'wizard', 'connection', 'pending', 'success', 'error', 'relay'],
  },
  {
    id: 'confirmstep',
    title: 'ConfirmStep',
    page: 'features',
    category: 'Relay',
    keywords: ['confirm', 'step', 'wizard', 'summary', 'review', 'mask', 'relay'],
  },
  {
    id: 'agentstep',
    title: 'AgentStep',
    page: 'features',
    category: 'Relay',
    keywords: ['agent', 'step', 'wizard', 'answer', 'routing', 'session', 'memory', 'relay'],
  },
  {
    id: 'setupguidesheet',
    title: 'SetupGuideSheet',
    page: 'features',
    category: 'Relay',
    keywords: ['setup', 'guide', 'sheet', 'markdown', 'instructions', 'relay'],
  },
  {
    id: 'adapterbindingrow',
    title: 'AdapterBindingRow',
    page: 'features',
    category: 'Relay',
    keywords: ['adapter', 'binding', 'row', 'agent', 'permission', 'strategy', 'relay'],
  },
  // AgentSidebarShowcases
  {
    id: 'jump-back-in-rows',
    title: 'Jump back in rows',
    page: 'features',
    category: 'Agent',
    keywords: [
      'jump back in',
      'recents',
      'sidebar',
      'session',
      'room',
      'channel',
      'direct message',
      'dm',
      'shortcut',
    ],
  },
  {
    id: 'jump-back-in-popover',
    title: 'Jump back in popover',
    page: 'features',
    category: 'Agent',
    keywords: [
      'jump back in',
      'popover',
      'composer',
      'recents',
      'home',
      'listbox',
      'palette',
      'shortcut',
    ],
  },
  {
    id: 'sectionheader',
    title: 'SectionHeader',
    page: 'features',
    category: 'Agent',
    keywords: [
      'sidebar',
      'section',
      'header',
      'menu',
      'context menu',
      'right-click',
      'collapse',
      'chevron',
      'morph',
      'sort',
      'show',
      'channels',
      'agents',
    ],
  },
  {
    id: 'sidebarheaderblock',
    title: 'SidebarHeaderBlock',
    page: 'features',
    category: 'Agent',
    keywords: ['sidebar', 'header', 'team', 'switcher', 'workspace', 'account', 'version', 'menu'],
  },
  {
    id: 'newmenu',
    title: 'NewMenu',
    page: 'features',
    category: 'Agent',
    keywords: [
      'new',
      'create',
      'session',
      'channel',
      'direct message',
      'agent',
      'group',
      'sidebar',
    ],
  },
  {
    id: 'sidebarsearchpill',
    title: 'SidebarSearchPill',
    page: 'features',
    category: 'Agent',
    keywords: ['sidebar', 'search', 'palette', 'jump', 'command', 'kbd', 'pill'],
  },
  {
    id: 'groupcreateinput',
    title: 'GroupCreateInput',
    page: 'features',
    category: 'Agent',
    keywords: ['group', 'create', 'input', 'inline', 'rename', 'sidebar', 'enter', 'escape'],
  },
  {
    id: 'agentactivitybadge',
    title: 'AgentActivityBadge',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'activity', 'badge', 'dot', 'status', 'streaming', 'error', 'sidebar'],
  },
  {
    id: 'sessionrow-compact',
    title: 'SessionRow (compact)',
    page: 'features',
    category: 'Agent',
    keywords: ['session', 'row', 'compact', 'dot', 'sidebar', 'preview', 'variant'],
  },
  {
    id: 'agentlistitem',
    title: 'AgentListItem',
    page: 'features',
    category: 'Agent',
    keywords: ['agent', 'list', 'item', 'sidebar', 'expandable', 'row', 'pin', 'select'],
  },
  {
    id: 'sessionswitcher',
    title: 'SessionSwitcher',
    page: 'features',
    category: 'Agent',
    keywords: [
      'session',
      'switcher',
      'agent',
      'dialog',
      'sheet',
      'live',
      'recent',
      'automated',
      'fork',
      'sidebar',
    ],
  },
  {
    id: 'sidebarmenusurface',
    title: 'SidebarMenuSurface',
    page: 'features',
    category: 'Agent',
    keywords: ['sidebar', 'menu', 'context', 'right-click', 'kebab', 'pin', 'profile', 'overflow'],
  },
  // MeshShowcases
  {
    id: 'meshemptystate',
    title: 'MeshEmptyState',
    page: 'features',
    category: 'Mesh',
    keywords: ['mesh', 'empty', 'state', 'topology', 'preview', 'agent'],
  },
  {
    id: 'openmeshswitch',
    title: 'OpenMeshSwitch',
    page: 'features',
    category: 'Mesh',
    keywords: ['mesh', 'switch', 'access', 'namespace', 'talk', 'topology', 'permission', 'relay'],
  },
  // TasksShowcases
  {
    id: 'tasktemplatecard',
    title: 'TaskTemplateCard',
    page: 'features',
    category: 'Tasks',
    keywords: ['preset', 'card', 'schedule', 'toggle', 'selectable', 'cron', 'tasks'],
  },
  {
    id: 'taskspanel',
    title: 'TasksPanel',
    page: 'features',
    category: 'Tasks',
    keywords: [
      'tasks',
      'panel',
      'schedule',
      'schedules',
      'disabled',
      'empty',
      'running',
      'paused',
      'composed',
    ],
  },
  // PulsePanelShowcases
  {
    id: 'pulsepanel',
    title: 'PulsePanel',
    page: 'features',
    category: 'Pulse',
    keywords: [
      'pulse',
      'panel',
      'inspector',
      'spine',
      'tab',
      'attention',
      'activity',
      'all clear',
      'composed',
    ],
  },
];
