import type { PlaygroundSection } from '../playground-registry';

/**
 * Sections for the Home, Inbox & Approvals page: the surfaces a person
 * answers things on.
 *
 * Sources: PipPanelShowcases, ApprovalsShowcases, ScheduleApprovalShowcases,
 * TriageHeaderShowcases, InboxShowcases, PresenceStripShowcases,
 * HomeStatesShowcases, ConnectionsShowcases, McpServerCardShowcases.
 *
 * See `features-agent-sections.ts` for why this used to share a page — and a
 * file — with `FEATURE_AGENT_SECTIONS`, and no longer does.
 *
 * @module dev/sections/features-surface-sections
 */
export const FEATURE_SURFACE_SECTIONS: PlaygroundSection[] = [
  // PipPanelShowcases
  {
    id: 'floatingpanel',
    title: 'FloatingPanel',
    page: 'home-inbox',
    category: 'PIP Panel',
    keywords: ['pip', 'panel', 'floating', 'drag', 'resize', 'mini-player', 'pop out'],
  },
  // ApprovalsShowcases
  {
    id: 'approvalcard',
    title: 'ApprovalCard',
    page: 'home-inbox',
    category: 'Approvals',
    keywords: [
      'approval',
      'approve',
      'allow',
      'deny',
      'destructive',
      'tier',
      'irreversible',
      'consent',
      'waiting on you',
    ],
  },
  {
    id: 'approvallist',
    title: 'ApprovalList',
    page: 'home-inbox',
    category: 'Approvals',
    keywords: ['approval', 'queue', 'stack', 'cap', 'pending', 'waiting on you'],
  },
  {
    id: 'standingpermissionlist',
    title: 'StandingPermissionList',
    page: 'home-inbox',
    category: 'Approvals',
    keywords: [
      'approval',
      'standing permission',
      'stop asking',
      'trust',
      'revoke',
      'stop trusting',
    ],
  },
  {
    id: 'approvalsunavailable',
    title: 'ApprovalsUnavailable',
    page: 'home-inbox',
    category: 'Approvals',
    keywords: ['approval', 'error', 'offline', 'retry', 'unavailable', 'failed read'],
  },
  // InboxShowcases
  {
    id: 'inbox-bell',
    title: 'Inbox bell',
    page: 'home-inbox',
    category: 'Inbox',
    keywords: [
      'inbox',
      'bell',
      'notification',
      'unread',
      'badge',
      'amber',
      'waiting on you',
      'header',
      'marker',
    ],
  },
  {
    id: 'inbox-rows',
    title: 'Inbox rows',
    page: 'home-inbox',
    category: 'Inbox',
    keywords: ['inbox', 'notification', 'row', 'unread', 'read', 'activity', 'history'],
  },
  // ScheduleApprovalShowcases
  {
    id: 'schedule-approval-card',
    title: 'Schedule approval card',
    page: 'home-inbox',
    category: 'Home',
    keywords: [
      'schedule',
      'approval',
      'proposal',
      'cron',
      'task',
      'approve',
      'reject',
      'undo',
      'run it once',
      'test run',
      'agent',
    ],
  },
  // TriageHeaderShowcases
  {
    id: 'pinned-triage-header',
    title: 'Pinned triage header',
    page: 'home-inbox',
    category: 'Home',
    keywords: [
      'triage',
      'pinned',
      'header',
      'home',
      'waiting on you',
      'needs attention',
      'approval',
      'sticky',
      'presence',
    ],
  },
  // PresenceStripShowcases
  {
    id: 'presence-strip',
    title: 'Presence strip',
    page: 'home-inbox',
    category: 'Home',
    keywords: [
      'presence',
      'working',
      'strip',
      'home',
      'header',
      'who is working',
      'follow',
      'viewer',
      'watch',
      'avatar',
    ],
  },
  // HomeStatesShowcases
  {
    id: 'day-one-and-the-quiet-morning',
    title: 'Day one and the quiet morning',
    page: 'home-inbox',
    category: 'Home',
    keywords: [
      'day one',
      'quiet',
      'all quiet',
      'starter chips',
      'openers',
      'empty state',
      'home',
      'forward look',
      'next run',
      'onboarding',
      'suggestion',
      'dorkbot',
      'promo',
      'discovery',
      'dismiss',
    ],
  },
  // ConnectionsShowcases
  {
    id: 'servicetile',
    title: 'ServiceTile',
    page: 'home-inbox',
    category: 'Connections',
    keywords: ['connector', 'connections', 'service', 'connect', 'gmail', 'slack', 'tile', 'grid'],
  },
  {
    id: 'accountrow',
    title: 'AccountRow',
    page: 'home-inbox',
    category: 'Connections',
    keywords: [
      'connector',
      'connections',
      'account',
      'custody',
      'disclosure',
      'disconnect',
      'expired',
      'multi-account',
    ],
  },
  {
    id: 'accountsregion',
    title: 'AccountsRegion',
    page: 'home-inbox',
    category: 'Connections',
    keywords: ['accounts', 'region', 'composed', 'first-run', 'composio', 'nango', 'setup'],
  },
  {
    id: 'messagingregion',
    title: 'MessagingRegion',
    page: 'home-inbox',
    category: 'Connections',
    keywords: ['messaging', 'region', 'composed', 'health bar', 'policy', 'claim feed'],
  },
  // McpServerCardShowcases
  {
    id: 'mcp-cards-what-needs-you',
    title: 'MCP cards: what needs you',
    page: 'home-inbox',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'needs sign-in',
      'signing in',
      'trust',
      'can’t reach',
      'setup problem',
      'attention',
    ],
  },
  {
    id: 'mcp-cards-working',
    title: 'MCP cards: working',
    page: 'home-inbox',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'connected',
      'signed in',
      'uses your key',
      'not checked yet',
      'off',
      'details',
      'tools',
    ],
  },
  {
    id: 'mcp-cards-from-somewhere-else',
    title: 'MCP cards: from somewhere else',
    page: 'home-inbox',
    category: 'MCP servers',
    keywords: [
      'mcp',
      'server',
      'card',
      'scope',
      'project',
      'plugin',
      'computer',
      'discovered',
      'add to agent',
    ],
  },
  {
    id: 'mcp-cards-the-panel-when-it-opens',
    title: 'MCP cards: the panel when it opens',
    page: 'home-inbox',
    category: 'MCP servers',
    keywords: ['mcp', 'server', 'card', 'order', 'sort', 'freeze', 'panel', 'attention first'],
  },
];
