import type { PlaygroundSection } from '../playground-registry';

/** Registry entries for the Generative UI page. */
export const GEN_UI_SECTIONS: PlaygroundSection[] = [
  {
    id: 'generative-ui-loading-state',
    title: 'Generative UI — Loading State',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'loading', 'skeleton', 'shimmer', 'streaming'],
  },
  {
    id: 'generative-ui-stat-card',
    title: 'Generative UI — Stat Card',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'stat', 'card', 'progress'],
  },
  {
    id: 'generative-ui-table',
    title: 'Generative UI — Table',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'table', 'columns', 'rows'],
  },
  {
    id: 'generative-ui-charts',
    title: 'Generative UI — Charts',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'chart', 'bar', 'pie', 'line', 'area'],
  },
  {
    id: 'generative-ui-list',
    title: 'Generative UI — List',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'list', 'badge', 'icon', 'thumbnail', 'meta'],
  },
  {
    id: 'generative-ui-timeline',
    title: 'Generative UI — Timeline',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'timeline', 'status', 'itinerary', 'steps'],
  },
  {
    id: 'generative-ui-checklist',
    title: 'Generative UI — Checklist',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'checklist', 'checkbox', 'submit', 'action'],
  },
  {
    id: 'generative-ui-compare',
    title: 'Generative UI — Compare',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'compare', 'matrix', 'recommended', 'options'],
  },
  {
    id: 'generative-ui-rating',
    title: 'Generative UI — Rating',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'rating', 'stars', 'reviews'],
  },
  {
    id: 'generative-ui-mood',
    title: 'Generative UI — Mood',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'mood', 'emotion', 'face', 'delight'],
  },
  {
    id: 'generative-ui-board',
    title: 'Generative UI — Board',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'board', 'grid', 'game', 'tic-tac-toe'],
  },
  {
    id: 'generative-ui-reveal',
    title: 'Generative UI — Reveal',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'reveal', 'coin', 'dice', '8ball', 'delight'],
  },
  {
    id: 'generative-ui-error-card-d5',
    title: 'Generative UI — Error Card (D5)',
    page: 'gen-ui',
    category: 'Generative UI',
    keywords: ['widget', 'gen-ui', 'dorkos-ui', 'error', 'invalid', 'fallback'],
  },
];
