import type { PlaygroundSection } from '../playground-registry';

/** Section registry entries for the One Bar page. */
export const ONE_BAR_SECTIONS: PlaygroundSection[] = [
  {
    id: 'one-bar',
    title: 'One Bar',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'header',
      'bar',
      'top nav',
      'title',
      'identity',
      'chips',
      'actions',
      'fixed cluster',
      'search',
      'inbox',
      'right panel',
      'truncation',
      'ellipsis',
    ],
  },
  {
    id: 'bar-tab-strip',
    title: 'Bar Tab Strip',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'tabs',
      'tab strip',
      'links',
      'overflow',
      'scroll',
      'edge fade',
      'active',
      'aria-current',
      'home tabs',
      'team views',
      'divider',
      'group',
      'mobile',
    ],
  },
  {
    id: 'team-bar',
    title: 'Team Bar',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'team',
      'agents',
      'roster',
      'views',
      'cards',
      'table',
      'topology',
      'denied',
      'access',
      'new agent',
      'view switcher',
      'mobile',
    ],
  },
];
