import type { PlaygroundSection } from '../playground-registry';

/** Section registry entries for the One Bar page. */
export const ONE_BAR_SECTIONS: PlaygroundSection[] = [
  {
    id: 'one-bar',
    title: 'One Bar',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'header',
      'bar',
      'top nav',
      'title',
      'identity',
      'chips',
      'actions',
      'fixed cluster',
      'search',
      'inbox',
      'right panel',
      'truncation',
      'ellipsis',
    ],
  },
  {
    id: 'session-bar',
    title: 'Session Bar',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'session',
      'agent',
      'avatar',
      'identity',
      'session title',
      'new session',
      'origin',
      'scheduled task',
      'telegram',
      'directory fallback',
      'truncation',
      'mobile',
    ],
  },
  {
    id: 'bar-tab-strip',
    title: 'Bar Tab Strip',
    page: 'one-bar',
    category: 'One Bar',
    keywords: [
      'tabs',
      'tab strip',
      'links',
      'overflow',
      'scroll',
      'edge fade',
      'active',
      'aria-current',
      'home tabs',
      'team views',
      'mobile',
    ],
  },
];
