import type { PlaygroundSection } from '../playground-registry';

/** Feature promo system sections from PromosPage. */
export const PROMOS_SECTIONS: PlaygroundSection[] = [
  {
    id: 'promo-registry',
    title: 'Promo Registry',
    page: 'promos',
    category: 'Promos',
    keywords: ['promo', 'registry', 'feature', 'discovery', 'shouldshow', 'placement', 'priority'],
  },
  {
    id: 'bottom-slot-in-a-272px-panel-with-an-overflowing-list',
    title: 'Bottom slot in a 272px panel with an overflowing list',
    page: 'promos',
    category: 'Promos',
    keywords: [
      'bottom',
      'slot',
      'pinned',
      'sidebar',
      'panel',
      'overflow',
      'scroll',
      'arbiter',
      'priority',
      'progress',
      'update',
      'profile',
      'promo',
    ],
  },
  {
    id: 'bottom-slot-above-a-composer-a-session-s-offers',
    title: "Bottom slot above a composer — a session's offers",
    page: 'promos',
    category: 'Promos',
    keywords: [
      'bottom',
      'slot',
      'arbiter',
      'priority',
      'session',
      'chat',
      'composer',
      'suggestions',
      'chips',
      'notification',
      'permission',
      'primer',
      'extension',
    ],
  },
  {
    id: 'promo-card-dashboard-sidebar',
    title: 'Promo card — dashboard-sidebar',
    page: 'promos',
    category: 'Promos',
    keywords: ['promo', 'card', 'dashboard', 'sidebar', 'compact', 'dismiss'],
  },
  {
    id: 'promo-card-agent-sidebar',
    title: 'Promo card — agent-sidebar',
    page: 'promos',
    category: 'Promos',
    keywords: ['promo', 'card', 'agent', 'sidebar', 'compact', 'session', 'embed'],
  },
  {
    id: 'override-controls',
    title: 'Override Controls',
    page: 'promos',
    category: 'Promos',
    keywords: ['promo', 'dismiss', 'reset', 'toggle', 'global', 'override', 'config'],
  },
  {
    id: 'dialog-previews',
    title: 'Dialog Previews',
    page: 'promos',
    category: 'Promos',
    keywords: ['promo', 'dialog', 'preview', 'modal', 'relay', 'schedule', 'remote', 'access'],
  },
];
