import type { PlaygroundSection } from '../playground-registry';

/**
 * Room component sections for the dev playground TOC and Cmd+K search.
 *
 * Section IDs must equal `slugify(title)` — verified by the playground-registry test suite.
 *
 * Sources: RoomsShowcases — Room Sheet, RoomMemberRow, RoomAvatar,
 * BridgeVisibilityBadge, ResponseModeControl, LoudnessMeter, RoomLoudnessLine,
 * AgentRosterPicker, RemoveMemberConfirm. RoomThreadShowcases — ThreadReplyRow,
 * RoomThreadPanel, Thread arrival animations.
 */
export const ROOMS_SECTIONS: PlaygroundSection[] = [
  {
    id: 'room-sheet',
    title: 'Room Sheet',
    page: 'rooms',
    category: 'Rooms',
    keywords: [
      'room',
      'sheet',
      'members',
      'roster',
      'channel',
      'dm',
      'direct message',
      'archived',
      'topic',
      'details',
    ],
  },
  {
    id: 'roommemberrow',
    title: 'RoomMemberRow',
    page: 'rooms',
    category: 'Rooms',
    keywords: ['member', 'row', 'roster', 'working', 'presence', 'avatar', 'agent', 'person'],
  },
  {
    id: 'roomavatar',
    title: 'RoomAvatar',
    page: 'rooms',
    category: 'Rooms',
    keywords: [
      'room',
      'avatar',
      'mark',
      'face',
      'channel',
      'dm',
      'direct message',
      'group',
      'stack',
      'agent',
      'sidebar',
    ],
  },
  {
    id: 'bridgevisibilitybadge',
    title: 'BridgeVisibilityBadge',
    page: 'rooms',
    category: 'Rooms',
    keywords: [
      'bridge',
      'visibility',
      'badge',
      'telegram',
      'privacy',
      'mentions',
      'everything',
      'chats-as-channels',
    ],
  },
  {
    id: 'responsemodecontrol',
    title: 'ResponseModeControl',
    page: 'rooms',
    category: 'Rooms',
    keywords: [
      'response mode',
      'rung',
      'loudness',
      'silent',
      'mention',
      'engaged',
      'everything',
      'radiogroup',
    ],
  },
  {
    id: 'loudnessmeter',
    title: 'LoudnessMeter',
    page: 'rooms',
    category: 'Rooms',
    keywords: ['loudness', 'meter', 'bars', 'level', 'dormant', 'scale'],
  },
  {
    id: 'roomloudnessline',
    title: 'RoomLoudnessLine',
    page: 'rooms',
    category: 'Rooms',
    keywords: ['loudness', 'room', 'line', 'sentence', 'preview', 'aggregate'],
  },
  {
    id: 'agentrosterpicker',
    title: 'AgentRosterPicker',
    page: 'rooms',
    category: 'Rooms',
    keywords: ['picker', 'chips', 'combobox', 'agents', 'add', 'fleet', 'search', 'typeahead'],
  },
  {
    id: 'removememberconfirm',
    title: 'RemoveMemberConfirm',
    page: 'rooms',
    category: 'Rooms',
    keywords: ['remove', 'confirm', 'undo', 'toast', 'member', 'destructive'],
  },
  {
    id: 'threadreplyrow',
    title: 'ThreadReplyRow',
    page: 'rooms',
    category: 'Threads',
    keywords: [
      'thread',
      'reply',
      'replies',
      'row',
      'unread',
      'count',
      'flip',
      'timeline',
      'expand',
    ],
  },
  {
    id: 'roomthreadpanel',
    title: 'RoomThreadPanel',
    page: 'rooms',
    category: 'Threads',
    keywords: [
      'thread',
      'panel',
      'side panel',
      'orphan',
      'orphaned',
      'stalled',
      'pushed',
      'mobile',
      'composer',
    ],
  },
  {
    id: 'room-moments',
    title: 'Room moments',
    page: 'rooms',
    category: 'Rooms',
    keywords: [
      'moment',
      'milestone',
      'joined your team',
      'first agent',
      'anniversary',
      'volume mark',
      'celebration',
      'team room',
    ],
  },
  {
    id: 'room-notices',
    title: 'Room notices',
    page: 'rooms',
    category: 'Delivery',
    keywords: [
      'notice',
      'turn failed',
      'busy',
      'cascade',
      'budget',
      'addressing',
      'system',
      'warning',
    ],
  },
  {
    id: 'pendingrow',
    title: 'PendingRow',
    page: 'rooms',
    category: 'Delivery',
    keywords: ['pending', 'sending', 'failed', 'retry', 'discard', 'optimistic', 'offline', 'send'],
  },
  {
    id: 'message-attachments',
    title: 'Message.Attachments',
    page: 'rooms',
    category: 'Delivery',
    keywords: ['attachment', 'file', 'image', 'thumbnail', 'download', 'chip', 'upload'],
  },
  {
    id: 'thread-arrival-animations',
    title: 'Thread arrival animations',
    page: 'rooms',
    category: 'Threads',
    keywords: [
      'thread',
      'animation',
      'connector',
      'drop',
      'hand-off',
      'handoff',
      'presence',
      'micro-interaction',
    ],
  },
];
