import type { PlaygroundSection } from '../playground-registry';

/**
 * Settings sections from SettingsPage.
 *
 * Sources: SettingsShowcases — Full Settings Dialog, Individual Tabs,
 * Claude Code Accounts, Execution Exceptions Strip, Mobile Drill-In,
 * Loading & Empty States, Settings Primitives — and RuntimeCardShowcases,
 * which owns the Runtimes category.
 */
export const SETTINGS_SECTIONS: PlaygroundSection[] = [
  // Runtimes — the tab's cards, and the two things true of the whole fleet.
  {
    id: 'runtime-cards-the-status-board-at-rest',
    title: 'Runtime cards: the status board at rest',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'runtimes',
      'card',
      'collapsed',
      'summary',
      'default',
      'ready',
      'connect',
      'claude code',
      'codex',
      'opencode',
    ],
  },
  {
    id: 'runtime-cards-opened',
    title: 'Runtime cards: opened',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'card',
      'expanded',
      'model',
      'effort',
      'trust',
      'section',
      'accounts',
      'power source',
      'opencode',
    ],
  },
  {
    id: 'runtime-cards-when-something-is-wrong',
    title: 'Runtime cards: when something is wrong',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'card',
      'broken',
      'default',
      'not connected',
      'no longer offered',
      'stranded',
      'effort',
      'unsupported',
      'warning',
    ],
  },
  {
    id: 'runtime-cards-on-a-phone',
    title: 'Runtime cards: on a phone',
    page: 'settings',
    category: 'Runtimes',
    keywords: ['runtime', 'card', 'mobile', 'responsive', 'phone', 'narrow', 'make default'],
  },
  // Dialogs
  {
    id: 'full-settings-dialog',
    title: 'Full Settings Dialog',
    page: 'settings',
    category: 'Dialogs',
    keywords: ['settings', 'dialog', 'modal', 'full', 'tabs'],
  },
  // Individual tabs
  {
    id: 'individual-tabs',
    title: 'Individual Tabs',
    page: 'settings',
    category: 'Tabs',
    keywords: [
      'appearance',
      'preferences',
      'notifications',
      'sound',
      'status bar',
      'server',
      'tools',
      'advanced',
      'rooms',
      'limits',
      'automatic replies',
      'tab',
      'isolated',
    ],
  },
  {
    id: 'claude-code-accounts',
    title: 'Claude Code Accounts',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'claude',
      'account',
      'billing',
      'client',
      'config dir',
      'CLAUDE_CONFIG_DIR',
      'switch',
      'section',
      'runtime card',
    ],
  },
  {
    id: 'execution-exceptions-strip',
    title: 'Execution Exceptions Strip',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'exception',
      'exceptions',
      'strip',
      'agent',
      'deviation',
      'broken',
      'defaults',
      'fleet',
      'runtime',
    ],
  },
  {
    id: 'background-systems',
    title: 'Background Systems',
    page: 'settings',
    category: 'Tools',
    keywords: [
      'background',
      'system',
      'systems',
      'scheduled runs',
      'scheduler',
      'agent messaging',
      'relay',
      'restart',
      'pending',
      'environment variable',
      'locked',
      'failed to start',
    ],
  },
  // Responsive
  {
    id: 'mobile-drill-in',
    title: 'Mobile Drill-In',
    page: 'settings',
    category: 'Responsive',
    keywords: ['mobile', 'drill', 'drawer', 'responsive', 'narrow'],
  },
  // States
  {
    id: 'loading-and-empty-states',
    title: 'Loading & Empty States',
    page: 'settings',
    category: 'States',
    keywords: ['loading', 'empty', 'skeleton', 'placeholder', 'no data'],
  },
  // Primitives
  {
    id: 'settings-primitives',
    title: 'Settings Primitives',
    page: 'settings',
    category: 'Primitives',
    keywords: ['fieldcard', 'settingrow', 'switch', 'row', 'card', 'wrapper'],
  },
  // Remote access — the Control Center row and the top-bar beacon, on one model.
  {
    id: 'remote-access',
    title: 'Remote Access',
    page: 'settings',
    category: 'Control Center',
    keywords: [
      'remote access',
      'tunnel',
      'ngrok',
      'beacon',
      'globe',
      'qr',
      'qr code',
      'phone',
      'link',
      'reconnecting',
      'control center',
    ],
  },
  // Control Center
  {
    id: 'control-center',
    title: 'Control Center',
    page: 'settings',
    category: 'Control Center',
    keywords: [
      'control center',
      'power',
      'trust dial',
      'warm agents',
      'standing permissions',
      'overrides',
      'flyout',
    ],
  },
];
