import type { PlaygroundSection } from '../playground-registry';

/**
 * Settings sections from SettingsPage.
 *
 * Sources: SettingsShowcases — Full Settings Dialog, Individual Tabs,
 * Claude Code Accounts, FoundAccountsGroup, Runtime Usage, Execution
 * Exceptions Strip, Mobile Drill-In,
 * Loading & Empty States, Settings Primitives — RuntimeCardShowcases,
 * which owns the Runtimes category, and CreditsOfferShowcases, its connect
 * step that offers DorkOS credits first.
 */
export const SETTINGS_SECTIONS: PlaygroundSection[] = [
  // Runtimes — the tab's cards, and the two things true of the whole fleet.
  {
    id: 'runtime-cards-the-status-board-at-rest',
    title: 'Runtime cards: the status board at rest',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'runtimes',
      'card',
      'collapsed',
      'summary',
      'default',
      'ready',
      'connect',
      'claude code',
      'codex',
      'opencode',
    ],
  },
  {
    id: 'runtime-cards-opened',
    title: 'Runtime cards: opened',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'card',
      'expanded',
      'model',
      'effort',
      'trust',
      'section',
      'accounts',
      'power source',
      'opencode',
    ],
  },
  {
    id: 'runtime-cards-when-something-is-wrong',
    title: 'Runtime cards: when something is wrong',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'card',
      'broken',
      'default',
      'not connected',
      'no longer offered',
      'stranded',
      'effort',
      'unsupported',
      'warning',
    ],
  },
  {
    id: 'runtime-cards-on-a-phone',
    title: 'Runtime cards: on a phone',
    page: 'settings',
    category: 'Runtimes',
    keywords: ['runtime', 'card', 'mobile', 'responsive', 'phone', 'narrow', 'make default'],
  },
  {
    id: 'runtime-connect-dorkos-credits-first',
    title: 'Runtime connect: DorkOS credits first',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'runtime',
      'connect',
      'credits',
      'dorkos account',
      'default first',
      'sign in',
      'api key',
      'other ways',
      'link',
    ],
  },
  // Dialogs
  {
    id: 'full-settings-dialog',
    title: 'Full Settings Dialog',
    page: 'settings',
    category: 'Dialogs',
    keywords: ['settings', 'dialog', 'modal', 'full', 'tabs'],
  },
  // Individual tabs
  {
    id: 'individual-tabs',
    title: 'Individual Tabs',
    page: 'settings',
    category: 'Tabs',
    keywords: [
      'appearance',
      'preferences',
      'notifications',
      'sound',
      'status bar',
      'server',
      'tools',
      'advanced',
      'rooms',
      'limits',
      'automatic replies',
      'tab',
      'isolated',
    ],
  },
  {
    id: 'credits-runs-on',
    title: 'Credits Runs On',
    page: 'settings',
    category: 'Runtimes',
    keywords: ['codex', 'opencode', 'credits', 'runs on', 'sign-in', 'dorkos account', 'section'],
  },
  {
    id: 'claude-code-accounts',
    title: 'Claude Code Accounts',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'claude',
      'account',
      'billing',
      'client',
      'config dir',
      'CLAUDE_CONFIG_DIR',
      'switch',
      'section',
      'runtime card',
      'usage',
      'color',
      'flow',
    ],
  },
  {
    id: 'foundaccountsgroup',
    title: 'FoundAccountsGroup',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'found on this computer',
      'claude',
      'account',
      'folder',
      'add',
      'dismiss',
      'organization',
      'managed',
      'discover',
    ],
  },
  {
    id: 'runtime-usage',
    title: 'Runtime Usage',
    page: 'settings',
    category: 'Runtimes',
    keywords: ['codex', 'opencode', 'usage', 'spend', 'limit', 'weekly', 'runtime card'],
  },
  {
    id: 'execution-exceptions-strip',
    title: 'Execution Exceptions Strip',
    page: 'settings',
    category: 'Runtimes',
    keywords: [
      'exception',
      'exceptions',
      'strip',
      'agent',
      'deviation',
      'broken',
      'defaults',
      'fleet',
      'runtime',
    ],
  },
  {
    id: 'background-systems',
    title: 'Background Systems',
    page: 'settings',
    category: 'Tools',
    keywords: [
      'background',
      'system',
      'systems',
      'scheduled runs',
      'scheduler',
      'agent messaging',
      'relay',
      'restart',
      'pending',
      'environment variable',
      'locked',
      'failed to start',
    ],
  },
  // Responsive
  {
    id: 'mobile-drill-in',
    title: 'Mobile Drill-In',
    page: 'settings',
    category: 'Responsive',
    keywords: ['mobile', 'drill', 'drawer', 'responsive', 'narrow'],
  },
  // States
  {
    id: 'loading-and-empty-states',
    title: 'Loading & Empty States',
    page: 'settings',
    category: 'States',
    keywords: ['loading', 'empty', 'skeleton', 'placeholder', 'no data'],
  },
  // Primitives
  {
    id: 'settings-primitives',
    title: 'Settings Primitives',
    page: 'settings',
    category: 'Primitives',
    keywords: [
      'fieldcard',
      'settingrow',
      'switch',
      'row',
      'card',
      'wrapper',
      'collapsible',
      'disclosure',
    ],
  },
  // Remote access — the Control Center row, Settings and the top-bar beacon, on one model.
  {
    id: 'remote-access',
    title: 'Remote Access',
    page: 'settings',
    category: 'Control Center',
    keywords: [
      'remote access',
      'tunnel',
      'ngrok',
      'beacon',
      'globe',
      'qr',
      'qr code',
      'phone',
      'link',
      'reconnecting',
      'control center',
      'managed',
      'dorkos setup',
      'approval code',
    ],
  },
  // Keep awake — the top-bar cup and the Sleep card, on one status.
  {
    id: 'keep-awake',
    title: 'Keep Awake',
    page: 'settings',
    category: 'Control Center',
    keywords: ['keep awake', 'sleep', 'caffeinate', 'cup', 'coffee', 'beacon', 'battery'],
  },
  // Control Center
  {
    id: 'control-center',
    title: 'Control Center',
    page: 'settings',
    category: 'Control Center',
    keywords: [
      'control center',
      'power',
      'trust dial',
      'warm agents',
      'standing permissions',
      'overrides',
      'flyout',
    ],
  },
  // CloudUsageShowcases
  {
    id: 'plan-card',
    title: 'Plan card',
    page: 'settings',
    category: 'Account',
    keywords: ['plan', 'cloud', 'account', 'seats', 'who can buy', 'eligibility'],
  },
  {
    id: 'manage-on-the-web',
    title: 'Manage on the web',
    page: 'settings',
    category: 'Account',
    keywords: ['billing', 'invoices', 'add credits', 'change plan', 'checkout', 'portal', 'cloud'],
  },
  {
    id: 'credits-and-other-charges',
    title: 'Credits and other charges',
    page: 'settings',
    category: 'Account',
    keywords: ['credits', 'usage', 'cloud', 'account', 'other charges', 'storage', 'billing'],
  },
];
