import type { PlaygroundSection } from '../playground-registry';

/** Section registry entries for the Sidebar Model page. */
export const SIDEBAR_MODEL_SECTIONS: PlaygroundSection[] = [
  {
    id: 'sidebar-model-journeys',
    title: 'Sidebar Model Journeys',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'sidebar',
      'model',
      'zones',
      'now',
      'today',
      'library',
      'getting started',
      'fixtures',
      'journeys',
      'reason',
      'first run',
      'quiet',
      'busy',
      'power',
    ],
  },
  {
    // This is the PLAYGROUND section's id, which the registry pins to
    // `slugify(title)` — not the sidebar zone's id, which is still `now`
    // (DOR-1155). `now` is kept as a keyword so the old word still finds it.
    id: 'sidebar-heads-up-states',
    title: 'Sidebar Heads Up States',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'sidebar',
      'heads up',
      'now',
      'attention',
      'needs you',
      'approval',
      'permission',
      'question',
      'error',
      'schedule',
      'overflow',
      'all clear',
      'getting started',
      'onboarding',
    ],
  },
  {
    id: 'sidebar-today-states',
    title: 'Sidebar Today States',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'sidebar',
      'today',
      'anchor',
      'recents',
      'digest',
      'welcome back',
      'automated',
      'reveal',
      'archive',
      'overnight',
      'interaction recency',
    ],
  },
  {
    id: 'mobile-tabs',
    title: 'Mobile Tabs',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'mobile',
      'phone',
      'tabs',
      'bottom bar',
      'home',
      'library',
      'dorkbot',
      'you',
      'badge',
      'needs you',
      'drawer',
      'sheet',
    ],
  },
  {
    id: 'mobile-long-press-menu',
    title: 'Mobile Long-press Menu',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'mobile',
      'phone',
      'long press',
      'press and hold',
      'sheet',
      'drawer',
      'context menu',
      'kebab',
      'touch',
      'row actions',
    ],
  },
  {
    id: 'mobile-catch-up',
    title: 'Mobile Catch Up',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: [
      'mobile',
      'phone',
      'catch up',
      'mark read',
      'unread',
      'today',
      'read cursor',
      'bulk',
      'touch',
    ],
  },
  {
    id: 'sidebar-unread-tiers',
    title: 'Sidebar Unread Tiers',
    page: 'sidebar-model',
    category: 'Sidebar',
    keywords: ['sidebar', 'unread', 'badge', 'bold', 'mention', 'dm', 'directed', 'activity'],
  },
];
