import { buildCurrentQueueBatchIntention } from './current/current-operation-intentions.js';
import {
  captureCurrentBatchOriginalInputs,
  buildCurrentRoomInputIntention,
  requireCurrentAdmissionIdentity,
  buildBatchDocContext as batchContext,
  requireCurrentBatchSliceBounds,
  freezeAdmissionData,
} from './current/current-operation-intentions.js';

import { auditCurrentQueueRows } from './current/current-operation-row-audit.js';
import { type SynchronousResult } from './storage/store-transaction.js';
/** Compact, sequence-ordered pending batches; admission remains an external transaction port. */
import { randomUUID } from 'node:crypto';
import {
  and,
  eq,
  inArray,
  canvasDocBatches,
  canvasDocDeliveries,
  type DbTransaction,
} from '@dorkos/db';
import {
  DocChannelCorruptionError,
  DocChannelStore,
  type DocBatchRow,
  type DocEventRow,
} from './store.js';
import { type DocIngestAccess, type DocRouteDecision, DocIngestRefusal } from './ingest-types.js';

import { isCurrentDocQueueScope, failCurrentDocOperation } from './authorization.js';
import { readChecked } from './storage/store-json.js';
import { readDocEventRow } from './writes/reservations/reservation-policy-census.js';
import { copyCurrentDocData, sameCurrentDocData } from './current/current-operation-data.js';
import { isOriginalCheckboxQueueScope } from './writes/reservations/reservation-bridge.js';
import { docEventsPromptBytes, DOC_EVENTS_PROMPT_BYTES } from './prompt.js';

import type {
  CurrentQueueIntent,
  OriginalQueueIdentity,
  DocBatchSlice,
} from './current/current-operation-types.js';
export type { CurrentQueueIntent } from './current/current-operation-types.js';
const currentQueueIntents = new WeakMap<DbTransaction, CurrentQueueIntent>();
function captureCurrentQueueIntent(
  store: DocChannelStore,
  tx: DbTransaction,
  access: DocIngestAccess,
  decision: DocRouteDecision,
  event: DocEventRow,
  batch: DocBatchRow | undefined,
  delivery: typeof canvasDocDeliveries.$inferSelect,
  priorInputs?: ReturnType<typeof captureCurrentBatchOriginalInputs>
): void {
  if (!isCurrentDocQueueScope(store, tx, event, access, decision)) return;
  let own = currentQueueIntents.get(tx);
  if (!own) {
    own = { store, eventId: event.eventId, routes: new Map(), superseded: [] };
    currentQueueIntents.set(tx, own);
  }
  if (own.store !== store || own.eventId !== event.eventId || own.routes.has(decision.route.id))
    throw new Error('Current route identity is already captured.');
  own.routes.set(
    decision.route.id,
    copyCurrentDocData({
      ...(batch
        ? {
            batch,
            inputs: buildCurrentRoomInputIntention(batch, priorInputs ?? [], event, delivery),
          }
        : {}),
      delivery,
    })
  );
}
/** Read only coalescer-generated original intentions; no caller registration or reset operation exists. */
export function readCurrentDocQueueAudit(
  store: DocChannelStore,
  tx: DbTransaction,
  event: DocEventRow
) {
  const own = currentQueueIntents.get(tx);
  if (!own) return []; // Exact expected route cardinality is separately validated by fixed ingestor.
  if (own.store !== store || own.eventId !== event.eventId)
    throw new Error('Current queue scope is foreign.');
  try {
    auditCurrentQueueRows(tx, event, own);
    return copyCurrentDocData([...own.routes.values()]);
  } catch (cause) {
    return failCurrentDocOperation(store, tx, cause);
  }
}
/** Read only pre-effect coalescer intentions, never a public store-derived replacement. */
export function readCurrentDocQueueDeliveries(
  store: DocChannelStore,
  tx: DbTransaction,
  event: DocEventRow
): readonly (typeof canvasDocDeliveries.$inferSelect)[] {
  readCurrentDocQueueAudit(store, tx, event);
  const own = currentQueueIntents.get(tx);
  return own ? [...own.routes.values()].map((route) => route.delivery) : [];
}
const originalQueueIdentities = new WeakMap<DbTransaction, Readonly<OriginalQueueIdentity>>();
/** Read only the identity generated by this coalescer in the genuine original scope. */
export function readOriginalCheckboxQueueIdentity(
  store: DocChannelStore,
  tx: DbTransaction,
  event: DocEventRow
): Readonly<{ batchId: string; generation: string }> {
  const own = originalQueueIdentities.get(tx);
  if (
    !isOriginalCheckboxQueueScope(store, tx, event) ||
    !own ||
    own.store !== store ||
    own.eventId !== event.eventId
  )
    throw new Error('Original checkbox queue identity is absent.');
  return Object.freeze({ batchId: own.batchId, generation: own.generation });
}
function retainOriginalQueueIdentity(
  store: DocChannelStore,
  tx: DbTransaction,
  event: DocEventRow,
  batchId: string,
  generation: string
): void {
  if (!isOriginalCheckboxQueueScope(store, tx, event)) return;
  if (originalQueueIdentities.has(tx))
    throw new Error('Original checkbox queue identity is already retained.');
  originalQueueIdentities.set(
    tx,
    Object.freeze({ store, eventId: event.eventId, batchId, generation })
  );
}

/** Renderer input assembled only from stored events and server-derived metadata. */
export { buildBatchDocContext as batchContext } from './current/current-operation-intentions.js';

/** Add input while preserving the first deadline and explicitly settling replaceable inputs. */
export function queueInput(
  store: DocChannelStore,
  tx: DbTransaction,
  access: DocIngestAccess,
  decision: DocRouteDecision,
  event: DocEventRow,
  now: string
): void {
  const { route, grantId, grantRevision } = decision;
  if (!grantId || !grantRevision || route.turn.mode === 'none')
    throw new Error('Queue requires verified turn authority.');
  const pending = tx
    .select({ batchId: canvasDocBatches.batchId })
    .from(canvasDocBatches)
    .where(
      and(
        eq(canvasDocBatches.documentId, access.documentId),
        eq(canvasDocBatches.routeId, route.id),
        inArray(canvasDocBatches.status, ['pending', 'waiting'])
      )
    )
    .get();
  const batch = pending ? store.getBatch(pending.batchId, tx)! : undefined;
  if (isCurrentDocQueueScope(store, tx, event, access, decision) && pending) {
    const actual = readChecked('canvas_doc_batches', pending.batchId, () =>
      tx.select().from(canvasDocBatches).where(eq(canvasDocBatches.batchId, pending.batchId)).get()
    );
    if (!actual || !sameCurrentDocData(actual, batch))
      return failCurrentDocOperation(
        store,
        tx,
        new Error('Current pending batch cannot be substituted by a public getter.')
      );
  }
  if (
    batch &&
    (batch.grantId !== grantId ||
      batch.grantRevision !== grantRevision ||
      batch.scope !== access.scope)
  ) {
    captureCurrentQueueIntent(store, tx, access, decision, event, undefined, {
      documentId: event.documentId,
      eventId: event.eventId,
      routeId: route.id,
      batchId: null,
      deliveryKind: null,
      roomAdmissionId: null,
      status: 'saved',
      reason: 'route_generation_changed',
      turnId: null,
      ackOutcome: null,
      ackEvidence: null,
      acknowledgedAt: null,
      acknowledgedBy: null,
      updatedAt: now,
    });
    store.insertDelivery(
      {
        documentId: event.documentId,
        eventId: event.eventId,
        routeId: route.id,
        status: 'saved',
        reason: 'route_generation_changed',
        updatedAt: now,
      },
      tx
    );
    return;
  }
  const priorInputs = isCurrentDocQueueScope(store, tx, event, access, decision)
    ? captureCurrentBatchOriginalInputs(tx, batch)
    : undefined;
  const batchId = batch?.batchId ?? randomUUID();
  const generation = batch?.generation ?? randomUUID();
  let ids = batch?.inputEventIds ?? [];
  // Comments are append-only even if a declaration requests coalescing.
  // Type also participates in identity so a checkbox cannot replace another event type.
  if (
    event.type.split('.').at(-1) !== 'comment' &&
    event.coalesceKey &&
    route.coalescibleTypes?.includes(event.type)
  ) {
    ids = ids.filter((id) => {
      const prior = isCurrentDocQueueScope(store, tx, event, access, decision)
        ? readDocEventRow(tx, event.documentId, id)!
        : store.getEvent(event.documentId, id, tx)!;
      if (!prior)
        return failCurrentDocOperation(
          store,
          tx,
          new Error('Current pending batch original input is absent.')
        );
      if (prior.type !== event.type || prior.coalesceKey !== event.coalesceKey) return true;
      if (isCurrentDocQueueScope(store, tx, event, access, decision)) {
        let own = currentQueueIntents.get(tx);
        if (!own) {
          own = { store, eventId: event.eventId, routes: new Map(), superseded: [] };
          currentQueueIntents.set(tx, own);
        }
        const before = tx
          .select()
          .from(canvasDocDeliveries)
          .where(
            and(
              eq(canvasDocDeliveries.documentId, event.documentId),
              eq(canvasDocDeliveries.eventId, id),
              eq(canvasDocDeliveries.routeId, route.id)
            )
          )
          .get();
        if (!before || before.batchId !== batchId || before.status !== batch!.status)
          return failCurrentDocOperation(
            store,
            tx,
            new Error('Superseded receipt lacks exact correlated original membership.')
          );
        own.superseded.push(
          copyCurrentDocData({
            original: prior,
            delivery: {
              ...before,
              status: 'superseded',
              reason: 'replaced_before_admission',
              updatedAt: now,
            },
          })
        );
      }
      if (
        !store.updateDelivery(
          {
            documentId: event.documentId,
            eventId: id,
            routeId: route.id,
            expectedStatus: batch!.status === 'waiting' ? 'waiting' : 'pending',
            changes: { status: 'superseded', reason: 'replaced_before_admission', updatedAt: now },
          },
          tx
        )
      )
        throw new Error('Pending delivery changed while coalescing.');
      return false;
    });
  }
  ids = [...ids, event.eventId];
  retainOriginalQueueIdentity(store, tx, event, batchId, generation);
  const intendedBatch = buildCurrentQueueBatchIntention(
    batch,
    event,
    access,
    decision,
    ids,
    batchId,
    generation,
    now
  );
  captureCurrentQueueIntent(
    store,
    tx,
    access,
    decision,
    event,
    intendedBatch,
    {
      documentId: event.documentId,
      eventId: event.eventId,
      routeId: route.id,
      batchId,
      deliveryKind: null,
      roomAdmissionId: null,
      status: batch?.status === 'waiting' ? 'waiting' : 'pending',
      turnId: null,
      reason: null,
      ackOutcome: null,
      ackEvidence: null,
      acknowledgedAt: null,
      acknowledgedBy: null,
      updatedAt: now,
    },
    priorInputs
  );
  if (batch) {
    if (
      !store.updatePendingBatch(
        {
          batchId,
          generation: batch.generation,
          status: batch.status as 'pending' | 'waiting',
          inputEventIds: ids,
          effectivePayload: { eventIds: ids },
          updatedAt: now,
        },
        tx
      )
    )
      throw new Error('Pending batch changed.');
  } else {
    const due = Date.parse(now) + (route.turn.mode === 'coalesce' ? route.turn.windowMs : 0);
    if (!Number.isFinite(due) || due > 8640000000000000)
      throw new DocIngestRefusal('INVALID_ROUTE_DEADLINE', 422);
    store.insertBatch(
      {
        batchId,
        documentId: event.documentId,
        scope: access.scope,
        routeId: route.id,
        grantId,
        grantRevision,
        generation,
        inputEventIds: ids,
        effectivePayload: { eventIds: ids },
        dueAt: new Date(due).toISOString(),
        status: 'pending',
        createdAt: now,
        updatedAt: now,
      },
      tx
    );
  }
  if (batch) {
    const current = store.getBatch(batch.batchId, tx);
    if (
      !current ||
      current.generation !== batch.generation ||
      current.status !== batch.status ||
      current.dueAt !== batch.dueAt ||
      current.scope !== batch.scope ||
      current.grantId !== batch.grantId ||
      current.grantRevision !== batch.grantRevision
    )
      throw new Error('Pending batch identity changed while joining input.');
  }
  store.insertDelivery(
    {
      documentId: event.documentId,
      eventId: event.eventId,
      routeId: route.id,
      batchId,
      status: batch?.status === 'waiting' ? 'waiting' : 'pending',
      updatedAt: now,
    },
    tx
  );
}

/** Exact immutable inputs offered to an admission owner, excluding superseded receipts. */
export type { DocBatchSlice } from './current/current-operation-types.js';

/** Select at most 100 originals and the exact rendered byte budget; no input is silently dropped. */
export function selectBatchSlice(
  store: DocChannelStore,
  tx: DbTransaction,
  batch: DocBatchRow,
  maxBatch: number,
  documentLabel: string,
  promptBytes = DOC_EVENTS_PROMPT_BYTES
): DocBatchSlice {
  requireCurrentBatchSliceBounds(promptBytes, maxBatch);
  if (!['pending', 'waiting'].includes(batch.status))
    throw new Error('Only pending inputs can be selected.');
  if (new Set(batch.inputEventIds).size !== batch.inputEventIds.length)
    throw new DocChannelCorruptionError('canvas_doc_batches', batch.batchId);
  const selected: DocEventRow[] = [];
  const inputs = batch.inputEventIds
    .map((id) => {
      const event = store.getEvent(batch.documentId, id, tx);
      if (!event || event.payloadPrunedAt !== null)
        throw new DocChannelCorruptionError('canvas_doc_batches', batch.batchId);
      return event;
    })
    .sort((a, b) => a.docSeq - b.docSeq);
  for (const event of inputs) {
    if (
      selected.length === maxBatch ||
      docEventsPromptBytes(batchContext(batch, [...selected, event], documentLabel)) > promptBytes
    )
      break;
    selected.push(event);
  }
  if (!selected.length) throw new DocIngestRefusal('DOC_EVENT_CONTEXT_TOO_LARGE', 413);
  return {
    batch: {
      ...batch,
      inputEventIds: selected.map((event) => event.eventId),
      effectivePayload: { eventIds: selected.map((event) => event.eventId), documentLabel },
    },
    context: batchContext(batch, selected, documentLabel),
    overflowIds: inputs.slice(selected.length).map((event) => event.eventId),
  };
}

/** Split atomically with external admission; the callback must move the selected batch out of the pending slot. */
export function admitBatchSlice<T>(
  store: DocChannelStore,
  batchId: string,
  maxBatch: number,
  documentLabel: string,
  now: string,
  admit: (tx: DbTransaction, slice: DocBatchSlice) => T & SynchronousResult<T>,
  promptBytes = DOC_EVENTS_PROMPT_BYTES
): T {
  return store.transaction<T>((tx) => {
    const original = store.getBatch(batchId, tx);
    if (!original) throw new Error('Missing pending batch.');
    const slice = selectBatchSlice(store, tx, original, maxBatch, documentLabel, promptBytes);
    if (
      !store.updatePendingBatch(
        {
          batchId,
          generation: original.generation,
          status: original.status as 'pending' | 'waiting',
          inputEventIds: slice.batch.inputEventIds,
          effectivePayload: slice.batch.effectivePayload,
          updatedAt: now,
        },
        tx
      )
    )
      throw new Error('Pending batch changed.');
    // The callback may only persist admission. Its mutable view cannot redefine
    // the selection against which committed source identity is checked.
    const selectedIds = JSON.stringify(slice.batch.inputEventIds);
    const selectedPayload = JSON.stringify(slice.batch.effectivePayload);
    const overflowIds = [...slice.overflowIds];
    freezeAdmissionData(slice);
    const result = admit(tx, slice);
    const accepted = store.getBatch(batchId, tx)!;
    requireCurrentAdmissionIdentity(accepted, original, selectedIds, selectedPayload);
    if (['pending', 'waiting'].includes(accepted.status))
      throw new Error('Admission did not release the pending slot.');
    if (overflowIds.length) {
      const overflowId = randomUUID();
      store.insertBatch(
        {
          ...original,
          scope: accepted.scope,
          batchId: overflowId,
          generation: randomUUID(),
          inputEventIds: overflowIds,
          effectivePayload: { eventIds: overflowIds },
          attempt: 0,
          leaseUntil: null,
          relayMessageId: null,
          turnId: null,
          admissionReceiptId: null,
          errorCode: null,
          createdAt: now,
          updatedAt: now,
        },
        tx
      );
      tx.update(canvasDocDeliveries)
        .set({ batchId: overflowId })
        .where(
          and(
            eq(canvasDocDeliveries.documentId, original.documentId),
            eq(canvasDocDeliveries.routeId, original.routeId),
            eq(canvasDocDeliveries.batchId, batchId),
            inArray(canvasDocDeliveries.eventId, overflowIds)
          )
        )
        .run();
    }
    return result;
  });
}

/** Derived write cardinality of closed before-effect queue intentions; no count registration exists. */
export function readCurrentDocQueueWriteCount(
  store: DocChannelStore,
  tx: DbTransaction,
  event: DocEventRow
): number {
  readCurrentDocQueueAudit(store, tx, event);
  const own = currentQueueIntents.get(tx);
  if (!own) return 0;
  let count = own.superseded.length;
  for (const intended of own.routes.values()) count += intended.batch ? 2 : 1;
  if (!Number.isSafeInteger(count))
    return failCurrentDocOperation(
      store,
      tx,
      new Error('Current queue write cardinality is unavailable.')
    );
  return count;
}
