/**
 * Checks the launcher's Fly GraphQL documents against Fly's real schema, without a GraphQL
 * library.
 *
 * Three paid live runs stopped on answers the fixtures had invented; one of them was a query for a
 * root field (`node`) that Fly's API does not have. A fixture can only prove the parser agrees with
 * the fixture. This proves every field, argument, input field and inline-fragment type the
 * documents name exists in the schema Fly serves, using a trimmed introspection snapshot that the
 * contract replay (`community-deploy-contract-replay.ts`) regenerates from the live API.
 *
 * The parser understands exactly the GraphQL the launcher writes: one named operation with typed
 * variables, fields with arguments whose values are variables or object literals, and `... on Type`
 * inline fragments. Anything else is reported as unsupported rather than silently accepted.
 */
import { resolve } from 'node:path';
import {
  FLY_APP_TIGRIS_QUERY,
  FLY_TIGRIS_CREATE_MUTATION,
  FLY_TIGRIS_CREDENTIALS_QUERY,
  FLY_TIGRIS_DELETE_MUTATION,
  FLY_TIGRIS_READ_QUERY,
  FLY_TIGRIS_TERMS_QUERY,
} from '../src/commands/community-deploy/fly-graphql-contract.js';

/** Every GraphQL document the launcher and the live gate send, by the name used in reports. */
export const LAUNCHER_GRAPHQL_DOCUMENTS = {
  DorkosTigrisTerms: FLY_TIGRIS_TERMS_QUERY,
  DorkosCreateTigris: FLY_TIGRIS_CREATE_MUTATION,
  DorkosReadTigris: FLY_TIGRIS_READ_QUERY,
  DorkosReadTigrisCredentials: FLY_TIGRIS_CREDENTIALS_QUERY,
  DorkosDeleteTigris: FLY_TIGRIS_DELETE_MUTATION,
  DorkosListAppTigris: FLY_APP_TIGRIS_QUERY,
} as const;

/** The checked-in snapshot of Fly's schema, regenerated by `replay:community-contract --write-schema`. */
export const FLY_SCHEMA_SNAPSHOT = resolve(
  import.meta.dirname,
  '../src/commands/community-deploy/__tests__/contract/fly-graphql-schema.json'
);

/** A type reference as introspection reports it. */
export interface IntrospectedTypeRef {
  /** `NON_NULL`, `LIST`, or the named type's kind. */
  kind: string;
  /** Named type, or null for a wrapper. */
  name: string | null;
  /** Wrapped type for `NON_NULL` and `LIST`. */
  ofType: IntrospectedTypeRef | null;
}

/** One field or input field. */
export interface IntrospectedField {
  /** Field name. */
  name: string;
  /** Arguments (fields only). */
  args?: Array<{ name: string; type: IntrospectedTypeRef }>;
  /** Result or input type. */
  type: IntrospectedTypeRef;
}

/** One named type. */
export interface IntrospectedType {
  /** `OBJECT`, `INTERFACE`, `UNION`, `INPUT_OBJECT`, `SCALAR` or `ENUM`. */
  kind: string;
  /** Type name. */
  name: string;
  /** Output fields (objects and interfaces). */
  fields?: IntrospectedField[] | null;
  /** Input fields (input objects). */
  inputFields?: IntrospectedField[] | null;
  /** Concrete types of an interface or union. */
  possibleTypes?: Array<{ name: string }> | null;
  /** Enum values. */
  enumValues?: Array<{ name: string }> | null;
}

/** The part of an introspection answer this checker reads. */
export interface IntrospectedSchema {
  /** Root query type name. */
  queryType: { name: string };
  /** Root mutation type name. */
  mutationType: { name: string } | null;
  /** Every named type kept. */
  types: IntrospectedType[];
}

/** The introspection query the replay sends; kept here so the snapshot and its reader agree. */
export const FLY_INTROSPECTION_QUERY = `query DorkosIntrospection { __schema {
  queryType { name } mutationType { name }
  types { kind name possibleTypes { name }
    fields(includeDeprecated: true) { name args { name type { ...T } } type { ...T } }
    inputFields { name type { ...T } } enumValues(includeDeprecated: true) { name } } } }
fragment T on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } }`;

type Token = { kind: 'name' | 'punct' | 'spread' | 'int'; value: string };

function tokenize(document: string): Token[] {
  const tokens: Token[] = [];
  const pattern =
    /\s+|,|#[^\n]*|(\.\.\.)|([A-Za-z_][A-Za-z0-9_]*)|([{}():$!=[\]])|(-?\d+)(?![.\deE])|(\S)/gu;
  for (const match of document.matchAll(pattern)) {
    if (match[5]) throw new Error(`unsupported token ${match[5]}`);
    if (match[4]) tokens.push({ kind: 'int', value: match[4] });
    else if (match[1]) tokens.push({ kind: 'spread', value: '...' });
    else if (match[2]) tokens.push({ kind: 'name', value: match[2] });
    else if (match[3]) tokens.push({ kind: 'punct', value: match[3] });
  }
  return tokens;
}

function named(ref: IntrospectedTypeRef): string {
  let current: IntrospectedTypeRef | null = ref;
  while (current && !current.name) current = current.ofType;
  if (!current?.name) throw new Error('unnamed type reference');
  return current.name;
}

/**
 * Check one GraphQL document against a schema snapshot.
 *
 * @param document - One operation, as the launcher sends it.
 * @param schema - Introspection snapshot of the service.
 * @returns Every problem found, each naming the path; empty when the document fits the schema.
 */
export function checkGraphqlDocument(document: string, schema: IntrospectedSchema): string[] {
  const types = new Map(schema.types.map((type) => [type.name, type]));
  const problems: string[] = [];
  let tokens: Token[];
  try {
    tokens = tokenize(document);
  } catch (error) {
    return [(error as Error).message];
  }
  let index = 0;
  const peek = () => tokens[index];
  const take = (expected?: string): Token => {
    const token = tokens[index++];
    if (!token) throw new Error('unexpected end of document');
    if (expected !== undefined && token.value !== expected) {
      throw new Error(`expected ${expected}, found ${token.value}`);
    }
    return token;
  };

  // Variables: `($name: Type!, ...)`.
  const skipTypeRef = (): string => {
    if (peek()?.value === '[') {
      take('[');
      const inner = skipTypeRef();
      take(']');
      if (peek()?.value === '!') take('!');
      return inner;
    }
    const name = take().value;
    if (peek()?.value === '!') take('!');
    if (!types.has(name)) problems.push(`variable type ${name} does not exist`);
    return name;
  };

  const checkValue = (inputType: string | null, path: string): void => {
    const token = peek();
    if (token?.value === '$') {
      take('$');
      take();
      return;
    }
    if (inputType && !types.has(inputType)) {
      problems.push(`${path}: type ${inputType} missing from snapshot`);
    }
    if (token?.value === '{') {
      take('{');
      const input = inputType ? types.get(inputType) : undefined;
      while (peek()?.value !== '}') {
        const field = take().value;
        take(':');
        const inputField = input?.inputFields?.find((candidate) => candidate.name === field);
        if (input && !inputField) problems.push(`${path}.${field}: no such input field`);
        checkValue(inputField ? named(inputField.type) : null, `${path}.${field}`);
      }
      take('}');
      return;
    }
    if (token?.kind === 'int') {
      take();
      if (inputType && inputType !== 'Int' && inputType !== 'Float') {
        problems.push(`${path}: an integer is not a ${inputType}`);
      }
      return;
    }
    if (token?.kind === 'name') {
      const literal = take().value;
      const input = inputType ? types.get(inputType) : undefined;
      if (
        input?.kind === 'ENUM' &&
        !(input.enumValues ?? []).some((value) => value.name === literal)
      ) {
        problems.push(`${path}: ${literal} is not a ${inputType}`);
      }
      return;
    }
    throw new Error(`unsupported value at ${path}`);
  };

  // `typeName` is null only below a field already reported as missing. Any other type the
  // snapshot lacks is reported, never silently skipped: a snapshot missing a type cannot vouch
  // for any field selected on it.
  const selection = (typeName: string | null, path: string): void => {
    const type = typeName ? types.get(typeName) : undefined;
    if (typeName && !type) problems.push(`${path}: type ${typeName} missing from snapshot`);
    take('{');
    while (peek()?.value !== '}') {
      if (peek()?.kind === 'spread') {
        take();
        take('on');
        const fragmentType = take().value;
        const target = types.get(fragmentType);
        const possible =
          fragmentType === typeName ||
          (type?.possibleTypes ?? []).some((candidate) => candidate.name === fragmentType);
        if (!target) problems.push(`${path}: fragment type ${fragmentType} does not exist`);
        else if (!possible) problems.push(`${path}: ${fragmentType} is not a ${typeName}`);
        selection(fragmentType, `${path}(on ${fragmentType})`);
        continue;
      }
      const name = take().value;
      const fieldPath = `${path}.${name}`;
      const field = type?.fields?.find((candidate) => candidate.name === name);
      if (type && !field) problems.push(`${fieldPath}: no such field on ${typeName}`);
      if (peek()?.value === '(') {
        take('(');
        while (peek()?.value !== ')') {
          const argument = take().value;
          take(':');
          const declared = field?.args?.find((candidate) => candidate.name === argument);
          if (field && !declared) problems.push(`${fieldPath}(${argument}): no such argument`);
          checkValue(declared ? named(declared.type) : null, `${fieldPath}(${argument})`);
        }
        take(')');
      }
      const resultType = field ? types.get(named(field.type)) : undefined;
      const composite = ['OBJECT', 'INTERFACE', 'UNION'].includes(resultType?.kind ?? '');
      if (peek()?.value === '{') {
        if (field && resultType && !composite) {
          problems.push(`${fieldPath}: ${resultType.name} has no fields to select`);
        }
        selection(field ? named(field.type) : null, fieldPath);
      } else if (field && !resultType) {
        problems.push(`${fieldPath}: type ${named(field.type)} missing from snapshot`);
      } else if (field && composite) {
        problems.push(`${fieldPath}: ${resultType!.name} needs a selection`);
      }
    }
    take('}');
  };

  try {
    const operation = take().value;
    if (operation !== 'query' && operation !== 'mutation') {
      throw new Error(`unsupported operation ${operation}`);
    }
    take();
    if (peek()?.value === '(') {
      take('(');
      while (peek()?.value !== ')') {
        take('$');
        take();
        take(':');
        skipTypeRef();
      }
      take(')');
    }
    const root = operation === 'query' ? schema.queryType.name : schema.mutationType?.name;
    if (!root) return [`schema has no ${operation} type`];
    selection(root, operation);
    if (index !== tokens.length) throw new Error('trailing tokens after the operation');
  } catch (error) {
    problems.push((error as Error).message);
  }
  return problems;
}

/**
 * Keep only the types a set of documents can reach, so the checked-in snapshot stays small.
 *
 * Each kept type keeps its whole field list (so a field removed upstream disappears from the next
 * snapshot), but types nothing selects are dropped.
 *
 * @param schema - The full introspection answer.
 * @param documents - The documents the snapshot must be able to check.
 * @returns A snapshot holding every type any document names, plus scalars and enums they use.
 */
export function trimSchemaForDocuments(
  schema: IntrospectedSchema,
  documents: readonly string[]
): IntrospectedSchema {
  const types = new Map(schema.types.map((type) => [type.name, type]));
  const keep = new Set<string>([schema.queryType.name]);
  if (schema.mutationType) keep.add(schema.mutationType.name);
  for (const document of documents) {
    for (const token of tokenize(document)) {
      if (token.kind === 'name' && types.has(token.value)) keep.add(token.value);
    }
  }
  // A worklist, so every depth is followed: from each kept type, the result and argument types of
  // every field the documents name, and every input field of an input type (documents fill those
  // by name inside object literals). One pass over a copy stopped at the first level and dropped
  // nested types such as `Organization` under `AddOn`.
  const used = new Set(
    documents.flatMap((document) => tokenize(document).map((token) => token.value))
  );
  const pending = [...keep];
  while (pending.length > 0) {
    const type = types.get(pending.pop()!);
    if (!type) continue;
    const reached = [
      ...(type.fields ?? [])
        .filter((field) => used.has(field.name))
        .flatMap((field) => [field.type, ...(field.args ?? []).map((argument) => argument.type)]),
      ...(type.inputFields ?? []).map((field) => field.type),
    ].map(named);
    for (const inner of reached) {
      if (!keep.has(inner)) {
        keep.add(inner);
        pending.push(inner);
      }
    }
  }
  return {
    queryType: schema.queryType,
    mutationType: schema.mutationType,
    types: schema.types
      .filter((type) => keep.has(type.name))
      .map((type) => ({
        kind: type.kind,
        name: type.name,
        // Every field name stays, so a field Fly removes disappears from the next snapshot; only the
        // fields the documents select keep their arguments.
        fields:
          type.fields?.map((field) =>
            used.has(field.name) ? field : { name: field.name, args: [], type: field.type }
          ) ?? null,
        inputFields: type.inputFields ?? null,
        possibleTypes: type.possibleTypes ?? null,
        enumValues: type.enumValues ?? null,
      }))
      .sort((left, right) => left.name.localeCompare(right.name)),
  };
}
